---
layout: post
title: Given Episode 01-11 END Subtitle Indonesia
date: 2019-09-25 03:03:00.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17850'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3001&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/07/given-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '3842'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1654320558;s:7:"payload";a:0:{}}}
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/given-episode-01-11-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-KGvKkdZrR3A/XSi1onESKYI/AAAAAAAAbn8/yWYwb6FliQEc1ewpyhewmXEWat6I1Kq3QCLcBGAs/s1600/Given.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/09/Given.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> </b>:</b> Given</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Drama, Music, Romance, Shounen Ai</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 11<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 12 Juli 2019 - 21 September 2019<br /><b>Studio Produksi :</b> Lerche<br /><b>Durasi per Episode :</b> 23 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 8.11 (MyAnimeList)<br /><b>Credit :</b> Bakacan</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Suatu hari, Ritsuka Uenoyama mulai merasa bahwa bermain gitar dan bermain basket, yang sangat disukainya, menjadi membosankan. Dia kemudian bertemu Mafuyu Sato, yang memegang gitar yang rusak, dan memutuskan untuk memperbaikinya. Saat Uenoyama selesai memperbaiki gitar, Mafuyu menjadi benar-benar terikat padanya. Namun, setelah mendengar Mafuyu bernyanyi, ia meninggalkan kesan mendalam padanya.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Given - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1S2wZB82EWaEod5V8utooDBxp0GQ4CIW4/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1CqlDVVNzp_n-q3UeWYYk7boKckYJyhzI/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1EvfCWgzM4Nu4j4K592cnkwLwiABUAjrm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1DN54pif3DFvQmTwjyNTV4vesy33YbuNa/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1bmv_oGDcqCqEeiXDf0a-UpedMzefFxnU/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1dGO0l7lytHdOf8vn4I7AXzwsLbgChSuP/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1fompcfCIhglt-kbrYeobbODH4vUdP7Rl/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1yc4q9uDnL53RtdIBo3kQXQTcZI437hCh/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1-7yEzwYtIIoezdJE-x95789rPQmUrVvM/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1FBeDXpUdQ9uosVd5AaDzMoTOwHTgo9cj/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1LQ7DagEdoRkDwXk5BF95Q0FNDe5JQshw/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Xbr3wPjn8LIJoOPekwcHFDhHM4oILgBv/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1zDLENsnZ-9bMK0UqjseqLUnfOKlLYOvk/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1vX9zIXr3r-8sJH_bjIxXsXFMGElOVrZG/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qPerAPy3Rg1d4ydhpVKp-WcqzD3WK1oe/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1zW6gOlSBF70J6AjFFfqqCJldC6Ah8qIp/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1VUhlxAlgdkvZdZ3743kCIdKJ8btmrn8Y/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1H9ZrhEZ2dl4yHCrxJ1cHPiS0VUnf5xQS/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1l6fpGG0a4DBT5FUplf-pBH1xO13EygZu/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/12WdicdXxe42Rg7WxKki_10hUqJ33Kids/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1d5twdVYRqd_efzcYLSU_12YDeoHfLGw7/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1TkANiqLgoylcF61yPEDGgQ3TIErtg4sn/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1pq97QhWq-b7RiWU1_5tSOtg6Ei2tIDFr/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Mt4KASoewwcPM-psHklEOV01ayKv3QG8/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1s-4Wo2mNrKTl7D55E1TnONJ6C8z1V-6j/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1HfgxOUx_cHrttjwjZulylvvuivrprppd/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/156SMzxyolQYxNSy5RXU7cdO4uyFAnOQR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1HSvMFysuKqEYytVygeVowMGK5M9W6R3h/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1twBnOpLZnSgEoM6pqWtUDS2AtNHyrVVD/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1Oor9P8VQjChnQ0CtOc_2eTxzIii9ipRZ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/19GrUkZTqfB_qIh0t5_i7dxanIrbfjrcB/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mGjm8q5XODC3pGhuGwiwhOvo1-gIRjO1/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/12nBjaRO5PapaxBT5O95XV33WwFoj5MAD/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1u9Auduk0LSuGo3RC8yX0WWS9qFlZ4278/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1-6Y1DZQoBk80orMYFn_W9iwRdeqLBDq_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TKKzaQCApg7c_LOO_6kq-pIJqGtj1cYr/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/18-7plyCiXWc4A0wdZokQwJLOGOmG4jT8/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ySmj2ILri7rzh781bh3bS4sneGkw25ia/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1kEsps1goNklSMkGrlyFyqlMcKY7QZFOj/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1geyBl8E093yrxx8EAcSkKE9PT6uLk--L/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1cwVzuNNksjKiaaHIFnXkEOQKT4cfDM0b/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1FixytfASOnU_pzUsf_PVbcl_m5McyKZl/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ciwBUh9X3p3KvCx_4us9FaggNnBHQmPW/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/13dVCMWBzwKM36XehvFsZtAtOwdBKlbQc/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1el3iatFwqxyfyjHe5jtkRDCsmTVuMhKU/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1tUANGlhJ3nNtqZ2R1MA8j8F2CYFZBQkp/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1tOT4quepjAaaBjmkpxxH4SqcGNSd1v6B/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1A3A-yRC2NVdC8wHhIlqHsFIub73wWzIr/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1-Ecg-ywQi7Nj2jJ6o849_GNKZ6r7sqyq" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Q0uAPpYlCskpsR369SGVEN48JchE1F_i" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XPaIs44R1nW7UqzfwpnfhQVAhFZ8lkv3" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-6oSQQdXyCvuv3ulkwWSzH6xM_euR9ai" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1MDLdgos2c1_q3-WAfmBHX_j6eVuR0YXN" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1snf5LAqJmPXkHrAH_fXuf-bsiCiKgk85" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pIGhHLJJMeOXJ_LvcyWeWMSvA24ta80G" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1h0H7q5grRGhunmYxr_YbjOJUF-lXa1vb" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=195lBofJeXoBOT6RTWPSnErWaTr6WLpYN" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Kzx6XLsuAqHvfATr_sj6ub42BeeoOrab" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=180Y12Cdo6x3iBjL9OirqajhP-noru1Xt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kN4bJQV4iXODDXjV9EDR_IKTOlv1hnLa" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=195lBofJeXoBOT6RTWPSnErWaTr6WLpYN" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Kzx6XLsuAqHvfATr_sj6ub42BeeoOrab" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=180Y12Cdo6x3iBjL9OirqajhP-noru1Xt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kN4bJQV4iXODDXjV9EDR_IKTOlv1hnLa" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BQ2o1yNQ1e0iie-_D_e2yRPR53GRLUKm" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DraCyud9yDjszNNTFmOUoStIoBByb-Q0" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1207a_dqyHc9D-SWsi6iBwmXQoHAU97Fn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mPadd9256q-1SosUHMr49SaypRVJVGCV" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BQ2o1yNQ1e0iie-_D_e2yRPR53GRLUKm" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DraCyud9yDjszNNTFmOUoStIoBByb-Q0" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1207a_dqyHc9D-SWsi6iBwmXQoHAU97Fn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mPadd9256q-1SosUHMr49SaypRVJVGCV" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1uRFaBdIuEhijwQDMDVx80AG6ERQq5g4X" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r4cg8_2m808rGsUkf6oCX_k_yJ6fn2js" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R-w90_JYMlFNek-d3SjYRSaCEOO2bKZV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I4RbqV079e9Ra-CyIA9sa8eVvdVxpO5B" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1uRFaBdIuEhijwQDMDVx80AG6ERQq5g4X" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r4cg8_2m808rGsUkf6oCX_k_yJ6fn2js" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R-w90_JYMlFNek-d3SjYRSaCEOO2bKZV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I4RbqV079e9Ra-CyIA9sa8eVvdVxpO5B" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Given - Episode 11 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1V6oBDatjOVzREBZIQluFf4NNSvEpktzj" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17WatKEmFlQZZLgsIMrZbSJv74Qcx9X4F" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15dP6CLcYtjJwZi42fwi0yyGTpzGy_iF5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bHgKANBtGoXvVfS4u3WJ1q6zB_hw32m-" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1V6oBDatjOVzREBZIQluFf4NNSvEpktzj" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17WatKEmFlQZZLgsIMrZbSJv74Qcx9X4F" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15dP6CLcYtjJwZi42fwi0yyGTpzGy_iF5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bHgKANBtGoXvVfS4u3WJ1q6zB_hw32m-" target="_blank" rel="noopener">720p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
