---
layout: post
title: Tate no Yuusha no Nariagari Episode 01-25 END Subtitle Indonesia
date: 2019-07-11 21:55:36.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '16525'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3751&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/01/tate-no-yuusha-no-nariagari-subtitle.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '4212'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1653472337;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/tate-no-yuusha-no-nariagari-episode-01-25-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://2.bp.blogspot.com/-yVkJgx6sbE8/XFId0J8VYVI/AAAAAAAAJMQ/u4BipgQmoIAxC3AG8wGayTnSb8FLpmtngCLcBGAs/s1600/Tate%2Bno%2BYuusha%2Bno%2BNariagari.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/07/Tate%2Bno%2BYuusha%2Bno%2BNariagari.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b> Alternatif</b> :</b> The Rising of the Shield Hero</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Adventure, Comedy, Drama, Fantasy, Romance, Seinen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 25<br /><b>Status :</b> END<br /><b>Tanggal Tayang :</b> 9 Januari 2019 - 26 Juni 2019<br /><b>Studio Produksi :</b> Kinema Citrus<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;8.48 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Bercerita tentang seorang otaku Naofumi Iwatani yang kesehariannya menghabiskan waktunya dengan game dan manga. Namun, tiba tiba suatu hari dia dipanggil ke sebuah dunia. Di “isekai” tersebut dia menjadi salah satu dari empat pahlawan yang memiliki senjata legendaris dan bertugas menyelamatkan dunia dari kehancuran. Karena pengalamannya yang kurang maka dia dianggap sebagai Pahlawan Perisai yang paling lemah diantara pahlawan lainnya.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Tate no Yuusha no Nariagari - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1DVh5k8qqfxODE7s-bo2pGnuQ5HjopHLU/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1nLt0kVNRDZ-oEWs_LYdHVyIchvH-S63v/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1R8COPpZgvUfEtRA46jCibEqpR6eLLAIH/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/11o_aOZVotwEvZRiE8e0-KneMttZKDsoa/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1e1kDdwpMfQ2yAKhiLUjAlSzgP1PrDI-O/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/16i3l9aIxWRyweZjX6G-o9ZIZ0WfHtNmp/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1H4dVGL06B_P1JGA4KN9wBbdTtSAj5Igc/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/11L3jmO5Du6o6uQzpPH4L6oLEbf0zRElR/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 02 </b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1FlSEDtI-MsjvVuKro6Kkv5g8JIW6GAFF/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1B__12PXmHvC7cFKAtj3LPDYYSRwqrfuO/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/164NlyWbAxCHthqg-at8zHiLKcdgKZrT_/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1s-sbfrU4gmg4ubqety2vnbQAVQTsi5mR/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1CcHan_C0XXx0b_rOlC9oA3Dz-LA9m5w8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1zOj3EPcQY7f6vVXddey01kaGDzOMYw7Q/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10m5gytGROKBjIaKUxkQKJx6W3v1RAhBl/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1v9vevuBhly6hAyFXaFgw4SHKlIDc50-V/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1HaKUnkXG397dXTrp-jkK0i63zOG-CcFi/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gHvCuFk8FDdutSWamegS9H1C_dEhGP5p/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1SiqR8zXliZ8pn2Doi1YoXOPFMvuHt44m/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1PBkFo8f9LprHG_u6C4MA3xjpZzWtIc2x/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1YuWMZRdkEqlqwQRz5CaC5HB7VZxuSDms/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1PEBb0JAsd4i9YiAoeJRDEmxWaSz6OeBm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10RMA64VsjfYP0pWxnWWjq2poxcOqO0Pk/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1IwSQBpVO_ZyzE9LOApbYZ5_e0SGMZ_wG/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 04</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1XSH6SCwrNs1S2TDiqsANRrmJ5YHznept/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1dGlQyBK6fjMkJnTbS9BoRzLC-53Zl_Rf/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1jH71nxJWox5Lv_OYJQ577cCBMxngeyio/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1iJDTQ3C8dpd91PpLYTSK1FVf1Dg-gKC3/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1pyc91V87eWZv4FmtXuE1TnMeRv6avADX/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gEHah44BrbziOLQKw9HNF30c-FNQHRmj/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1wf278aQcQUIcCxW_uLHGK-mCVOG0nwPV/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1OMV4YvTKhW8WEiul23n5Ra5D2z_WvWIq/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 05</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13-3kLTBqnp1fgND_dZmHsgJRMDzCra2-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1t_N2wGpKFFOhYCEkzgXvnSmO5nXtiri5/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/17avqWvNeVUW9arr_xH0cci-nzI8NPXy9/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1W53FhribPGfwg9lTqxOQS6yBcTUktYk-/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1pANZZvn8J5jtbDacNedmH6MWmkZHGH7i/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/161jy_gYkJ-yRzEfl8QjTCrOVODuL5NGg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1T7j6vBaX1R4skFpblZLJxpBaMr8OXEFd/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dKnknEbVItV1arZawHKHqChwQmLls2oU/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 06</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/10jpCM2cBU-AEaWsjlFTo-ANCKoVeK-Gz/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1_CtgbKWIGNHGSEPL30CVTjfJ8yZ9Yz1K/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1dPF8v8NrlpcubTiiWNyAbVlwpNP2lIzt/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1hf8AP53OmkATSpSTHw9db8NvrC0tm023/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ygJmkfHnmOJGPuQHyGP4J_u0mDKzD26J/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1w2eyf8omMWswoiHa48oBjS0PtL5CAGFd/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NqDIvmSNIb7lKh_UMpneEQyYzzXvOlMY/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1MlQE5lPtGNCSC_u1uIi6F3mv8umB223g/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 07</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1U9qvw7nWUH4nAX-3j8bQq52Z1TA2-JIE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/14IUUdKHjE6mX56KuIBQjMQxbGQ-oQih9/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1uznZvG-TN6XLc0Ku4v32q1LWitBUTHdj/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1rJuwPd31KUeskQkoIB8kie3gX27z1hgK/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1BsRewkEmdkf9VwPK12SFEkXVp3-on5co/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qcoZ2SWHzFGtKB8uiKXUc4YjRUYR2l51/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ZyHsliHfcyGo-Hy9vTZ7HyQABpo0D09M/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1no4-7P4wJTS4RslQHPhi7KRW9SSrOgbo/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 08</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/137oenXFRxi9volndf0hk8Nnu-Os1xhJS/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1nW6_VGahFaZMQV70FapKENYdDPsrW7_C/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1tqQkI7hyFBPydwHpwPUJEVfY95JCoycK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Cq1tl8qp41FjREsAGy4Ni1tU3hslbzEJ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1mqDXIk7wJhjodyS8uGKJ-Z52LBK49SrP/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qmtUYY66RYSyQ_m6jf2aWnxDum-S-yY0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1EXFs18f75DSckZeuv27iAzsxOw2Gzgix/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1lmdP7k4SLfreV_F99w9nbNtU92RZR7Kp/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 09</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1HqumamK2xXGRpyTxq-NX2zUuLo3kGoiN/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1-D_mjuUvqJbzSjs_Rz3COOVFoNVNkWFm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1MY519I8uWp6HOGiejzfVKR6MCWsVTb0z/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ykuNyzAS73BA3PLovl7kMste7EyF16Zw/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1yE6yOGLUSvgtwRlKB3lgPJ_F8ung2SD5/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ue5sdB5tqaRCNt5OWolRxReMmbM_Rj_b/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/14QJ9KXVw7Mo8QCZaXv9ENnaE8cpuTfD7/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1MWxdaXV6tph1Kz9mwacsKq64I1yECJnx/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 10</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1C-m8DeCaNf5HSBe0dzDDUU5IIe2EJxjT/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1cCVAPH_Uoa-FoXix3mFhL0qs927BA9CO/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RlbaJpTB0YRqPeuxIKzQhuj3-BqAcpMB/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1yS3WhiKrFfLSgLVjXPkPs8y1xOAqx7NO/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/16g5LmxQyC8QJsB92YW3STwF9NYdTjHrG/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1tfMpN_WZkl0EbTnWLcClwTBba6VYqQk-/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Jq5EYGG2R8THpNfkTxS_LzQpKul6f1qg/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/18trVdOOfxaJUbw4o1KN8Ka53bKWxpuvD/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 11</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1fLMusCVXPC3i0OKnqB5wd2DBI47nZXcM/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1mwEolzH8EmlRczDOdurMFILLU1tM5bLl/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1gTk4-tU8sELGNRhDdq60TSOdJb9zeK38/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1wuWJlygF_aMKtHZbm0Mhd_3E4ecraQWj/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1F_qr95kJikn7RcsC9tK-_uf5cEoxZ1Bn/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1G-WEgrdSndcADT96Y1pH4pA2t3uIdjTB/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Y9RE0p4PKW62g2QGHl8w39ntU4sO7l8I/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1TOkEQbbIp0kdN5c_Bgefhm_n3RASyinl/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 12</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1n4TVzqbTBH65BXVcwu6zlD2SGNvXFF1I/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gFgDANNNHN0bp2vOqP3uT_3dLUASMrOw/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1L8f4aA1gY9HXYHkw_D-vXUBJZcWrJEuO/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1YWqf3OKMTWwOKRUtCoHr2DhYH_tGUkG1/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1bwWKQ34qYJyn6Z8djw7Wx93nwS0qtEMa/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1m_TNUh44RtIOJ1LFrkDLZdznea1iVway/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1SkpszQKxQQ5ujq138Q_B1p3w2872_pD7/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1TmSm13nyvMmC5z3XIcYlQM2jHY5IVHZ1/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 13</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1guzfPuxK51AYYpTTh6ET5yTQkccDsII7/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1X0n9hhKmBro6eFhTN1qTRuRu0BeMbi92/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1FrCYn6m3mYyVwbe-ySOIYSN07DpnMUNV/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1h7pZlZKSvul4kEdGfF6CM9oeyQUTzGYZ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1Ho4rVq2ucV9l_szFn2g-1JCh1No17Wjq/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1WdL0Rb5n7ivMfX0ZEFveAeVXXE84gtN7/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/15cLU-we7aqoPrgNe_KCvaMsxxgzMbwdb/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1S4t848u48qMLhZJ02WrgGKc65yHjWLII/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 14</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1E5YAWNdps1lKmeYbUksDEEmPbj_WcL0z/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Rf1EImZpmL8wCKdBig-Xkuv2Knh6arij/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1n2WLr2p8bOfxdZebAR03m7ZDRSxREAzC/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1a2oDSB2FaVxgkaemk5BdKbnzj5BPm73W/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1s_6eWzRLftv59DPkKoUPXC-pzbCfE1u4/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gxuO_N9BIHFzCnm8YEetbcPZTph8Of6E/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1QnJY6NB0Fefj9VuGbVhw8FUf3ZxnGp7c/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1X9853odfJ81Wpm6xTcA_e1nBDR04hkbf/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 15</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1GgzG-DHyL0Jn5sX--SQ7w6EmBNuJ9wwA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1XDBd2oeWKaTqxOhEpOxKuHsKIVx3U6s6/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TuIRdPvkL3AgOXzvRJwQxnwwIA9pPkJY/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1H-m7ftuIAvS3SQo65lCfRTalZThD1afU/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1M9ESRGngLQQkIr-D2IvO3P7WW-pcXLc3/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1agPT0euW5MzPYf7KVXK6ByQFHyVbo6PR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mlu-QhIPCljhuJ-XpOC5X4r2EknHhJBI/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1MD_WgEWRvWEvJCNdwmq2U3-mSyq94cds/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 16</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1AnHdgwbLUn-P36_KqUu-iEUCUsXyhURO/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1HS0W5LYiobTr2zgqqCTje54s8yHj4lPJ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/103FcMmMdpzGQNDVIfMrWiROPOcivS2ni/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1tMQxPl-ApwYd5t2QaNZhr0IuzJZfSQt5/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SqAU0eD-Za30lnf4Nv5ng2JacSA4ZgBW/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ZX9jFrKU-hOhKwrqTh27JyE3AY3eJPfR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rPcGI7MBdRo4Fu1qBtUiTBbpQUD4n9bv/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1vrWYvQv5PnclBBkasGojjxKT05O-V1kI/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 17</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/16-oBn6vwH-dIj57oaywy1LKjzkTE03vn/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gfcvkX0IvifK5UduB7dabCEdfB1yetAo/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1PKp-xs5FZqlfhQuLKAwgqVv8UsUok96O/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dH2w7YEzr8jg7UcDf8bzg6QUGceS6RfA/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1fv7tkrd1fvhL39OlIYBksQ4qA6MahVje/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15wh8dBaw9agvn6nnAo55Q_4w18YsJtAm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1BcJefqEGMxb2GnRS8CS6YbTYZ7ZnvtU7/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1sV6_RbSIZHtthVZfgcj6-_qKHGfy9EtZ/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 18</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/14XBP6SwUdQ0OStkzgf-DPrZyLs-GMe8H/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1wikOi1YZ0FQLaorpcXSpby-wv_oMCTfp/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1dRqK_-mOo60xG21EAV-qj8U9hwZJJwRP/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1LLaxE34x9FUSmuUhmLybEueBsckGdNQ6/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ooUXtGRXBnV9aDzs3B-T_51_W_DwuYbt/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1e20cCE_a_0rCJQ8v1Yn7b0gONO1199QA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1c62kt0jyrWhFW3iC7LZdjhpkGbV2CPIL/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1LeAqRLup7Ioy6i3H44-sHIgN484CXkDS/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 19</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1SOpcII8ad_7hsfmt2XC_4CfIj-hulO8X/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1yvL16VupkOg-H7HIN_nkAv1Lpq1t2BDk/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ytstLeX8mJOMFadS6-wANKni41pn_mX9/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1QXOzmumDAsm_Nfm9_eu1HwI44Iwy9FZy/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1_ZjjRXNa2kOPrbKTE67dVSMppcJXXf9v/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/12mcuHzrzp7pZEnp3JO1VPszwwk7FcwSJ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1_9EIa6kzi9aXzZEvioJEP4vpbAltfVON/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1gBwfeE4s9OE5z77bBzecOYouscEd1raF/view" target="_blank" rel="noopener">1080p</a>] </p>
<p><b>Tate no Yuusha no Nariagari - Episode 20</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/19BEsBLGbddT5tWxBikuoRIJtWy-rOT2L/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/17FLnObQcKRmZWBiID_AMtimm0RQxFBDE/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rxpdRyS5CKynCMdTERghzItRzUX4uKSV/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1fpC9Rq2reWaMbtqC-FwBBE2Jsl40UCeJ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1BUnMnWSImvXzlZHO4bZ-QYhSH9VcHLjf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1X3S5fFCSUayTN7PprHsixzkkRXvHCA8T/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1BNm6zv_P9LoZDC0snhHeGgw7c5_NETAg/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1HsOmfa7HGTU0ov0HpLU15zacKvERrDwk/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 21</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1aXJBcMzWa6OJDsPC9wLWC16SQxaAGEjI/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1R4FYa77hY8-F-asNGRO92IHkc-cxLWjy/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1LYOiciGEMHloter41prpUeL4C0ZN2X9G/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1U-3oCnG5OnaALbnj3fjeMatEw6Jrxh4X/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1i62lyoeUbo439UEkxnbmeBCtfVRkD_dQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Fyb5Q5113HDKz0Fa5NYLTYSAspZiMfxl/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/15OGLgJgKOWSSIXaFXQw7PngWH5VjKKn3/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1_riZfzQfXDuoNweFDNY81j8XNmHNgdxe/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 22</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Qd6wvXMJDr662oAJZHNVd1AE5Zuq7kU5/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Cdi7d6yMM6_Z0saZymopNFGp_Sx_rkZI/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1IHB1Pwos9TAlN-CgczUxNjhaNTt7D_tl/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1wZzAebnaUY_QOQgFPl-6yTFHXUFIKYpd/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ntkuSkEVdgCNaMyeWXMDlRSoEasMUv9t/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rDk0A5-Yz9NPcZcvSZXCohGapPu_z064/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1nqNmVNPPZNgSMHdrpQIBYb5worTTDgwl/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aQ1aPyW7o6xnxwHsVHGR0mTqTzqT9js9/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 23</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1ti9Iiv15ytkUa79CiAmgXV-qCJ0hu0Z9/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ljzpTOuuylScCT8QhkSo_W_imHxGhNgI/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1iawEuRfOZNAWjMBpAxs2r22Fmo_Xd7RA/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Yrl_ZBPlUUGixBc-QvkhHnBMEr-lFut8/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1zA7KigTV1ZIvd_IOyW-Q9sO-Ig1WMytI/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1JrZImEVO-UVknJLjyM2tiE5AdWXdHK_f/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1_kN6uVovKe-_1GkxLxjkuYHtGrDrkpue/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1wpsn2xLrtJ_3Ics5afwavd4cgIqTZa47/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 24</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Q8CCmgaB8UpofbIJ3c93cLmQ8FunWtyp/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1CHapajzflqjd54otbk3fdklPi_wDfaqm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10fkomsosmyMnu4Men2yyd3BwwAj-dJ-K/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1FOd0e9-xTrUYktDrnIzvkd9m6BsbjwBx/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1hSXqsh3q9OENO7kUKHu6Kuaj6xr48j0y/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rmJ56Ds82F5GbR4IIBFy5E6f9mIILcJm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1IKtkl_SVWDHq2sXQnwPwt8Mic8Ccq8yJ/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1VLuv4JdHqwWnA1SCrvN_QA0il73bfA4C/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Tate no Yuusha no Nariagari - Episode 25 END</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1JpIHc0JC1g2PHkEOAG61a9Jd7w3MjE-M/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1-KKL91_7vQTIh6n8OBJLrKNbrT29GHwh/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16pFoBnDTTJUnYxZgW1hqsEpTPCbklIP9/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1WMkEkuwgFss946F6i_jCn81EKRrPfdLA/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1Vbv2kTO3ct3-mAf2bgQld8r6DNJkAvAf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gD7WArjZLGdOkq6sEBNHXZXiG5KK-3KS/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1s41DQc41z9OOJJ73T9J-Cqg32w4D2-Zm/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1gvI5B1Qus3ErfJf2db4FcGEMDh1NRvY1/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"></div>
<div style="text-align: justify;"><b><b>Download Batch</b>:</b></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"><a href="https://www.ciunime.com/2019/06/tate-no-yuusha-no-nariagari-episode-01.html" target="_blank" rel="noopener">Tate no Yuusha no Nariagari Batch Subtitle Indonesia</a></div>
<div style="text-align: justify;"></div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
