---
layout: post
title: Toaru Kagaku no Accelerator Episode 01-12 END Subtitle Indonesia
date: 2019-09-28 02:45:53.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17590'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=2851&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/07/toaru-kagaku-no-accelerator-subtitle.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '3823'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1663337533;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/toaru-kagaku-no-accelerator-episode-01-12-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-0v3lNvpOQSc/XSj9hnWZL1I/AAAAAAAAbpM/qCL0Byg-JNAljjjpMFshSkU1kYV9MjaeACLcBGAs/s1600/Toaru%2BKagaku%2Bno%2BAccelerator.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/09/Toaru%2BKagaku%2Bno%2BAccelerator.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> A Certain Scientific Accelerator, To Aru Majutsu no Index Gaiden, Toaru Kagaku no Ippou Tsuukou </div>
<div style="text-align: center;"><b><b>Genre :</b></b> Fantasy, School, Super Power, Supernatural</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 12<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 12 Juli 2019 - 28 September 2019<br /><b>Studio Produksi :</b> J.C.Staff<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 7.34 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Esper dari Academy City diklasifikasikan ke dalam enam level, di mana "Level 0" tidak memiliki kekuatan sementara "Level 5" memiliki jumlah yang luar biasa. Dari beberapa juta esper yang tinggal di Academy City, hanya tujuh di antaranya telah mencapai Level 5, dan peringkat tertinggi di antara mereka adalah yang dikenal sebagai Accelerator.</p>
<p>Toaru Kagaku no Accelerator berfokus pada Level 5 terkuat setelah ia melindungi Last Order yang ceria dengan harga sebagian besar kekuatannya. Sembuh di rumah sakit, Accelerator telah menjalani kehidupan yang relatif tenang sampai akhirnya menyelamatkan nyawa Estelle Rosenthal, seorang gadis misterius yang membawa foto Last Order. Sayangnya, Accelerator sekarang menemukan dirinya terseret ke dalam konflik baru dalam bentuk organisasi jahat yang disebut Tindakan Disiplin yang merencanakan untuk menggunakan Last Order untuk misi berbahaya. Sekarang setelah mereka menjalankan rencana mereka dan mengejar gadis muda itu, terserah esper paling kuat di dunia dan rekan barunya untuk melindungi Last Order dan mempertahankan Academy City dalam prosesnya.</p></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Toaru Kagaku no Accelerator - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1_cC_UKypQoTU6rpOlIInnNqHl5G55ke3/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1-mPKedlMz2EYgRsDJKc8w6sP_TYa275O/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GdH4jTm-2roG9fWbzAW-Y7rye7--MG8v/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1JBMJIbPD1v5GMY1nKXbNBHzqPiGFpt5T/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1oh4Foyr2X0je_EXikLPfA-vjY82SYRVu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1_-KKrbzRGORusqivOYLzojRonGIgKjtx/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Vue4CbNmTqsXsl1M2bqhhQ-nzFrXTLBL/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ytx22VlurxRL6BacYfTLIN3kNauCg5yh/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Toaru Kagaku no Accelerator - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/15Nrrh6JURiRhos9pPf4873_TPGfbFpLg/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1S3t3XF_2crYUP1tBaHuatWrh5SiHBSk2/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16yVcLcqtMw9NuJwMbfNXWeaEGo6nQpGv/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1FyCzPMnQDM9I1qAZPlPO9vFr2JODGMlI/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ZMt-TMI6fAo3nrDgFd62G1NVjAJe3s_f/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1u5vxO3q8MDwp1RdwEUnCnDmnzSCzjkHJ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/17xdMz9jvGc_Qg60jy7HVP-KNjwJRy8jS/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1pd2xvEG9illX6nEoWNXNRvffjMDfTUuB/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Toaru Kagaku no Accelerator - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1QOR0eJ3yDh2a8-EDVV3oEjQ6qWty9oAc/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Fl_XL7uphHy2eRVfeAdCRJNG25S2S04Q/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1a7QXG_Ij9YwbhFzr-62-XJsIsybaDKFk/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/149m3wiQVOZuaxD4T_gWr5f8wm9rz4TQ6/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1oVZAPKY_cCBoLYdn4XlQdWCVpFDJNLzx/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ej4fj8SxLSOM_sGOkkn5wFv8N9ujSinz/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rFZuntijCuuKJOF0Kql6bCgE0M7Tb_gO/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1sPRlLSyTm7sYKL3o9BY5oRlBXRn-fOpp/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1A58kljmQqusPCI3-sXYbeaFtlHBRyOZa/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Zsbkg1dc-OKzeA9vVRBS-u9TqeE71Gdv/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Fjin0gMUF7-g0AIYRv1gLOf2ZuvoFpqP/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1KaQoQAfl-UojDmQilzqGle24fizvP57b/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vHEBOVf9vl4eRz5ToJVKhtbNJrdbqspQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1dauJ4-Q2Yvfb_N3JoBhkF0KNVYwCJpIP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rdJ1vnDysmLj6gIcC60RAELlR92KfErF/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1unqn3hGMC54DwrgPcMU8NqzTriwHwRUJ/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1-rNiWSYNqLFgJtszhuCH-lXg8Ez8e9nl/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1B-RSh2Xp4wy_ovnUz1QQEgV6Uu5nEzUj/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16d4Z9ji-fFX_JamrtIyuj8vP85zz6QKS/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Rywj0sYOF0F6NLVOghL3B1FCJFMJXOAC/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1AU8_bsJUqS58Ee2dzCSMG10NnO_qoa9W/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1JlztIhDVteTdu5yUWuTUKa8xUBXNUbSv/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1qs7ZoCv3Qob0Cw8ZRqgBCBjm6UfBrMWD/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1fN7kxNCMvvqwRiftSlPQRZMoQMgUb8Mt/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1_30f5Y6OYxMp1497DyStNOfwxcd2pjo6/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1SaV6Cl3rH5WhRfdmEqVZvZmH-HCwppC0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1YuljldoZn-P7c4gBQQCs320Ktb9NtpGJ/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/16gAjwvs0gWPpxQR2Yheog7l-DQN0vckG/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1s79BljwiE9dRLlE1vr2j4gLd0WSsZrlK/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1fpRk4d-CpkAD4hAZtuICA_vLAOeUjrxr/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1wrS4-68FDr2u1sM2e9S0Q-l_EUqeP-bK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ukA1S28Iku4UGgWxPO152UDPWHPorkJO/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1-G349PI2zXlYWvF9s5fPvLpYtGgTXXwP" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SumVItBp718ot3c2VXBw8lYOacRkbrcy" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KSxSfpkQOhjzVi7z2a2xpLT9zIPssqBR" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1twL-y3ZeescGDUEkVPvAzyOnMeIfeXAr" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BZkMRNNsJkNsLLyY612QnC7nXkjrkRtL" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1n17OtogrZr8j3gteRFGlM76SByNqIsRo" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1V6svQZ4OLC3aoRu0_zMJANoD-vBVI3PC" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uwyWOFQksPhqQ-PmVabPmnuLlVw-Rgi0" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1vxuuHkjIsUIIGY48QlLfVnJaaIPvoBTz" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FPAN0ZjOccMlcYQR7DaL9-8MeaQa5-v-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=185mFNuNRxlh5b98g3Iy9ajhGH_Efjyfx" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yGdXi1tmATNw0xOnnNCqaoFZ47317JMT" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1vxuuHkjIsUIIGY48QlLfVnJaaIPvoBTz" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FPAN0ZjOccMlcYQR7DaL9-8MeaQa5-v-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=185mFNuNRxlh5b98g3Iy9ajhGH_Efjyfx" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yGdXi1tmATNw0xOnnNCqaoFZ47317JMT" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1A9zSt50ZShgSeEWK_ZXCVybqjjUBy3xQ" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dCxDmsAWmTvaZW7atqMwI-78LX_a35rU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RcrjVGMNHCFom-Oj-wi1DGhiIiHx-dQi" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Nv2OhDtG5Qgho5x7pHqFLPr5cShHWcBB" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1A9zSt50ZShgSeEWK_ZXCVybqjjUBy3xQ" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dCxDmsAWmTvaZW7atqMwI-78LX_a35rU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RcrjVGMNHCFom-Oj-wi1DGhiIiHx-dQi" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Nv2OhDtG5Qgho5x7pHqFLPr5cShHWcBB" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Toaru Kagaku no Accelerator - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1vrBgNcubdgPFqcZKKg82NZqJ65pgrxia" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hedlrXp0bUIhjPB6kvHLsnhoRlSw9lnU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vIewmnpsQ3oCa7OCfirGr00A8GlBS8sw" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15nbEDDMmWmBUZO4N-s8zCd5cw3JRcb5x" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1vrBgNcubdgPFqcZKKg82NZqJ65pgrxia" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hedlrXp0bUIhjPB6kvHLsnhoRlSw9lnU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vIewmnpsQ3oCa7OCfirGr00A8GlBS8sw" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15nbEDDMmWmBUZO4N-s8zCd5cw3JRcb5x" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Tskt8QjVJnS-sDCTtyxw4OlwN0LLcZ9S" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kQYhwlJ-hgGWnuDwEMYl8nNwMORys4Gh" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VgK9Eu6ck31VN1bG8YOQSm0iArgone7Y" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XVFuw-mUf85pdhZ99NPXhNdCJfNCkZDr" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Tskt8QjVJnS-sDCTtyxw4OlwN0LLcZ9S" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kQYhwlJ-hgGWnuDwEMYl8nNwMORys4Gh" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VgK9Eu6ck31VN1bG8YOQSm0iArgone7Y" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XVFuw-mUf85pdhZ99NPXhNdCJfNCkZDr" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Accelerator - Episode 12 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1wXM6AaIQm7Zyr1R-pYbj0B0ooxbPzJPG" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hP7KF4LCOuX_6ZPtgD2WLBc3AafQjmZ1" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DF8N7RfyKiU1vkIHfyboWMZXeWv_7zfZ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1emeJhyUtMjZB0AJJvKDy_QwLAQO5DfZ_" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1wXM6AaIQm7Zyr1R-pYbj0B0ooxbPzJPG" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hP7KF4LCOuX_6ZPtgD2WLBc3AafQjmZ1" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DF8N7RfyKiU1vkIHfyboWMZXeWv_7zfZ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1emeJhyUtMjZB0AJJvKDy_QwLAQO5DfZ_" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
