---
layout: post
title: Kanata no Astra Episode 01-12 END Subtitle Indonesia
date: 2019-09-21 16:51:56.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17914'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3001&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/07/kanata-no-astra-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '3860'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1654557603;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/kanata-no-astra-episode-01-12-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-6IJ0MKe-PnY/XR0NObfDrKI/AAAAAAAAa0s/ZPht5otOR0EgGB5beYXWJTlSTqu2zdIogCLcBGAs/s1600/Kanata%2Bno%2BAstra.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/09/Kanata%2Bno%2BAstra.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> Astra Lost in Space</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Sci-Fi, Shounen, Space</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;12<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;3 Juli 2019 - 19 September 2019<br /><b>Studio Produksi :</b> Lerche<br /><b>Durasi per Episode :</b> 23 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 7.70 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Tahun 2061, ketika perjalanan ruang angkasa sekarang mungkin dan secara komersial memungkinkan, dan siswa-siswa SMA Caird memulai Camp Planet mereka.</p>
<p>Namun segera setelah Grup B5 tiba di lokasi perkemahan planet mereka, sebuah bola cahaya misterius dan tak terduga melengkungkan 9 anggotanya ke luar angkasa, membuat mereka berjarak 5012 tahun cahaya dari planet asal mereka.</p>
<p>Dengan ditemukannya sebuah pesawat ruang angkasa tua yang tak berawak di dekatnya, para siswa harus tetap kuat, mengelola sumber daya mereka yang terbatas, dan tetap bersatu dalam kegelapan ruang, sehingga mereka semua dapat bertahan dalam perjalanan panjang dan kemungkinan berbahaya di negara Astra.</p></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Kanata no Astra - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/17fXA2N3wBSNdeR2IWpv9ekkXCV-a4-A3/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/12ppXlzRsrE1_JJaUMJiqbUblx2WKugBl/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1N8vF3SrPrMzJ_RLt6VtWtlIQ2Z9OBR8h/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1StZE0-HAvacb3EfEigSVd_-zm5CDvbWE/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1LjFpkOOKjoH8JJ8xIzdBjl6R_4wSRDOl/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gwOqsdz4F7k_Xb9CLSc_tXqrXdIY5Vu0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1N8vF3SrPrMzJ_RLt6VtWtlIQ2Z9OBR8h/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1x6wDKtxo367ATsEUEA8F4My4GPhaStX2/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Kanata no Astra - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1aYNvt1VzfOJV3LCMbmHlC4OEs9N60iEt/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/12C3vNXfVfbPg-CeWCHbWbpPW6j_S54_m/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1i9I0YBbFnQfZqwJ-5e0tx6BbUYu6Ja9g/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1DfAXDcnR5uZ1Khlq9YFolg2slGxQ6X-M/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vaMfnN4oEdYCemW1Nzpl95rKte6BEm-1/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1IGDWORDoObcez8fL5lcBrPIGYl8WPej0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1kKl5LDVlhwg0Y_8KDsCs-nRfve5P30wU/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1N0DAol_EZw-f0651sXe_YDVxFZOFnTTk/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Kanata no Astra - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1SPF75iBBgehlW_W2n79fLyJF_PJejqKu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1bLlKnRMB73mwT4qg9qxEV3Yfxr13P44M/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1inog_A73hcAeuRDFPg6x70wY9_Bt9bGO/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1WLXGQx63YnMvuk_ks5x0GVdCbaksD-_5/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1gNoBTfB6HPz3AfY0D9CI7F-qSQMKekLj/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1jvUyCcyokrWU0dybsN0lUNyUPv01MSPF/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1sgdavoIlggF-AyHrCfasCVAQBleNWl15/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1i5ELN6Hho-jg4It30unuPkJeGhOvO5EH/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Kanata no Astra - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13_4r5O_92HGfVBPMdXv81c3c9sM4Lg2k/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1cooTX3gE7iQiLIx1YePnKr4j9A7yNIpa/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/14vGHNE8Cn9GepLnrvTtN13_4fIlgsx45/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aun4bWu4r08ZjtnV9_svynTMrJvWl6DR/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1M8rC8OYhQTcZh_KUOgFSImIBqiResJMR/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hs8Bz-k81azP3TvZjxTlYJXmlMtQjsiP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hkNviaeUjJWpeFrvNWQaJ_lKDMvALgS6/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1xFLDRMKSaBV4nYCP6cWP646pM2rOZ-d-/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1kqgiJUQ31Db2psmUAppgHUOS1Y0V3443/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1-LeYUoER3piPTRNG1wasB-6DnZ951cmA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1UdNBoDz0sfubMfem3x4oFCvbzfAOY5be/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dpncJbHnnCw3-cYRO9x5eji4BxsP1Nn5/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1mjBtwSHNKmbZnCm97OCX6yrg5v16As9y/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1OmBKAG8z7__qruYvxIPrWRbSI6BuuVgx/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1cZR3nkZmnuqGu-j3Byz6GoYx1yHdCiHb/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1iPPrEJxod_k5XEYiawyxZEpHk8P3fB0E/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1jtuRpeG5gwHu_6GWTVYzVlfCQay0TEAR/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/12PPJ_QMfCauVkKGF-eU4rvYLNyslPUOC/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1UmH5CjfY2eNS7IP8yx8Qeg6rW381bonE/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1POzZcYnvZ50BLBbkYqj4PkQxHw-PIpbM/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1m7Ij5g_zOLuAKO0sLVXgeL-Ph85zIFxk/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1LE_VUWJpZzJnYrZiRwlq2kErH8YY-A2i/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1yLPfWu8UeOrYQgL5lXncBs_ELVHUFjQ6/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1cyybnHWn6EaxMQeOv8IT8ImuxjzWKnq8/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1WR8sl1FA_15FJmzQp9LxRS6n-cDivf3E/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/13USizbPaQAPQ6YVTYcux0GCBe72mX9fA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GUVpLc7pD9bQiVSJeaVtdknE64z3kZQM/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1VKcCMyOqxjxxlkXqzx1dy71gBiTTnDAx/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tQ1HPk1Ug6Xdbf4lJFEEvmuRcANNI79Z/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1vW0re8xUd3qvS-25q2oOG9pJ3ABRkwDZ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1up6iMLtI51TFGnayhR7csZImJHHbilw_/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1WXYXPX0Cu6wHo6LCexVR1_pz9lAdUb3s/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/16655PmXFrlkmdFaYOVSZTYfV0pWsBIEN/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1NOnVwljCMlOjqkw8nnS0KOnPJCO0i0HD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/18uOjRRdMwccP5AL-sMt_YlbvF5YYPOoK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/105ZS3Lga9g0rgdA0WTQ3De_JytJ71890/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1qCHerCkEgN3IjDxSVzlE7zfKSLRCey9Z/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1w4yeEHnvk8U-4gMpwXDjVmgnyMw5yEwL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/190wsh1vfLKLcm2xxntj8FYE1IuyCFc-K/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1R_YM8TgA2_xGd1nz_BLY-qDyQLSGDeql/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=19WZjW8AEGMKN9iCsrXrwOCOs0HcVCVUh" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18dPQ43PAcXpje1YaMS54uXNupd0rMizl" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14CCZSQu2E5WvSfr9yz6jA7P4Ox4t-I4y" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tlUU-ZXtR1qAu4PgD5UXyhK2KpjbEzZC" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1KKaOyWYTx3r--CM69UKak4Y5ChPg-8SN" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bdLyD0lmzD5TWG62DKbVkI7JjFNKAGxp" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r1rN4zeh_unYEV3J94Lw16TozrMoR_-8" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tlUU-ZXtR1qAu4PgD5UXyhK2KpjbEzZC" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1yyEortLpkycwvDXihP7BgNCRHXOMghNH" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SOLEmKmNN_yp_7qkOvXsy4q3j9zSX1MC" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1A-W5hsaJp9ugeLpWyQoVGy69dRdWwOGS" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zXY_Ayq013d03qCTvwMCsxSmqA0vqqgO" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1yyEortLpkycwvDXihP7BgNCRHXOMghNH" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SOLEmKmNN_yp_7qkOvXsy4q3j9zSX1MC" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1A-W5hsaJp9ugeLpWyQoVGy69dRdWwOGS" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zXY_Ayq013d03qCTvwMCsxSmqA0vqqgO" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1GmRlCTWuZUjSn953BzOf3kVJqjj20O_H" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RFz5hO3Qm6oVvCyP0JShbkm9cTFsTDYD" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Fp-vA1qE-0_jkJbzFIYF-Lmqj3WXmsu3" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14QbjeKzCtOBXFVUe60y7A1h2_-g8Q2Fc" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1GmRlCTWuZUjSn953BzOf3kVJqjj20O_H" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RFz5hO3Qm6oVvCyP0JShbkm9cTFsTDYD" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Fp-vA1qE-0_jkJbzFIYF-Lmqj3WXmsu3" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14QbjeKzCtOBXFVUe60y7A1h2_-g8Q2Fc" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kanata no Astra - Episode 12 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1YyMg2GP_ufPfZ4G4o8WaxsipsMFvSfB6" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ieCJknjl6Z9LtZMrb70uTa4bbxGxV4O-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HzMaNj9SCo2_FTl4Wo_NFZxjJgKqALVB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O53DNu1HSR88quC2bW7LHNzYNkBuFNtL" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1YyMg2GP_ufPfZ4G4o8WaxsipsMFvSfB6" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ieCJknjl6Z9LtZMrb70uTa4bbxGxV4O-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HzMaNj9SCo2_FTl4Wo_NFZxjJgKqALVB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O53DNu1HSR88quC2bW7LHNzYNkBuFNtL" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
