---
layout: post
title: 'Fairy Tail: Final Series Episode 01-51 END Subtitle Indonesia'
date: 2019-09-29 02:43:56.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17532'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=2851&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/02/fairy-tail-final-series-subtitle.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '3806'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1647376708;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/fairy-tail-final-series-episode-01-51-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://4.bp.blogspot.com/-IywbX_sddo0/XFVi_1DDWtI/AAAAAAAAJgE/xi05y6z7FkksQN7wDCVi2hL2QqD6cSj_wCLcBGAs/s1600/Fairy%2BTail%2B-%2BFinal%2BSeries.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/09/Fairy%2BTail%2B-%2BFinal%2BSeries.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> Fairy Tail Season 3, Fairy Tail (2018)</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Adventure, Comedy, Fantasy, Magic, Shounen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 51<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 7 Oktober 2018 - 29 September 2019<br /><b>Studio Produksi :</b> <b></b>A-1 Pictures, Bridge<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 7.51 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Season akhir dari seri Fairy Tail, diangkat dari manga mulai Arc Avatar.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>14</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1sDw_PCriTj1JS2JxZ3ZoI9NjLwc60mcu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Xn2adAb2wpoVZ3nuMXt-3G9BnanCT-Eb/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hXmNBMCHpT8gbGiE9Yg65kBqwKOBHRnU/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1C9venX2TtvZhx9oI89Y8RqFwLzN3dq0l/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1EIkupqrPhOVVO5iKs7i5WoUH3gBO-q6Q/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1WXZ9jiZoC-ssMaoj1a-UC2m5PAWfD7Yo/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/19RG82WC02pJpGChS9P_sw5PlqqT7Pmr9/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ejt4OmAJWeAPN3rCE4ZKgYfd5jmJWtPA/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>15</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1DgiGU_HKfBSGRb_ZqfPDaD5SYTwaRYap/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1952D8zvWVviK9Q2vJLs8jIcQHFjjY4Jv/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1_J6JG1P75mM90AVBLSWYduBhyCEWHjV6/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1pjBN1jHHDD5WfSIaycSewV5UEKTAwEL5/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1kOawI_WiGO8aMQ7gmxcucH5OWJTGKsdg/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/18qXc0t14kU7_vgxxecOXr9UV9ob_0oDk/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1lehFb08uNs6GW8JphtIMqxDcE-eOOaPv/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aez4FJmJtxKACmDCGC224LVdKw_TGGP-/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>16</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1YMsjvhOf7bGvStPT2A_G0RyAnz6eClIy/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1VAA99ainM8cYrPlI8d7VDcOGba2620gS/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mgBwquFXMof6MxEUGfIFH_FCgTdF3RBa/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1YY0IpnPIHnmzqxfXtbUxGFbr_9SqOHsx/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1u09xuVDI28yFxOVxkKrYJaG4H9WWKMrg/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1REcAXWckErrp1p1pmnruASUhHd6z8dC_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1JZYpql3geJQRKLo02pX8MlduoeqtpoMM/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/15C6tfHJ9_LTLxoctKb-Nkjvb5iGzpIgo/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>17</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13ngk0gjUl-DCnErrIOdsDSXTD4eJIiZf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11bhSRhrUqCYNCcbDj88wQ7neG_ovepYR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1zEYF4wErqc3L_VXRuHKvttsPDl4NVmjl/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1-KKvc4jpSWjuoI1eO4TuEiSW5xCppFlD/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1rXxgIJ861o9JmxYyci2unaLAx3BXtIXv/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1m_0sFQDj-zcSyMpG6RlDeejrlm12Ltb4/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ocVaZgIQYx8_NHQqSO2I1E0GZ8qpycpT/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1cZq4cuFAD1WjF5W8R6ht9BANYI5Z1blR/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>18</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Wu8SiZkNorTHShgeq2P45-N5JhDSkpbQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15P9HW8UM3c8e_x1U9ntYmCGZA_3qSvLi/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1t9Q_Wx3VDW9y5aGJRYyFVFx1nkpHNI4_/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1naDaPM0dhFAaTuDSpefljmAbdLTL_nfK/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1jy5w5XZOjPIhe6us-Adxmz24lwB3G3_g/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QOMsEnu3ImJA6QZti2vds0k7A9wW8QaL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1AIIN2hKMWSTjrJ_FjUqnqqpkV2htnFlK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1eN0kBvYx-IyQqKeyOzx7hqwIkQ2NwDC8/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode 19</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1o6BgdVsUwU17d1TmwAZ8W8VRbQCEux9P/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Oc_cMMMa3fu0A92sCaFCICY-Qb0N4oql/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RnSUePjFRmZydGadjdaNU4ipVleSQ3oa/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1VB8DlyP-lkHL44TgvZklnIptErovXM1z/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1MUm2wexF46Cux2w_unwEPbErXIBmqICB/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1xrg518deBaRLBkGIP_5H-HBKWEGMmOVq/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1WyNHGoUKJA1RnfxmrK5PT9Wt0mPsxBff/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ZLeEe9vKMHI0VgLN2ndAQzn3xSnccxdM/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode </b><b><b>20</b></b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1nrFIBhUfZy9wo-cxT4KVX6pnKkQVE0jp/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1g1GxuXIyyvrrKtQ8vjrzOgFcWmG4FDB7/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1JvFCNI_pOc8mx9f59TeHCquC5CyjnITI/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1XiD9Fi2Nzg8bsZimY0agasan2nYrB4bi/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1l4czm85DH9xXxn2Y07wcYs6T0s4vx1og/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1fBSmkadKWui_eMtiwmyRBZR9SoTcGzlt/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1MoMnA21pQhiczvzAcU-zqD7DjDeqaKsN/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1UO_topaldCtQdkge8s7D6vgxhSSh4Qxu/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode </b><b><b>21</b></b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1iWr9kOcliKdKN__dSpDlYDT_hSxOAojb/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/13ujudytHKPHfpc-bZHWT8bmKrVj5ZGOa/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1C4YzJYYPdnhtZ0AdXs9WGGygXLdNtT06/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1i9Tx2HPDb27Z7UUvCe_72za4CX0FKdHZ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1AoWBldcYlevoqObdxg7Lolbg3j6z7w_a/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/14QvdPIqm99YmCNO1ZIXz_nUCuiGyJTxP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1QbJx0Q1Y7ZHgoaT7iGitdQ32Sq5q4vqo/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1tPsSpBNBKtFkgvMTi1tYS6PidM7SQej1/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode </b><b><b>22</b></b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1iG5yyXQv2bNF93MZACUFt6hL_sa1yPPB/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1aJ8Qfu_3O0MsZ0IIShtsAyWVFv_mXbEN/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1IW-1sri23mfbfu0llDU9cpu0wW4WEcKh/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1bF4G2Vzg1gNbqintLyJi_sar6uXQozCA/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vk5UADQ3DgqbfS3AsYhZIQNYsKdEEF06/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1heJP6tQ-rf84ZY9XxRK20zCv189jG1r6/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/100QPsvk6sNKLtTgPoG52D-0fPnlwDN57/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/10Ao9fmOcHGyXkWUWADDurKRDL738m835/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>23</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1VAwCULNxZdd6a8U7UgHXhKkxhd-fsVd0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1yq9vBEdlLOxMf5x23DNgv_OYi3NF9Tai/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/19gaYG1wEdnejye45UQQg2ic4B5OKW9aI/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/15nyK5DxU61oPOEY7SZcCKTT47BKvt2OP/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tmMZG7PfRRMdJSNl2rCQ7YlpX7Cinqfy/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1PEkIfcpySq7T9b4nMpSFfOzVyPzy3vHT/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/14GPJ8V4CrhSl8l0enFGtcpXs-2CQG6jA/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/117Tvsde0dXOF8_DDqdENh9Vz-k6UXOom/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>24</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Yb850yNafUiPxeOBbhypQvggCwub1CPr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1thtExYvXIQ27hU5eReYczXLuuMfkIY-9/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1JnBRE_AxMiiSibzBkDMt88onyd89mgFe/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1nX5ZkqNP3yRrbqeIWtSgc7Zs9wazse7e/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tdO-TjSo5Zqdk7pAKNcdoNA0heIzhHVQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1wOGHC-fxpg15q43-ncGGEJQgmzXRDwGY/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hRiqc9xY5envoXDsN3ndXJxzhuLDJJ-e/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1cdQT_JxjcFlAHuEMx9x9UKEGECT5Tn4W/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>25</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1xuJWbGDt5rreLi6Yd0kfeW0sFSx5xWNf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1y7dsBg5HeZ9BMsWEU-XJuO4p6ZCuFgdp/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10GygzRpmiomlrSLeQzAmW3rgYqazPIU3/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1821fsiA1gN6xEC2px1jWhGsdayV-D406/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1bXWNIhxbYZykrjtS5CgDEAoj304Ajat5/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qW5hm3z_eLCTeZERLYu0ZyvCAJOfMVH0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1QEWgq8wa6wTcFGQis2MF8syxZxTVPvna/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aOU-tKLp30B0027vnXTCc2CoSYLeSCIl/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>26</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1gZPpO4SUyZwUTulqPdTjtIv4zyDNqMij/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1R_HalYXw6ItI8DgPt4y0b7Spo414Y6QC/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/17wlCkvNQwfsZ6USPeCJO1kQ6bVG8JYUu/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1hm_OTxqydMAOX_ZgfD0bgJBcTBXuueah/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1BiolNzfc9zVAbIshmQkDQ8uu-Q4hu5B2/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1oZshlFIS2Cz1z94uEXE28Y5a6MLHHp0x/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/196MtR23Owpdf-F-3659MhBNa5nedD2rs/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1cQWJNZBNAHuXpSnGysAlFmcbYAHvAs8L/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>27</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Zhqk6LgW3yAYEWBdy4VxaSZ3uqChRLOE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1y7R0GS2rq6ttvmonbZHs1Gwl5KbfmaFG/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1BLjL0LluaYcj0qYGrlj8JKNwZ-5AuafD/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1WWV_T8JzfcZdyNpdu_Effh_7ysPpBXlS/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1LrDhTrLzebPbMfH5qJlBhqhoGqI10qNw/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gdifkiS66BwOMLmotrYoTjyumk8KlYGT/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mtJlm781ddZUdZlIWIxT8h8zp1rFeCRl/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aiNWSoXm9UqcDbdkFKKLIMiupUYzN676/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>28</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1XkEcYrb0qVJtWncILAgWCfYMJPUw-P5x/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/13w63uzjpI6A9jIajdM8B3QUFY5NFx44s/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1iO8Kmb3Fod6hFS9V794LAEVVhPZd514O/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1q1ksQWlYdXP0wnyOfEDiglEao_vJPkXE/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SSxzPVr_aZ57hIksPrpMzcPwKUiy27pK/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1uLW0t_c4Yq-Rusazghx8MYknaXvPLnN_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1eNVUdB3j67WeWX3wvhYL9D24djpVAkLC/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1-AZvTcEUaK5noJ_8ui8o2CQI-anWZMAt/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode 29</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1lJa1Bg1cojKXZIf0yJhXSNCBBnQM8sX5/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/19dWwhHkvbcs0FgxoegKbTsbDz2pLGyji/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/15ZNomMJ64OpgdD6S9TidpvEVlIXTqGOw/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/14keyeQHLwsP2FR-qXasfGGvi1_yIIqC5/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1lAtX4nJIsblZC5k71p7lFwY8GyHitkA-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1pdKqN-8A4UuC27gqqcgJ5_4JZTCHz8jC/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/165Ov7MbTGJG8EBIL_fo60bfqTD63LjMr/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1sLYMmOZBrnZQZnfqX7hOXIdfYUvqRrsA/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode 30</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1CEmvOX3LWBMv4_EdFxAbJxiCX37dCnwo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1oW2IPMb5EOt3fpmMrdZVXAqzw6FWxroy/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1XXks80kPfChqLJk2UjdItdBUzyygMub4/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dWgRqr435opayZg2Qi1E0hlLRcfKZH30/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1NkoibeUWi6aSzyinoFXe_rkkZDxFeoYh/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ucm0RBpe1soz5wMPVoZpuU4xF8cREju9/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1-v7SHEoS1W11Czk_lKlxvPdn3oC8OObb/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1UDmng5SUnPlLL-gxqYyTyEfG-YiOCUVH/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode 31</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1FxdK-EUo5iuOmsCaSsThQeV5DoW3stw0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/17z8oShPaZYIl8wrth5e3FemhQzygh6pr/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1K0Y5ID1ODn3kdT91F8z2OPybptAcIHRx/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1mOh3dYXa4bR-0IL1uopuQ__nDmAoDLmJ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1MoTovPRbUfmDelgG4R989_xeyux7jHCe/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1xau2At4wh6d_fFQpf9cnR92YaAolKCBp/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Ptjx6ltaSl9DXx7P0tJmj3MVDpZVte9K/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1UzfMjcQBm0pMOPb0UDhxMLMYHa0tqjWO/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>32</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1G1CYl1oCntxK90doH9CMHHWc3mk_XbUE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1I1x3EqSeMKZFd2aM9m9UDA4W7Q63bNo8/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Oxfmx3KC3WVeVMtvxdh1xXy4zukA8tld/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Z_4j78P4X85VkH8XaFNma39t_ko7_8Kw/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1uazQ6kP8srYpW2HK1y-fctzgq-0pKpI9/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/10JuiVwjURkQFoglpsJIOTr-gcgws7bRZ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1oy8_Iw6kbVM4m2UemcT-jUjc4_Jvo3WV/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/13lpXiCD1fkXGxJZJy3RL5y8cTNbYrmyk/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>33</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1SBKOVwpx5z6NUJJcn3mvS9iDo8_-9n8G/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1k4nDJhP805tEhqDWw4Jf5pa-AsRz-Z0x/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1DCOaI2o6Fsf8_id1bSDdjA6yLJFST38N/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1BYsga5kfbX9tKusi4bnZCTqkAqmQ7DqE/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SGLNxRXIqsGLhk5dhdfF2PSIgXGgpTjH/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/160tspRbQlhn9Y7_3vF-g_4eL2iG9z2Di/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ZmZTfwYXzQHwfHWDa3RoUTmPgit8WySq/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/13kY-TJax4idtHBj7NqXl5MZb_qp93A2_/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>34</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1nR8CJlLY72Su28xHIz-Pd6_qN9cE8ySo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1S2PyR_PjNXNH1aWVaE2bMqSZyTjIr_QD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Hyv61rh4p6g8SkGC2UWH2AKl6uKo2832/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Crfx2RR1yPsmtM0j-Vd5Y_DzSmzmUX2Z/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1La7lIW--yCT6MwpnkQdDOUiliIXA4HYq/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1RWMlfCIv5uOX5zY6iX0jzq4lpfhiJdqD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1fp8_t_B1Jgnz4uIstHwZjphLkXojd3w3/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1gGJ6SgOVDNZdngqcHCvtAhFfp0ZM2-Gl/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>35</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1s1XKDiIP5b1K9f5veyXlaOCbXOekt9Rb/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11lW7lGJ3NJZOWJnciAJpOA3Uryndb63i/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RZ4z2HzJCVC75FjxEFNem95qTf78-OhA/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1kXKDdAQYUM7wdFOdttDM8W7qeZHs0JVV/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/10AoRC1GQ2twaWbinLScaSuSZ5aPeJ4lr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qst-yVASclEqB-zqWopzKLneFHllk0fG/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16rX2lx2KCC1Xzu8A_TaEvFHUrEzsLdGC/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ilhc9eddwNmggzHE5OlE0aeGJuzrO2W1/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>36</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1LIY_d7Ti8K7tAyaUghGQAY2GR-3VPLOe/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1K1vmDS-gFBUx2BmhQg_klbpdpWqmkWmx/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1pabCkmda6v36FzYPttxRsNINQC2BxAfH/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/18Ucrrk41wnBEo8k6G0Bxe50tHuvGDUHH/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1lJLhgaUM0srpV-VRpqUA1oVdhn8QS1fU/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/14IWD6JZiKoM9pstvzk6V_O4lw6iHpC7N/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1_bpVz5T40K39iMwc0CBq_6HEzPKCABQk/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1sqGVDTc-BKt_m4YIHxNgebBxyHLf0LC2/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>37</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1L91ZlPeLXnEU1o_XymzI8bKx2mAuAOG8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QW71aFXBSdmd1OwwpI1xXkoLrNchG_z2/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1L5RGagVpk28AjooYT7T_MtUydAljwzQD/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1z_-w32QuSB6xFz1Ct5NwsuOfEKkrO8Is/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tu69VwivarBx67VHhOLuuiaFsY5Ud1FI/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1R6nfRERKRAYs_BhEikh5xnFHpQn7eZir/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1u9AngxeuF6CBZIsgpT6FxG0HUOlu7QH8/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1OnWzAgpPL6Ccj1sYxM9BkPSFW1B1RJYV/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>38</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/18QkuHwWdNczr8BrajAHIq81y3Trxt92P/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/18223VIlwM8RqvsiNjW86gI39juD9XhbP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/14vOtMFkbYL_eSrZKCo1Dp-JApXyy0iO7/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/15XmO_0CAQEaelMg-lvcU6io0eWlmDji1/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1cZA7ih9iEqFuGFbV5-3st8YDWlueYhaq/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1y24KG-jomajKxNUeiggaut060kuuz_cg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1HbxNkXT9s6ihZjSBFbpr5vVPMcxdMHAZ/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1cWxp9rZ8E3Fsrt2TuQd0znqFoPEa54-b/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode 39</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1J3iEAEE-HtyYmFQCbOPxFTbL2dbZqFrV/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1H-CpAjjdRkF6lSP4gvaVb4Yl39ypdVjm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TeWfGDknuv6use4z6HHCfi2FYc87kQBX/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1t8nAOeKA8gjNfCi96aPRulGWx0HUhV15/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1Qrrc3m26eFIDgtj0YCw4BZEM9EXFLUV0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QrBidJobaX2i9sjXV2KIGa2IR0FiTs0y/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1jdemaNCGQr5SXRsn0xNAjNs2unHYryWS/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1yf8EL0KFQEyeVTkJf_-Brzws4kyMUunL/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>40</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1BUf84BskW84iiDzj5u-yXrTNxQmNjrex/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1HDVRZMUPyuClSl8q_JV6ven0Pc3ZPg-u/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1-q_SCBULx3SqI8dGu7JSvf4qV2gpsz1z/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1D9FZIsFBmFeeT54Nn2BHUHamrnvAtjGc/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1nPRibue8Ezpnc8rlqzmldTv3jbqjw0s0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1vWIDlrmhLs-sVzcJ71cLKq4cVp4IGcia/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ry3AoDeuLx5yZYW6slYofUU_ea8qGLpI/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1DFjLI-EDUeWAs0yWBKWIXUg-hk8V1lF5/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>41</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/14vaIfY5KOZBjtuhI8tOCIWeP6s7VxXNz/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Lni0FGe5GocS6yEgFzj_kUggZrCRofz7/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1AxJePhATz6iZcyp_IMxL_GIboFXIq4vp/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1E70OIWQrkvXFwM_gJWwGD10vbKWnmEoB/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1g7M3tdcA3C4KYX5pyMGfoG23eJgz91qd/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1OueG5cJiCfXo3rFdz_y0h3a_XygIFCKP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ewOeQbpeTUBJV_wk3cRpbF8rVexkf7NW/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1exp5ubvypvQNh69Kin4iIuVCjvkLu45I/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>42</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1VUmpqGnWaiqVlcvgNQMQ2IUwHkyXyFaW/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1NO74OZ1UT98zpoO5480l81FsnRjYX1WF/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1dPaRR0sZWUkiO73YiYZTypmCOfQNN3vZ/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/10NIx67d6RHSaCUB-LO_gIjAPI0s-7nGM/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1hel_A8FU49_LdVdNbHOwhzr7PLceI_pO/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1dyX4uY29Jx5xBmF0CNlAuMa5gJ1eZm7S/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1i7QeP5WGd_El8Bk5djXqGTkO2faBQxp_/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1UPCWlSIIxUB7DJ06i89n8uAtOCUqlEue/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;">
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>43</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/151KlSAzxEqp3-A-Q0WCDgWP67Seg4oHu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15OLnCfcoZiVE0P2vRJuwnol5jN-qGV18/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GgJkubSBwgE7XttV3PXKymb2wwHnw9ph/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/17InOIR2XfB679rpK5Avf71wz0BeVS4ZU/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1YLACccqIGPuGI3ASrWJq8kTcs0-JQWph/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1RCYfxE92yYQ4AhCz9M3xAn2ko5LCf8Rf/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NZsCHTNDwHC8EpyzcrQ8hkurAkxLzwIz/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1F9I-L5sO4vqgRybFptPPUaDAYY8yv44R/view" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>44</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1HhnBF5VHQPZjhpOGCghrFJpbpQltHyaL/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ngo-cbadqc4Jd04fdKTbAMC7qCH0eTIi/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ZY0Hj44RUr9mC4veN4ge5UQ6zfhEm3EE/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1LELib686R6FCTI7wwo8NM5UFC_6DBOsD/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1XqNflXn0J4VTwY_WfpVSY8jZw-TWkC0o/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1nk_fDpENMJ5-JZ05EtTvv9J4B3zh8FFg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hEiD-GXgCl5vutba5Yua4_Q9IBnHrg0W/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dYgrXsyRqAV-kfF5rwIeFyFLTOYjhuuO/view" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>45</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1f4Pe4dHOaDDGZ4DAhjZgC6xSgLMWDY6L/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/19MMMmcqsR2bl3LIR6Zhsm25ItNB5t88G/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1LBZHg5ByPOySNVrpGzasIPjctYrwmq3m/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/19ByTWE1NCmSmgPQT-eRQE9Mu3ykawW_L/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1gb04_WardLxjURpzAzXRqrj3BR_qcHaf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hAwzdD4ClxYSdeU9LO2atkTjZadEUmzc/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1xFqZ6z-px3Otf8hv_Wf0Vke53yS5NFBC/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1XA7kVAszu7qYTHlh7B69QWiPAHKs7LPC/view" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>46</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Rcrps2NnvDSKdGuUiYoEZMexH_JJBOKx" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1utNdtbFNRqVYlL7YEq3ClJxWA4aoroOX" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13JJBGvI1UL0igMJDgGJYKk6Gk5XSa1b_" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=10lhViwhMqxrXodQ3G7B0O1QxLz8E3rqj" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1zDUvc4jOo8jlciH_56oQuhk4RqeFMIO1" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wMJONj-k3EkEkLR2st1jFQHX70TZPQuv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19_WI5WTI0BCb5tBC1su_6zD4WEWa8Bqq" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1roFtPrP7GLx25INGaMakbY-gFq2svkIY" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>47</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1cUwwxExikrSnJWIIMQc0XFRux69zgdC3" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18SQz98IpgOD9EynQsWwHWkgRXwwGNfy0" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ubuMO3hOiMtD6vZIJBgs0boQsNv6ZSJr" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FHntvnZpECUTWKdZ70cGh8uAVHgUopxy" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1cUwwxExikrSnJWIIMQc0XFRux69zgdC3" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18SQz98IpgOD9EynQsWwHWkgRXwwGNfy0" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ubuMO3hOiMtD6vZIJBgs0boQsNv6ZSJr" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FHntvnZpECUTWKdZ70cGh8uAVHgUopxy" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode&nbsp;</b><b>48</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1uDbBFIQWQJXu1y4khuI2VePRRvjIaF12" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1LFX3cMctT_VRssaEcohF46aBApsEi8m5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1eMFsamS2Wkeqe0YHkxfOZWCkbmH2-e7V" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11oXPqx407JCMhtjFSMLRUDURJYcnv7Zy" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1uDbBFIQWQJXu1y4khuI2VePRRvjIaF12" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1LFX3cMctT_VRssaEcohF46aBApsEi8m5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1eMFsamS2Wkeqe0YHkxfOZWCkbmH2-e7V" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11oXPqx407JCMhtjFSMLRUDURJYcnv7Zy" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode 49</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1RQVGtqeQ9CIIN44KmBm8rqNvWcZYYLQo" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VezozaT8v_JmTP5DgNjoKsSWdH4ZnMxZ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sYwZNrNCn8QGl2TeaDhXphHLGUwNLWE0" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1qiCLF7MwVI-ENgvQ37gq4hf_kw31OPa6&amp;export=download" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1RQVGtqeQ9CIIN44KmBm8rqNvWcZYYLQo" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VezozaT8v_JmTP5DgNjoKsSWdH4ZnMxZ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sYwZNrNCn8QGl2TeaDhXphHLGUwNLWE0" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1qiCLF7MwVI-ENgvQ37gq4hf_kw31OPa6&amp;export=download" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode 50</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1EVWOtS1MA00S3KZzfhHoMVgdA6wO0CWU" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k88Qlot0orIk3YzhI3pWjkPsvK5c8P-z" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OXeuBqBvQmOweENHwIsBHoO2kG3rvS-m" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1l5WKi6qbqors6u3cebhPeNEzTZ-26xPq" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1EVWOtS1MA00S3KZzfhHoMVgdA6wO0CWU" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k88Qlot0orIk3YzhI3pWjkPsvK5c8P-z" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OXeuBqBvQmOweENHwIsBHoO2kG3rvS-m" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1l5WKi6qbqors6u3cebhPeNEzTZ-26xPq" target="_blank" rel="noopener">1080p</a>]</p>
<div style="text-align: center;"><b>Fairy Tail: Final Series - Episode 51 END</b></div>
<div style="text-align: center;"></div>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1ps5-1HP7MMDQ-2K2AtWJfM2u_Cgpiq39" target="_blank" rel="noopener">360p</a>] [<a href="http://drive.google.com/uc?id=1u0NYcDZdiy_bL7pEKmmZ7q2uUgmTrSW2" target="_blank" rel="noopener">480p</a>] [<a href="http://drive.google.com/uc?id=1XxygvFgL_OcKUFDHn_smPmM2ixV9LMNd" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VYza_gDe6uPKPw78SLmhAgAlFmeSfiGK" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1ps5-1HP7MMDQ-2K2AtWJfM2u_Cgpiq39" target="_blank" rel="noopener">360p</a>] [<a href="http://drive.google.com/uc?id=1u0NYcDZdiy_bL7pEKmmZ7q2uUgmTrSW2" target="_blank" rel="noopener">480p</a>] [<a href="http://drive.google.com/uc?id=1XxygvFgL_OcKUFDHn_smPmM2ixV9LMNd" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VYza_gDe6uPKPw78SLmhAgAlFmeSfiGK" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: left;">
</div>
<div style="text-align: left;"><b>DOWNLOAD BATCH:</b></div>
<div style="text-align: left;">=&gt; <a href="https://www.ciunime.com/2019/01/fairy-tail-episode-001-277-end-batch.html" target="_blank" rel="noopener">Fairy Tail</a></div>
<div style="text-align: left;"></div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
