---
layout: post
title: Fairy Tail Episode 001-277 END [Batch] Subtitle Indonesia
date: 2019-11-19 07:27:37.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '15593'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3301&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/01/fairy-tail-episode-001-277-end-batch.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '2834'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1653671098;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:26051;}i:1;a:1:{s:2:"id";i:26053;}i:2;a:1:{s:2:"id";i:26055;}}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/fairy-tail-episode-001-277-end-batch-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://2.bp.blogspot.com/-5IB76uHox1I/XDFq6KKA3kI/AAAAAAAAGVM/u91k8lDL8dEZ25TMwdooA3TzjUA-ttgIACLcBGAs/s1600/Fairy%2BTail.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/11/Fairy%2BTail.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul Alternatif :</b> Fairy Tail</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Adventure, Comedy, Fantasy, Magic, Shounen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 277 + OVA<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b><br />- 12 Oktober 2009 - 30 Maret 2013 [Eps 001-175] (Season 1)<br />- 5 April 2014 - 26 Maret 2016 [Eps 176-227] (Season 2)<br /><b>Studio Produksi : </b>Satelight, A-1 Pictures<br /><b>Durasi per Episode :&nbsp;</b>24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 8.04 (MyAnimeList)</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;">Berlatar di sebuah dunia fiksi, di mana terdapat Guild penyihir bernama “Fairy Tail”. Guild ini bertempat di kota Magnolia, yang berada di Kerajaan Fiore. Saat ini guild tersebut dipimpin oleh Makarov. Lucy Heartfilia, seorang gadis 17 tahun yang ingin menjadi penyihir. Dia memutuskan untuk bergabung dengan salah satu Guild penyihir paling terkenal, Fairy Tail. Suatu hari, secara kebetulan ia bertemu dengan Natsu Dragneel yang mabuk kendaraan. Saat bertemu dengannya, Lucy tidak tahu bahwa Natsu adalah penyihir anggota dari guild Fairy Tail.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download Batch :</b></div>
<div style="text-align: center;">
<div style="text-align: center;"><b>Fairy Tail - Episode 001-025</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1V_u_t-fKODnI9y-X3zozvCTvPGUg4kGJ" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VAqxWi7UHDBB1w9aiX8jnLtwOb2zLExC" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1QABVo0wUAQ83wNJnB4mHDyy8tlGYJ_0j" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1OwPXYwt7_XdXAYxpCOxzFK3AFOvoRjB6" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YPWaSOGC1XlSVOoVhEPUFMBR7svOIJO7" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-rzB6P2IUsqCdifXBrWUZNlLK4msitCu" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1Le3LJKymF4ImD2OhRzsBuTEjPkBz0U9f" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sZY42ziLVyeshmPmbHcpVC9ErjuRL2oj" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1t_ZF8qqaCVDyxcbYYOOWsUMKbrXd4yeK" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1BihvRA79dOeXylRVVpY-oSHgrcKciLcy" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nQyeOldk_Fdk-u3OWIFtqHpA3tSUHjYh" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JFJEhlTeqqJAegdmm8Xguu9jY-bhcbyG" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1rngrwj69JxoWRkZ4D8F57PSuVMj_PQdd" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1BtAUYU3mFVYpEfutQssxmiA1aDJKUB5g" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1J-pEsdUtaS6XQE67quXyw_uHLlssggd2" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1OO1ZVRdhM4o_Ni-7TvC-rdtZFRwM0Xhc" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MgvWw-hvmdRtxeQN5fIaropOaDPOi2KL" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14l6cvmevbfAY9RaXicLEL4RP0tqxSks1" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 026-050</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1ZHO_khhCQFOGzRLraIeXj617I8OmPlKJ" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1BP_wmNACqNbtBvo_2juvgCqkUapojvaH" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1evflL2irpgDFqKi8Eo6TRr9MQs5gN52g" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=11k3HwCF5U9ErVvxeuCMJr_vJ1nip2zMH" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1S9XEFG1X844T-n92_O78ZpDb5oRTnSo3" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rJP_PAy2NKgcSDbiNRMIKPe8TvO5qf9r" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1oarEy5mtT6-0uwsruBcjHBaAlorAqvae" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?id=1_94f3Rw1ny-QB8SGxrr41jZoNDgNmxjN&amp;export=download" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1YYc_rg_jPRUuEUQ7wiJVrSTCQhbGffFX" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1pK4cXSIeoXxW0YgYefaDR-5nlCqzOq3g" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WrQYSO88YvH1ZGFHk8opNMtrqVhOGG5L" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XEja3NYwL27o2_fS9_7BhdhV6Sz8D8OO" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=17siTXph224fc2jqGatNRokKZFd9zBZGk" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Qv8232IEmpISpB9EIFa5zcRuWgii14ib" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1rMeeNS34q_HcCNaKE2UwQ2bd3r-roExt" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1Oc3ko1m-NWy2jkyXPVAZlKLV8gc3HzVb" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HelDDGbqWqILbD129j6B1luY636QCbU5" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r-eFcF-tP-iPV_uLUt6JWUunNMr0p87e" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p></div>
<div style="text-align: center;"><b>Fairy Tail - Episode 051-075</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1QXlwL3auz6deJXuIzN_5eGcWBIxo02yC" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1l_ryn7bejlupzj178jRoekY22lF317kP" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1LTC4AUaQ-jv-46_Iyo0xMBlS6G7e2hKa" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1K1g-YNGnKfMqnxdbpJMklB1-umLaTQRE" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mahPMZmAQhje4Ytog1Etf-LjPRiVPmPD" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1driKMUE4x8F8GKxPsZzWscLnmDRaj6sk" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1BNd0n7N_O_h725BSwcY2y61H_2_tRF5N" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1V_IKBonPaDFvIUWVYNfNOmcM3SM8BZ4_" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ObiAVYOLmrdmlxzxb68iOFZt-Zb5_qwr" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=16ioh2Gw5j6LdBsfYk0OBzsJA-H_9T6Ki" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zi9OZbzV0e7oLrIg7r-sQIJbqq2pW11k" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CkifsejvKgK79qVM5y03HF8YivcfQKsI" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 076-100</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1q-vOMkWfLNjAWGYh6-sRgPnJ-kXkH3C-" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WoBygcuBdNA-5wm1BFMEVzh64aR66Ksv" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=1swd2l4VNq5FXR1o3EkNKngWd-4rP6UUD" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1PEd5GJvIP_rOupDdJmer6URo5mLhFXrw" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=10eZRLnbjlC0p6c-zs9hh89tK8lgILGC6" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oaRBwof4v_oeo0lOKB6g2G61vQYdTG_Q" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1vF0QHAuiDcBWK5QSm3GmtOVgUVlXEUlG" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qtgS3305gdGRTX0q96Ka5CsQ5OhYNNH-" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?id=14N2HUG_eLjhBMicklLbs87Itas78RKFI" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=18J_pTJt_uhUC7gekwzSb5zv6vycb2T2o" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1USvD_N9nG2W2or2hvwZDXANJJplieLWH" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1i-EFDXprx-VSSUJTAY4EVIsrXbQ4TXPj" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p></div>
<p><b>Fairy Tail - Episode 101-125</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1v7cfIJ4dFhN17GowBx4ngKuxBYgQtULq" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xc4MdizR72RBgP9oL7nVyEXP8U91B-tu" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PCrAgSIupV4mqcrfONzDTBcx2uSeF37W" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1MfeEE8tdWL8cg8ChOoqRkDCDNUZzt5Fe" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_crWrmeJTOlG6Hny4vOaVzAMPziA_-_b" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1c7pgeJcCnsDNfjbM16l63Wz5_Ut1nxtu" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1HzzRauyD9Z9Wjv7Xe8_QoLeTyqv_Q6mW" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ampuj9chSCMNhcGEN6VVLLZl0UHArOWr" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11QOAQFC_Krq3qbLDPEN6irVWz598NBVO" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1OPbtRtASQq73rsPp-bQXitWgxybI84yf" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wPRJo0Ezi_3-rvjaYXLkGia1l3HN0zRo" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zMQ-WIwdF_gvZUYxf3Pcs77BNCazEhGF" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 126-150</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1NNQOO5nf3ePO2NFnL_uqHJ4DJyrrUHUT" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_7E10JpVVfT4oJMcxyl8tiXZpmSwuEev" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xRdDkgJvcIvegtFYLEuJW9iB7XOUx6hR" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1ZTh4I9YWZa_ZcII40FtxX2KWj1moJqw0" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DMSBGC26KBP666j1T5ojpTKBkO6KRt7Y" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KIZWATZOhfgorwP9K-lehzRQF4aMRUVG" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=15tKblqbj5kCjsvA8BBRB1ZovWtsN_pz1" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12QDBFqSlN4ZfxxrGf0mUm-5Nzm71lHq-" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uoqXHEOPuqsuf75hyX2qt__kSI_EJa7y" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1gs30nyPASlWpC2xql8PLE1r0wLVn677i" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FYhxiy6bnjZOBkcqZXihKfG98vrmqAyH" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lCvGVN6EWHYcZ-dr_XvBKhC8g6i-DbWi" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 151-175</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1xak6OdVBw06EfPtGIvQnXyJRG-K8baSY" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1esDfqpdulWgZCke6K85VQYZdWE9uKcP_" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O1UF9YcQvvSYHy58BlSGonGsk6pBJd2X" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1wr4Pbw3MHtd1LKToPAS-Ru0gk9ujq8vJ" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=10dsyTM0WfBb-M319rlFhH7r-q_Hg9tqy" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r8dQN99uARnFajXgg3vMrGOO7Bl5FuC1" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1i2J17uhgZ4ZyzxqzJJyAMn5SowKf8J8L" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dZLwGnyCYbgoSkRm-WrS4ELt6RCQFt_K" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1G39gT0r-ZbNy6qNl7mFLoZkuAVs5TNrz" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1ZkQv1AeMUZeqlREqHaGIX6gActg7J8FY" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=165mpepOGOMq7y80MCoBUnB5s7WeFcyYy" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ugHyuwIaFxoFN6aJ1FHqSZYyybFD6neO" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1NxoepWgmkokTXVqifH3J6KLv9T0DAdE9" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1NieNK7QvhLpIDKHJpjD065I60BFcKT41" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f_h-Ts9Hnmk49211-Lo18-fD28M8874j" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1eFtUZImUiSNOddHCSjF9e8ZcVz6PQDwY" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rTJ51XIjXXfWKa66Xp9uFgPRMMICK3ah" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dOD_04B6YPLrV5GxNFBz2xrZpv4rYepB" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 176-200</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1pS1gLOSYJ_n6BPYzcJYuiGDMsJf--8fF" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1LTAK0c7Hg9JVdgsEllPmAZ5_EDcUIHN1" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fUmYYjZ4kOEBeeQkRU6WREBAJBJVlW4Q" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1Sz3tLEB7FuzN9T5fZYeXx-3QlpH6c1WI" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gNXrIl9FJDN_Si8zXwMItgG0RHfguZSl" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1NdKmOnjYq5pNrroH6J-ExTuBeAQPVaws" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1NTRledJPca-RsyjhAEn2zrwGsG5bQhBt" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ab9cA3FPvrgMpr43cRVHcHi6dz9RLXSH" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1L8eRAegxRhbfcNV9lfNJyaMxWjSipouI" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1fVv2h1AmvqenDB7SrD077_XZ9S2z_b-3" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iXv5sYTm2H01NMyakhI2avDrGfn9phOX" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ijIwE-HlgLWGNrAXHw2pm9mDQxnSSm27" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1rDpf38u7cN1Qy4B2FKvIAigp1RwajqEj" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ME8wYF6jrP1p4Xu3yEGzUtE8bunxT9XE" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XA1BL7Cj5PzweYumzfenqB9bTD60MX17" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1h4t8rNvA2bab3hgOQ55CUMAZ8zc7124b" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wCzYN5IZLqnvGBGns428BP34DsFB4nyi" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ZiTZUT2Euoc0BTNfeAuEuj6oNKp7UXQo" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 201-225</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1axQPUwRE-Jb9axhmNBzF2ns3WoYHclRV" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1F3nLk9VXP-00GkbKoRPaVttmHhfZ6vyG" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1BdpaHElnkuXWUzbDGS94CcWGwm1_T2Su" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1eYCRMPoOBg1jSXcn1jZR0WJi7OFCCVpn" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1w8F5MxgtSzrKnWvxhvEcKSb2arAfU3s_" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JA6k1qHtM_YW48NNiv1Vbo5XMVsg71HZ" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1SzLpqA41_CnJac9cb4WoDsajVzrTjJl4" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1c7NUq-LYgHHGdS_X5FVVi-dtU0EYrxrr" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fDiu393ByucbD9FY-sDSG5gM2S0GLu1y" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1xeo_FSSmS_HhROh9HBiPPSlGAC4jgJYZ" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mVf-e7hBYDFAJJk55aGX443JeD0cOpL9" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DBsqzgGopIaQw-drSd3BtewRux_OMNlh" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1SaBEHAG6xXNi76mWdVrX5H9syX31Z2a6" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HHb5KI85HzVNkxOqhoCuUyZ_2wxjSG_I" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nRDB2gWmxDI7CWKMoXd9CyWVrcx9v3OQ" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1_T-Qkf9DiEGzTd4yboe2y3_8TFA3Lr8q" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xDpB7-jAMCQRgwSgWdnpN9d1fndm5-Ls" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=157WTwga69Nd-_dTWg-qBzBtoQleMo25H" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 226-250</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=19LKJgjWJjuYU0H8cRQhO29QmgBNs_NZl" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RoWzl60gw6-7vhmN8r8CtxQtjfROGUEj" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uxtaLWU-nCbyj4nVGXREI-VQDv7wwQPj" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=10sXlyOrSdFEjIJKd7ITbkPXrpos0XhUC" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=134FzqSY1ZWeTViHqCJMjlBx37UEylL9C" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pSpdfnh0_a1NhUctKJsuNkNQ61aPZuQf" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1vrd8RMtUK3YqN-IMPtJ23tc3NmS7AJgS" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AZAyvGgxdXAa63_ejZ8rLZc6LPUNoazr" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HXdcu50m3QgljvvuoZrXO5Rwsw0cCZeX" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1fF9yIpcJp1S_lz5fyi89FSmlqon15KRg" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Y5KRcv-qOqKyrGFEUjFR3jPtRdZPVKDc" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mQ75MDm8sAPTSS-9f738FEluo6M1nYnl" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1WvzO1IbQUi3Kdogpb3m-lu8UiliA94F-" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12fVPjyus121CL2PTeDeB0bkuruaSQ-fI" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1exZtKHX3d2qZf4PsOa4WVmTq9v6K6vvR" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1o3bKuDdGBZ2ZkotD6wWG3PxJs_92jykF" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ENRUHLEPDILOhOjpIqmSyVIGbTcId0BV" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/$typettps://drive.google.com/open?id=1_09dOeSKxF1MAVuiK9H-5GVpG6LS0qL" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
<p><b>Fairy Tail - Episode 251-277 END</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=14nC6_aCyIXU6vi_z8udfZ9HOM1GLCmGD" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=166y1gOOs2MtwBNd8kuYcjPAn0ivqUoKx" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1cz55m9EnAkLjFW11LQz8yirEOErjx7pc" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1ruITcwI-c2hH-1IxLGUpE2Inx_N3SAUV" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CR0gmVaKg-O4seiUKPhcrYuj2a-r7vu-" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Gwv3PDGP56h8SLE3S7_Cmv8yQHBffakC" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1QTEONQt1su5Q-_4zNrMqNCdXUixsqDSg" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19EPl_tvEWenEBbaHejsOx5rUkwEnh6KX" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IoGa79X-Np97-05aeX-UqRBUmJ4vjVCH" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1qyAZUOuh25En1iE6gizsu8IPepqoObKK" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fMZp8zhhmX_wQJ1mlf9Ue_0HwH2gXApu" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XNS4hgDG1oynw6RUmeiEwDjdD7iDEB1I" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=11BzDoE_MmhB5p04m0y9N6gUtOcohPIlr" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1b4sQDnoLlENOgMe7LcdGqA3Zl7Ftr1n4" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16fdwjFJywmiYZuDp3J6B3tSKQMNkFR-e" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?id=1uq9k3L7FXcQehZgpAETKDdemrsprbHYk" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sc3bPwbmqssaga4nLIC2sJgURkY5GRw7" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1NCaTuxQ4ILjdaFq6owSumg6F6FCRW01I" target="_blank" rel="noopener">GDrive_6</a>]
<div style="text-align: left;"></div>
<div style="text-align: left;">
<div style="text-align: left;"><b>DOWNLOAD SEASON LAINNYA:</b></div>
<div style="text-align: left;"></div>
<div style="text-align: left;">=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/09/fairy-tail-final-series-episode-01-51.html" target="_blank" rel="noopener">Fairy Tail: Final Series</a></div>
<div style="text-align: left;"></div>
<div style="text-align: left;"></div>
</div>
<div style="text-align: left;"><b>DOWNLOAD MOVIE:</b></div>
<div style="text-align: left;"></div>
<div style="text-align: left;">=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/fairy-tail-movie-1-houou-no-miko-movie.html" target="_blank" rel="noopener">Fairy Tail Movie 1: Houou no Miko</a></div>
<div style="text-align: left;">=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/fairy-tail-movie-2-dragon-cry-movie.html" target="_blank" rel="noopener">Fairy Tail Movie 2: Dragon Cry</a></div>
<div style="text-align: left;"></div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
