---
layout: post
title: Kono Yo no Hate de Koi wo Utau Shoujo YU-NO Episode 01-26 END Subtitle Indonesia
date: 2019-10-03 10:49:07.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17342'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=2701&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/04/kono-yo-no-hate-de-koi-wo-utau-shoujo.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '3772'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1663212323;s:7:"payload";a:0:{}}}
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/kono-yo-no-hate-de-koi-wo-utau-shoujo-yu-no-episode-01-26-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://2.bp.blogspot.com/-hPO0UDxcmaE/XKV9SRvPCoI/AAAAAAAAL60/ikn9NTXq080h6xs3znqf7A90SGq0nVB2gCLcBGAs/s1600/Kono%2BYo%2Bno%2BHate%2Bde%2BKoi%2Bwo%2BUtau%2BShoujo%2BYU-NO.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2019/10/Kono%2BYo%2Bno%2BHate%2Bde%2BKoi%2Bwo%2BUtau%2BShoujo%2BYU-NO.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b> Alternatif</b> :</b> YU-NO: A girl who chants love at the bound of this world.</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Drama, Sci-Fi</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 26<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 2 April 2019 - 1 Oktober 2019<br /><b>Studio Produksi :</b> feel.<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 6.71 (MyAnimeList)</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Takuya Arima, seorang pelajar yang telah kehilangan ayahnya. Suatu hari, saat libur musim panas, Takuya menerima paket aneh dan sepucuk surat dari ayahnya. Surat tersebut berisi informasi mengenai keberadaan berbagai dunia paralel. Awalnya Takuya tidak menganggapnya serius, namun tak lama kemudian dia menyadari bahwa dirinya memiliki alat yang memungkinkannya untuk menjelajah ke dimensi lain.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO&nbsp; - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13Rv1rucziv2VmzWTC93SHyAdyB6Qr9di/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1Uye_LvYmOfTq4opDyYpUDTxNA8_7iiNE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Olik2uYPopYKtOX4E8AZ6b3kGiwQiksA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1cjiddkisEKYIGdRO9CXdXmgJO1FbWdo4/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1Q0F4IJ69j7uPPRhwe8abrwy2mHvKDwsH/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/15ZP8wKBU4Q0ifxsb0VDHknbbiRUcDz-_/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/172kAb8w-Q_Q_mGcb51uyoUOhi6Hrcq6e/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16xD8_0NGxrEZk_Yj5FbtYQSuv6DyvhtP/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1hcPcSANEfHFuDViNyY8BIQs5TSxqCUn5/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/12tNRubuJ1-ECyt6tFGDP_AggRAK7kR2a/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1CBnPdv2K47fDEjDFzJNn1GBlMU2mPJwr/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1nzdFHybNKvt8GHGEoF7d0YBziw47cyG3/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/171ErIqVUQm1FYagTXQY6kby2R3TUjssj/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1bvJyTKCv9q6ockEQY9t8u8jfwj2moqVx/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1EyQWrsLNlHzwr28QFFVSaZed4L94eoA5/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/19S3OftxOeIQeF-NZNP8YSxxi6FzZROta/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1VYIiQ1A-3BtT4xng0JfgvLfIIUNDRH-Z/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1pj502ec0UfnuVCRcj0oCga2ma9OBbAsC/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Ej_Gv25AZI_8st0uOLTrQxp_8Vbhj2FD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1LObpEiq1bs94ijNG0oBzAql_y1YiBNf_/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1u30i6SrOQ45AEcF0-v3Xe3dlcy3iWeGi/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1m8wzfLvpLpD9W4qy8nS3V462j0xsEOCA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1u6AjdqAV37En74cQ-_SHMzXk2lt1qOLC/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Ior8TMYd2LEz4fV_72J8yJ6tYN4Rh6a-/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Vo3fBfMeK9kWrMIfWOkTEFVklhpTxbi1/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1H8lAWXpG6ewPkCWAxhCYY32a7VPU1UR2/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1_W8LRiXEQn8agm0dgpwgNOulPfKZJKjV/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1gRq_rtcMi0nZlLlu3dYRL5LgZ8vj97Ew/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1eAFzVR-VWmAwU_DBkYahenl8_wN8XWsY/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1AGp1hI1aorTI9o0TOoujP-cB-m_R4TXl/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gY4_ALdKeawxw5g8PySGxr99tbt7PozQ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1LvTifSEoAh0seNTsXwugRttXt7ujN6xq/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1IWzUCjwVwGIzASXN_9ew2Vnkg_1wcCgd/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1zF1WQOesG2y7OjYVUk4_IgyC0ILljJe8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Z0Mw-AXvx9LPaP3JZJSkVxHZNxOB0qOk/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1qA61Zknmltwfe9ebecY474lPiMNwf1Ne/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SuEuSAiinbS4tbtxHlM9gS_srpsrBqg4/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1Z0EiVohMRx2JtNXJuhCfai83Fo8GIBmn/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1WxaHRq6AsG_Ch_rMa9Hws-GW_Xyobs6o/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RhY3onPX6K7xcyHOPy35xeOgicDWe_B9/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1TbjGcI-ATlpgDQnYUifV0ZSZj3JUikoV/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1XTYBge3rb2z8x-e0ZCkG7dRapOmZ-j9q/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1FqqXXx_NDECb_RjT3aOL-Dlrn2B9SOSt/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1s58vfLGxe8fhjFIF5itnlFDdvg0TMkPo/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1q1aMk9mIl5cwNfpMFYjamf5mBDiRvFbP/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1F-lQwp0XnfhH9PV7IIKaFTFhGOe4nJd-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rej7QdSNSaPfu-Fx5PD766p2MIBDlL3C/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1pMhqAKKo3-Q-NnFtxOXJ_Gp-9zBaw0Fz/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1vX2x8ayHvzko2jEdKyb1ys1qUZqJE9J7/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1sdGwNtF20RlbM6qmNMMXtTJuMSnsgC0P/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1d6J09e7Pop_tNRU2rAtqZZ7UugZGJ0zT/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1P5KN8ENIE93y29e5xoC39oeRab6aBzoT/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1rrz_K8l-sinNkvc5z5i9VGa8qUapFLXo/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1jF5eNgMi2wMZsVtzzie1rNk1MjXS7AsA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1VV-z_IArPoAlUFrd7yqcIu7xiRKk3hkn/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1eduCaF0EjPl1aNERyZWVeoOPUfrX_dg2/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1g7mqGwWdOdT6mdjnGZHzuZZwDoutI7tw/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1haOhmbVbKqWk_zueSUuZySQrWfqoaKum/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hvpNgORQpx7b4-np89wWziRgfU0agF3T/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10RQN4lvBD280x_cmufm42eMv-NyVeN6-/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/126kbLUwYb2MRmH-bVFDl7Sq6VZBtACn0/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1vAfyg0yF5zR_fk3OhlJScw865hPM_qL9/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1_WoTTi5-Foi6-rX30RT2avfW_40f8ANX/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/18hTb474hbQ1fwtUj9hJzi-PzM1gIjXEC/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1rwb5tTe3rI2jBzj3yRu407LUYYxvjUgJ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/19i5oJvZG_tdoEc-8thTNYhd0nz9xgoaQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ARWNYNvpNcCJLXD9VYUMdSvsQjaki03k/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RfNOEUmOFjIF9ThsXbWWiNz_zIF3Jp1c/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tP6TcKRfWvjDDt6vOx1v8Vl_46LBV9RJ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1D3d2-PpL9uhCNzX11ANtJeOkMf4L1zyS/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1OKMSe0yrYxX1s2comrKXS7E2NYA7Kxpm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TF8q1ByQ0r3-CGc2h4pUvchgSu7r3YSl/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/167_kC3jhaMhcvVX2bFMphfeIS-Nuzx9M/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/12Kwyiz8FVHSP6PT5BhP2WKTxlPfTYG1m/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1pkSiRBE0TLY2DRH1uVwPb7SW749OTba1/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1VI7fFcYqLfmLIxFIYb3kIQbuNOBVr4yb/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1lx8RCsvBGrofBS6Z2K5J8LK063KvV_Yr/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1pRvejiaUUtv2M0QdFdISgBt5aXYp8kCb/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/16TtVEpdLSxNEGG7cmesPmbWADEBNO4bM/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mv80kbVnUADDI1NKEB6kdNOscIwPcIiH/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1bPLk_PsqF4AEeRKfxptgMQ1gdvq8Wckx/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1RACzwyfhpu6Bwx6TsTEdUTQOvOSUDI6x/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1eLro8ykPA9cUbin602nR-0rvQmGTKHvM/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1-MUGJd4FEra0C1osu2zwaLs3ERZQQRlF/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1KM9m4c1zSHiprBEsBRSTMSN2XmO_HoZh/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1JiiNUn3hdnleDhhW3SMvny3apO4vfGqY/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1P9NXXIvlfkP2tXQ776f26DFeVDc23zoJ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1sGM-HwCQvle29MMcTv0LO2iN7jnpNrMi/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 12</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/134E6OgsE6WWU2pQ0nrRviS1s8px7WjqT/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1nfkfDaOYhmwrftuZRYxkEJNNRdNGkpQg/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15WxCwR_TF6tD-1Ziz7Qbp_uZ3TXV8cFR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1KzA4a7BJx2ib7JJYpCJr1DH694vmLThI/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1qAipveAdnLjEWyomzi8dYxjY-pNO1qm9/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1pkRahY0Po_9110vKX3NKdPqGknuz3PgW/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qwPmAiy1xZTKSbeDuKH0ZiFVXcPCkjNv/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1_c-DmZ4ozr16yWy8JS5Z44nKWC_Lt9QN/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 13</b></p>
<div style="text-align: center;">
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1DYrD-d7omQ81s2qwxx2vEXJtLSNjvfAM/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1D_w522VrimWdUVxO-k7NL-eRjkgCrun1/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1MRycnw0JBcGHEgQqPhmjdean_fnxp4rk/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GLkOFGZBjTX2TQBLRGYPaHhs-GwC8TcS/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1FaeG4hYLiGqeckLziYk0ELep_H9jhmSN/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ks9xPzcx6s78d--ZYYWL-DmYobk0mler/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qScJlAAeFh_FyLazSXl4k6q1mMg9mHoD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ayHH9_9Dj6RmDF69LI-8Mj57dmlri_sH/view" target="_blank" rel="noopener">720p</a>]</div>
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 14</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1qlYgESYEWKmgW_4N39FOPx1hvjoCR1UE/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ybU-3Fv70tgSg_AYkI5rtqBPRvNFRZu8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11wjjMurCDUB_HK6RIddXITrJsa2LOVEX/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1HeoEs2888cKnRlCbYJX6HuMMzLryv-Oe/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1v8hp1XbVqbnQdRph0kqMnCepmP9BQPGt/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1zNUATKty7hLY007jBQslmp8M386kYvJH/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1V53BH6CWHjJ5NMMn92hhGwWs5LSnmhlJ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1bPeoKbh-j79x9T_iFWieR6LSlUbn8his/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 15</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1PPqj_qhG-bIa2Hb1Dj9evvOwot0Q7FDR/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1kDRU9H4jmgh4GDsuq1K7uMzHDEiPmHLW/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1FLSawvcfEhvxrR4swS15--4exxbP4lM4/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Oo_N6E70lgc3qa5QieGlCPw61PDHvNJX/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1TcRsNcaxxxo1dLRVU_x7vLPpZLSG5NEi/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1p04I6BhH4Ii3NyOzIsdbIUmxQu6frXE6/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rEc3398u1als7fX4JImbZ-RqubmC7pj5/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1dhTlFxWXvMG5K4NwmVkaUmACDGx9NTGd/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 16</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1kyJkrbeQ1Een830gMyzr5EFT_jCvK1g5/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1E2zMv_kzBYHf8YqX7IhrJ0hfpzRMxnB1/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1KbgVWWfmNRlB_d9nnCnJkmZpCmw2cuEw/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NW5Y8azwbvW9oOTrJLw4Dpff_k618gPk/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1nPA6OMItls5yGN4sXp-EBYU8KUUuZaE4/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1iCjxHldI_9uUwAKqrtG7CaQdcfCmR0bz/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1l9NEO0TAKANcu3f1HlxeKMS6hGKviA8W/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1dhAZCv0xiH2v70IX5wxTTfRR1ZEs20_K/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 17</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/169Ok299VTs5b3e8d6qjESqap6yUR-fOz/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1DX2mgmFfyga_5jRkINgzQqgqR2kJDer7/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1I-l2XH7qAxOiScbNUITATpi8GtM-kbL-/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1YkghVpjsf_d2eeVGu2I5as0DgUG7-JHc/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/18onbDl4gXE-Wd8hrhjyRxTJmtiYQE6Z8/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1qArjjmFCuvL0bN1tSWHnnTKFPeCSeLQA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1jzcrunoF-ThCOtLTJvhFQGawoFByhmW2/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1o1cqvuLZo6Z5oT5BFBcJt-x2Mz7Rh6UK/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 18</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1sJSZ29rXmL6lQCSXrEhesvHN5SLEc8j5/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1F-bpv9sH8CtZ2S_aibpqlETEtwDNqRfr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1wNQfuwishFamva6k8cTxKN5KjyHK8wQD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GcI5ogeb1Uy4hLMKwv6dJKSaZgwZgocb/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tGOfcBEkFAyJtHpt5n-7N-nvWHD8i9PS/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1RSo0A5KnuRQshJj2Psxuog3YbOV6wJA9/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1zH1dAKaGgYn0KG6rzodr93EJm6wb5-ZR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NAuyzP23yc1BYNfYQ6pHg8aCuJI7acZO/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 19</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1AGMEUZqHbPvNDSesYOr75kDgE3sFwTjC/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1fkC78ol-JjbLChVf3e14XHV2wRUeGnzU/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1V5U2E5MOThoOMIU8gc-KlYUNhOld2C4W/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/175STUN6xTQUftNlQc6GMHoHeJkFOthnk/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1IyOWul1n-kNuwhUbxPYGERR3fYydhT0c/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1o2mPRVxhSspuwbnYCkcRF93XK779lcFE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1YNF24cYW-Y7VO0PLsv1FA93al9PXq4E3/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1fFuRBjNsGslHXFaMVT7yshQghH2w8bcC/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 20</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1fabVPNJbZDf2sTgC_pgC1gvK-aYzOuAm/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1B6vB9Zff0d2tX4szAyuUAMGkVOO4ryzD/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1K1MWoYeuTqiuU1rqqXQ696BvPPHA2o_d/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Sf9kngANNGgt5HTJrA-ZQ345CyesSHL4/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1l6vIKWcWsaJaYUCjDy0akCXMmpfgLYip/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1Gmq19bLQ1a3vgpQYNL2hu2QYp7L_rn2H/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1r4TfZvZTB6IRR9oOV_8yDZFgykNrhK-W/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1xcpjCM6KAglNdakYOdQmkN6OEFBMDc2v/view" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 21</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=18v168pnVEWI08ZmkOt0NVUz6C-tRK9rd" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Golj9g60VbJtu6ndNFAGUfe-WdsV3nsp" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dBAjOxyeLb1peT-cOh4vYweJbQKW3wyk" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Aso80B84zt93rb1gGZzzaDfi5L_So8pI" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ICMBbR-Drqk_gRnlmzVg6g2xAjrcYuch" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f9Q8nG0-pDOgLu8aFQLgWlPyJ7Snb6sF" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vz-BgBLTMpDRsVOM5GLPFTJ-lQfTrROZ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YDNRmETzh4pY0aWkAGiAhj0Bfo4yBk_r" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 22</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Zl27J0y7sdlProUjKDyEDpNmVG4bK-Yo" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-xZ1AJkrGl93LNbVdESNgOXUIYpoO6hK" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FeWGFv65dtQ-V_2gX6GxH0VzHzcRX_0P" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SX7wzlA6ofgMVNMEGdZXYytae9X-koAd" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Zl27J0y7sdlProUjKDyEDpNmVG4bK-Yo" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-xZ1AJkrGl93LNbVdESNgOXUIYpoO6hK" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FeWGFv65dtQ-V_2gX6GxH0VzHzcRX_0P" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SX7wzlA6ofgMVNMEGdZXYytae9X-koAd" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 23</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1w9xJFMgngm4Ul1IoVdC5Wqi_fA4X5LZx" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TGrn61RBeMg38egNGVbDcUghkBt4bVbs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wxmqTyzgxkbJzcize4wf_7gAZ39vSRuU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zeTJc9eOwPRJSuaDzVw0DiaB6LDQWHge" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1w9xJFMgngm4Ul1IoVdC5Wqi_fA4X5LZx" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TGrn61RBeMg38egNGVbDcUghkBt4bVbs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wxmqTyzgxkbJzcize4wf_7gAZ39vSRuU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zeTJc9eOwPRJSuaDzVw0DiaB6LDQWHge" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 24</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=18m4mjKm-zqTF_gbpDooQds1TKUQ69Qso" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ryQSn6t6IIctt8UPLf2J3f5iUH0yHZqg" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16XdPQuJZUF0bFVwUnorUGNGpEvwPlLSL" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1EJLwX570cv1IkayLJy_nllWFKmV5MAHD" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=18m4mjKm-zqTF_gbpDooQds1TKUQ69Qso" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ryQSn6t6IIctt8UPLf2J3f5iUH0yHZqg" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16XdPQuJZUF0bFVwUnorUGNGpEvwPlLSL" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1EJLwX570cv1IkayLJy_nllWFKmV5MAHD" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 25</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1qwmMEzpWKc4YbAXxzt4M5YNqwHERYTgP" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zln-RslM8q3fs46f5k-qRFzsAcSP4U-A" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ddooxppkicpKgA1Y2KXl47BaWZkS_XMt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RO8XoGtTZ2Pff_XlJ0fh8K2XhadbqbWm" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1qwmMEzpWKc4YbAXxzt4M5YNqwHERYTgP" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zln-RslM8q3fs46f5k-qRFzsAcSP4U-A" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ddooxppkicpKgA1Y2KXl47BaWZkS_XMt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RO8XoGtTZ2Pff_XlJ0fh8K2XhadbqbWm" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Kono Yo no Hate de Koi wo Utau Shoujo YU-NO - Episode 26 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1QkbtbhyK3jV08rbmuRZ2tWn7PQ2OQz9Q" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TQtDT7nGPMxDZUoNMpZz554UBSex2mcR" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Yb7l3cRhPQDIDvVT9mgoMiGHyZt0_Nxn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ByZbO-OXUu0srW6bpMFDaFrs1_vygmNx" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1QkbtbhyK3jV08rbmuRZ2tWn7PQ2OQz9Q" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TQtDT7nGPMxDZUoNMpZz554UBSex2mcR" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Yb7l3cRhPQDIDvVT9mgoMiGHyZt0_Nxn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ByZbO-OXUu0srW6bpMFDaFrs1_vygmNx" target="_blank" rel="noopener">720p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
