---
layout: post
title: Hachi-nan tte, Sore wa Nai deshou! Episode 01-12 END Subtitle Indonesia
date: 2020-06-23 09:48:54.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '14115'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=451&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/04/hachi-nan-tte-sore-wa-nai-deshou.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '986'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1645012476;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/hachi-nan-tte-sore-wa-nai-deshou-episode-01-12-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-id2UaPCmqb0/XoS6Mb4wCUI/AAAAAAAAd_U/6-HWNxGYzlQyCQabq15nNEzVSxp-vUvEACLcBGAsYHQ/s1600/Hachi-nan%2Btte%252C%2BSore%2Bwa%2BNai%2Bdeshou%2521.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/06/Hachi-nan%2Btte%252C%2BSore%2Bwa%2BNai%2Bdeshou%2521.png" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;Hachinan tte, Sore wa Nai deshou!, The 8th son? Are you kidding me?</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Fantasy</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;12<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;2 April 2020&nbsp;- 18 Juni 2020<br /><b>Studio Produksi :</b>&nbsp;SynergySP, Shin-Ei Animation<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;6.23&nbsp;(MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Shingo Ichinomiya adalah seorang pria berusia 25 tahun yang bekerja di sebuah perusahaan, Sambil memikirkan hari kerjanya yang sibuk, dia tertidur. Namun, ketika dia bangun, dia berada di sebuah ruangan yang tidak dikenalnya dan menyadari bahwa dia berada di dalam tubuh anak berusia lima tahun. Namanya adalah Wendelin Von Benno Baumeister, anak bungsu dari bangsawan yang tinggal di tempat terpencil. Anak itu memiliki bakat sihir yang sangat langka di dunia itu. Ini adalah kisah dari anak lelaki yang membuka jalannya sendiri di dunia keras.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1q4TL3-hgFFSUq7b9O8-UvRtRc4Rnz8ps" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zi4H17ZvzjVFDB-y1nhWSJcbgKGOuoaj" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1swLOpnDBqYMpur2IBL9A31--q8eGYlfV" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fEUGeuOfNIN6A8paSfgvbICZHKyOvSoF" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www22.zippyshare.com/v/q6K2Snz3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www87.zippyshare.com/v/7IZuTfkT/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www117.zippyshare.com/v/rCNAxhHr/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www19.zippyshare.com/v/Hv0oqM30/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1yvMx6k9lkLr7cL2h7ONzOmd4NeGKWZi4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Xfz_DuKFF-RI_ici9eEaGZ05HRjWqeJJ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rp9QlmQOIyv7vrj7GjzBz_1QwotLTdkh" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1q_MhFfQHlcYQdnOk4_Jvz0aRmTbmRL29" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www120.zippyshare.com/v/Kcda0u24/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www117.zippyshare.com/v/mSFnW6pf/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www111.zippyshare.com/v/cPZxgCZR/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www91.zippyshare.com/v/N6368bpG/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1GkuMS1Jy41g_LXry3Nejfa5bEd_1OLam" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vWv9gGHb08Ex9kzZ2uz5kbtz0G1SRRIH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pJ38uEM5N3Y3XIDaujnU4VU4VLqSsAZb" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mYmxYASN2lte-sxNZBgFvW6gjWmkMw9n" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www43.zippyshare.com/v/gLa7KWAG/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www75.zippyshare.com/v/BD9sb3Aa/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www112.zippyshare.com/v/ZbpARADl/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/BKS96vMO/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1gVPpL0Bj4lGKZGbjZQVucbY2PMewne1w" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1BXU2hKB0mS815zyhHlxjFg-0dWi3eELj" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1siEVQkgp39UP6fNc3TQV8G84sZf3xATM" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FBS_bGYMwJ91VFgaaR-Zmmm0dddNwkBh" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www10.zippyshare.com/v/b7I28sy5/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www13.zippyshare.com/v/juduVi1g/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www31.zippyshare.com/v/c5qN83Uj/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www47.zippyshare.com/v/qeME6Fkt/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1wliBENvntRzM-muDY8mBjVEKfxSinBh-" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QTBKT9ssmumXvJCPzHAzNY3G4HW7ofHZ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16DdWaYiJUuHLlYrtZ3bPruYSPujtXBdQ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KcZgqgaOp6UbpNPJ9yU3YTaBMW8ebNmf" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www97.zippyshare.com/v/zxyv31uk/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www30.zippyshare.com/v/3iowyAC9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www112.zippyshare.com/v/rRuaff0V/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www24.zippyshare.com/v/d3edNFUj/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1OjL77pNHYSeWESswsuKaVWEI9dup42Xq" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1NgHV6P8OmjKeE0soH8hEthDch2SZHFkd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13MRpmbYt9uGqdUqiKk3MDGRaHA8xhex-" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11iRIt3pdbLh6z5QNiEVV6f2UiPgUj2w_" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www117.zippyshare.com/v/LiNrW0oT/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www77.zippyshare.com/v/ZzqDlhBA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www62.zippyshare.com/v/zGgNlsbD/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www42.zippyshare.com/v/08dxNF6y/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=15VCtbA-tKLK9EJ768Tk_-u7w3c0C8Otn" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sK0xGKct9vmobO_oPiD4F7DHMK0i5-kL" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KZehXGtUrt_e6R1plBFE_OdwOhVWoxKK" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Hi8BDvNHJapnwlfPbgIOb24oULTAOWdg" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www14.zippyshare.com/v/yjBmp6F9/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www63.zippyshare.com/v/wZUKdlF9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www110.zippyshare.com/v/otq5FrVJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www44.zippyshare.com/v/XWorKd43/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1SgUoNzZbbhxz5v9x5J_DYI0_btNmoIot" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-rciEdVnFwZ1bcS9lg1ABKsTV9_gtobK" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Y3w1xymbJnXXH4sREz9HZZHXKpOL0PkA" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1d950YNgFVwfTL456KLpcRZBdo0iMBC4N" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www100.zippyshare.com/v/zSJpWHXs/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www10.zippyshare.com/v/DPU2QoCy/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www9.zippyshare.com/v/lvv3lyjj/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www91.zippyshare.com/v/C9sAljXZ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1v-Wwoe4157ajZVGh4CV9B5CQUFUC93jE" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1D_WY74GITog_VSEv4dMxTa8AZlKzkAGr" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ClPn-n5XovIflRQwbgYeQCyM_r0aVizj" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=118w8WY8nQbBbn4J3Zs9gz9kKbIeoRZ8s" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www17.zippyshare.com/v/yF0ljzkh/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www50.zippyshare.com/v/ZI6H0QBo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www86.zippyshare.com/v/cQO0kS2j/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www48.zippyshare.com/v/GQMJFo6r/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=10ES72oEzw6lFpfe8EE6eFsEwrj643YOj" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1n6MYjKhhFowfec8cyIOGKp2bGn6VK88L" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12-Q0o6EhTPyJt1XTmi3E0LjlXP7zR7T_" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MebUJBTBlmt_na5T1dA1rYHwqE0oXrxq" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www73.zippyshare.com/v/SdFB6Emh/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www62.zippyshare.com/v/preGiS7d/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www119.zippyshare.com/v/MpHSG9PJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www51.zippyshare.com/v/IDDZNS0i/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1wjQOMlTcbWIWNpwB4ujFH4okxnAFEWRK" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1pdeXyJ5jcUXKikXcbdJO3xKvaM961ECr" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1MkHSrJVGvJtu9N8q60C1qCLO4cAAlp4B" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1Bw_jGMn-iBezruGajXONoMzzR_anAeIm" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www65.zippyshare.com/v/xaJiMK6s/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www107.zippyshare.com/v/Dqc6j9bA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www45.zippyshare.com/v/WbbZXzUg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www95.zippyshare.com/v/ShEHmZmh/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Hachi-nan tte, Sore wa Nai deshou!&nbsp;- Episode 12 END</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=14Otoj4F1RQvhZpuiPbqmd5H3YWK-UMaP" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oTe85CrlXsHHaZLkPxWlTbFzebJLZLRO" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1v5XLfyBQVaqDH5RpIjKa8IS3rVS7t-xk" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www19.zippyshare.com/v/fVBDUmeO/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www35.zippyshare.com/v/8tvsD09h/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www55.zippyshare.com/v/nhuCdpyE/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www57.zippyshare.com/v/usQyFgm3/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
