---
layout: post
title: 'Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana Episode
  01-12 END Subtitle Indonesia'
date: 2020-04-09 16:29:38.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '20082'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=1351&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/10/keishichou-tokumubu-tokushu-kyouakuhan.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '1500'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1657399488;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:27164;}i:1;a:1:{s:2:"id";i:27152;}i:2;a:1:{s:2:"id";i:27154;}}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/keishichou-tokumubu-tokushu-kyouakuhan-taisakushitsu-dainanaka-tokunana-episode-01-12-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/--eoCospzcvU/XaFcDT3t9FI/AAAAAAAAdew/TZXrPB5a4X4AzKRS_yORLpz9D23qr72MwCLcBGAsYHQ/s1600/Keishichou%2BTokumubu%2BTokushu%2BKyouakuhan%2BTaisakushitsu%2BDainanaka%2B-%2BTokunana.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/04/Keishichou%2BTokumubu%2BTokushu%2BKyouakuhan%2BTaisakushitsu%2BDainanaka%2B-%2BTokunana.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;Special Crime Investigation Unit - Special 7</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Police</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;12<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;6 Oktober 2019 - 30 Desember 2019<br /><b>Studio Produksi :</b>&nbsp;Anima&amp;Co.<br /><b>Durasi per Episode :</b>&nbsp;23 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;6.69 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Dahulu kala naga merupakan penguasa dunia elf, kurcaci, vamir, homunculi, dan manusia. Di zaman ini semua naga telah menghilang, dan yang tersisa memilih untuk hidup bersama dengan penampilan menyerupai manusia. Tahun 2×19 di Tokyo yang damai, muncul kelompok “Sembilan” yang berupaya mendapatkan kekuatan naga dan mengacaukan dunia. Polisi membentuk Tokunana, unit investigasi kejahatan luar biasa yang terdiri dari berbagai ahli untuk melawan Sembilan. Tokunana beranggotakan para ahli yang memiliki kemampuan di atas rata-rata manusia.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1AhkaeEfG1QS4_bF3eaE6ZPdJ_YoFsFZt" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wrvF6_eNuc43mGA10A_veY2-RmNn3N7J" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yyHwBgjLhAUt7lbPz7R8xulDJh79uFqw" target="_blank" rel="noopener">720p</a>]&nbsp;[<a href="https://drive.google.com/uc?id=1H9Sp6CqKaOaqz8tw83f-0JMCkSKODpto" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www51.zippyshare.com/v/AmNrO4Ff/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www51.zippyshare.com/v/LtwWcuZK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www51.zippyshare.com/v/62Peo946/file.html" target="_blank" rel="noopener">720p</a>]&nbsp;[<a href="https://www67.zippyshare.com/v/2Qp91Fmw/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 02</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?id=1bqsmzGs8t_x24HyyJHWrJfc4KLVuRh5f" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1PVtFwejep2AnBtRPACQLzK8GJiZwJh4z" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1uAXFZju4-hlT-MColkHEfKq2TWIvtj6r" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1LaH5d8x0FUYyc8BXU3g_UfoRomUD7fxv" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www91.zippyshare.com/v/9pxhhp23/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www96.zippyshare.com/v/All0xMzJ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www98.zippyshare.com/v/7NVgOQ97/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www39.zippyshare.com/v/TUOBLc1D/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 03</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?id=1uJEFlMb28rPj0Bt0CahMNSGhxwBaNoSA" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=15uYX8T8GHqAigjXHR_RQowxEZSOEMd-_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1y_E4jmeQmlSRp6ME-NHV_uFJUbEzJYpg" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1NveZYW5ofdRBz0QkzZwmVW4-iiFlS_m3" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www65.zippyshare.com/v/H35OjGVB/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www66.zippyshare.com/v/ejhbcKtu/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www83.zippyshare.com/v/TngCSmG5/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www100.zippyshare.com/v/kMtQzdEp/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 04</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?id=1Hv_Mhz5tP3AwoH4aT07GJpZt9mTRv0YY" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1MeUBDDlH_KWcUC0PufI08krD-3qpAIW7" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1ypcQ_BiRxNNpsNF-Fq7BcZCoMU58Y58Y" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=17ozn7W340LN2s6p6BpPIOAYOXRixBsi5" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www47.zippyshare.com/v/0wi17YqV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www119.zippyshare.com/v/FXTG09n8/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www59.zippyshare.com/v/3QCnAqZo/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www95.zippyshare.com/v/rdSUszZp/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 05</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?id=1zLN8GcLxuQo19pRKBrN9H8xyPGbXfCG2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1KBcoZSz3nB-b0wH_e5eTsJPrivuBB2dU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1PPRmgJB9Z5zzHO8soJjhsotsWWkiXrgS" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1gGmDjHW7W4jNJd2nWz3BGuEq-qzdkyiQ" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www14.zippyshare.com/v/45w0HiuV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/LU4rz5kG/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www18.zippyshare.com/v/0ZW6Hw35/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www118.zippyshare.com/v/ieQ7zug1/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 06</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1nerHnDA8BYriRsUDrm5ZW1xdT6qjwruf" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1dP6D1QSvvJH_6049l02A2zILU9MIH2EF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=17Wudc7M-1PkHrz65zsEeucDntHbT1Yhe" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1aEbWU_Fw4kt2K4Uelew9NNev-QgljaGE" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www1.zippyshare.com/v/8Qvwx0ke/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www73.zippyshare.com/v/CunYZB6E/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www90.zippyshare.com/v/7WEO7uxt/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www13.zippyshare.com/v/UJabWB0v/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 07</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1_RSeaEYuLO0LEx_hEUGksHp-h35rV4Cl" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1WKNpkXSFaCRmbLwUzSR2c_BUxvdQ6PG_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1YIs7HzNHuAUbcEwHATq3dITlJjwiJPPA" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1m8Sm9hm4SciFzcH7lyWSqDSFAJWQ0nie" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www106.zippyshare.com/v/xqSotZ9j/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www106.zippyshare.com/v/n8Qi4dMo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www100.zippyshare.com/v/YrllLnjy/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www98.zippyshare.com/v/355P8CNi/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 08</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?id=1e1IxoL_01kHsUNi1ZwnDvH9Ni2oQKeiO" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15WipkwYrNUdd2aTAbjrRBZbLqbWyQmLV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_W_At7RX4Ozaym1AUZGl-76FIk7pEPYT" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1__WvcOukhcRKJAXGuo4eqqB5MObywGxI" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www69.zippyshare.com/v/RVYTr0O9/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www1.zippyshare.com/v/pUja0GND/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www76.zippyshare.com/v/RDPkRwZw/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www8.zippyshare.com/v/Lkvjpgut/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 09</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=13N7r8UOq3RZHBWG0X-i7kmjVyzCxlCnI" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1gE9h2ELEkt9tMlzK0GsXwcmdnqZJU3BI" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dMuGlU4edkxv5re5yWd1n5FLHMFX4M1c" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RHjDDEK7Ta_4jxaib-DpzHxOJsqBZ4iO" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www26.zippyshare.com/v/DjTlUQxR/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www82.zippyshare.com/v/ye8dcjAF/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/XOP6ttCT/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www110.zippyshare.com/v/L6OHQ0ZO/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 10</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1LgjbQHJEPfBO08wPXRw4ei_9dYOjVMpS" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17-Z9I4bP-tfMgAM-8g-9UfN27J3r_7TG" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Wi9zXfgxXwvk6WmaIHwL_PXaalRqOSka" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bXFiPRL7HWuleESoPuukK51HLYfjrqHa" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www118.zippyshare.com/v/yurPCWMO/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www99.zippyshare.com/v/1XVGTwEN/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www39.zippyshare.com/v/wMMiNtVc/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www18.zippyshare.com/v/7JAWcw4W/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 11</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1eAido-W2vYlkxRjedxSHNlBbNLk3Ps0t" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Tj-QIcd2OC0WSpfKiXPNqAj0rGshGldx" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YAOhy3RPpBfpzpP7TYgw2gDJHxkP5I5O" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1F39KWgcSNv0IVmfdxCVfkqDkpHbr_Irj" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www84.zippyshare.com/v/E8kHllmD/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www89.zippyshare.com/v/enu6p7mk/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www2.zippyshare.com/v/WpTimyj9/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www76.zippyshare.com/v/WKJkMo7c/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana&nbsp;- Episode 12 END</b></p>
<p>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ky7q2fatr5Ho9bc5ZxlNTICJCb-UdmdY" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1dqOpCgrcXeb9OtAYS0gbCVNVxVCpyFVH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1h7jUOslq5nvZXPyKsKCNt5OrVTGhy6lm" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1P4KjgS2PWkJQZXp89RAMxpJxpCllH_nT" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www59.zippyshare.com/v/Bf4gNcxI/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www92.zippyshare.com/v/KXQPMyJ7/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www69.zippyshare.com/v/nUepFb87/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www62.zippyshare.com/v/9rl132pj/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
