---
layout: post
title: Toaru Kagaku no Railgun Season 3 Episode 01-25 END Subtitle Indonesia
date: 2020-10-03 04:04:34.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '18124'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=301&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/01/toaru-kagaku-no-railgun-season-3.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '795'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1650041130;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/toaru-kagaku-no-railgun-season-3-episode-01-25-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-mTYqQZh-oHQ/Xhlv9zHFL9I/AAAAAAAAd1U/5CllyCgJSs0jkEopjM-sRWXU2YUtI6kxgCLcBGAsYHQ/s1600/Toaru%2BKagaku%2Bno%2BRailgun%2BSeason%2B3.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/10/Toaru%2BKagaku%2Bno%2BRailgun%2BSeason%2B3.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;Toaru Kagaku no Railgun T,&nbsp;A Certain Scientific Railgun T,&nbsp;Toaru Kagaku no Railgun 3, Toaru Kagaku no Choudenjihou 3, A Certain Scientific Railgun 3</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Sci-Fi, Super Power</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;25<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;10 Januari 2020&nbsp;- 25 Septemer 2020<br /><b>Studio Produksi :</b>&nbsp;J.C.Staff<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;8.33 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Musim ketiga dari serial anime Toaru Kagaku no Railgun. Kota Akademi adalah kota yang sangat maju dalam bidang teknologi dan 80% dari 2,3 juta penduduknya adalah pelajar. Fokus utama dalam studi di kota ini untuk mempelajari kekuatan esper. Misaka Mikoto adalah salah satu esper level atas yang tinggal di kota ini bersama teman sekamarnya, Shirai Kuroko yang juga esper level atas dan merupakan anggota dari Judgement. Judgement adalah badan penegak hukum yang anggotanya adalah para pelajar. Misaka dan Shirai adalah murid SMP Tokiwadai, sebuah sekolah swasta untuk esper level tinggi dan murid kaya. Bersama dengan dua teman lainnya, Uiharu Kazari dan Saten Ruiko, mereka berempat menjalani kehidupan di Kota Akademi yang penuh dengan petualangan menarik.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1xbbhEaboqQoagDscqNhwmFmQ1mfFKPyA" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1QcEPxY6-JO1l7KlPMpwrVcY1K246A2lv" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1brILqbFAzSQaSKAm0WvDGFZvjdU6C-Wy" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www67.zippyshare.com/v/EyqvMHEk/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www78.zippyshare.com/v/6WCSBs8f/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www76.zippyshare.com/v/37wDFily/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www57.zippyshare.com/v/vfuqAvIE/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1kqp6tmDMvxfYfqHSInt3JGCq3281HRQs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=18nxCa1WMlRc31y8VkkrDyztHvM-uGbhE" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1hGCn-K5YsuHc3gNgZXjDWQIaQbXaJP3R" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1s1L3-MaYynFArI2SVnVPPZRQx4H4sEuP" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www24.zippyshare.com/v/B6adQXmi/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www72.zippyshare.com/v/2C3lWSpp/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www36.zippyshare.com/v/qrK7FuPs/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www60.zippyshare.com/v/P3tmFPgw/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1qN6sT2PrW4OdR86t9U7ci7qMwbHzhZex" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=19EQweIb-ustnVBj58vU4ktt5-vW8q7zH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1I0vIS2IPKMQmMaFQs_EdMz8pxI2Ewj_g" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1GRPt0xoUFwbIHEwo3cE8jE_KrBtQ5mX-" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www19.zippyshare.com/v/ippFV2K0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www119.zippyshare.com/v/dbiOHsu3/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www63.zippyshare.com/v/8Lz0HKqh/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www64.zippyshare.com/v/2BEHzzjh/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1XConJwjN-tZ6CFsmf3CmkSQvJZiQlTUO" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1JZTfSsTbVATEzn0TYryTwEOJWdJzGimy" target="_blank" rel="noopener">480p</a>] [<a href="https://www.blogger.com/"><span id="goog_2077977681"></span>720p<span id="goog_2077977682"></span></a>] [<a href="https://drive.google.com/uc?id=1Xomq61Fvdgb0ixIjuGlgsCFIIc7O7Oru" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www47.zippyshare.com/v/xh2zDhOW/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www52.zippyshare.com/v/5jyrI9Xs/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www13.zippyshare.com/v/Vdvt1G5j/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www62.zippyshare.com/v/Be5hdShQ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=19dqcsSV4QJfvgaFBZ7i4VRWqAdzdJ_lM" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16xrbqXs6CxHDf2zQuCNfJDveaU3mgyqh" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1EOlCMDs3VQtR0A1wmLKxPi1HOmbnuKJ6" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VExnnZ5VIXJfbT5AycXMTizPt7jyjFez" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www86.zippyshare.com/v/YJgAs5Qr/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www101.zippyshare.com/v/NAdeQTTA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www70.zippyshare.com/v/uzVKAWpV/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www18.zippyshare.com/v/0gL4CILR/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1-PTowyeXF6634dEN3RQAMtYjRpua1srl" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nyemrlIHEMI_1cySSTPb1AIERubKXw5g" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1XZRckQBxkQLg3KGlRCrC4s5INYEVa6aD" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oJgvlPGmTgybr0y6Svx9IBJWnPaqwUwm" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www38.zippyshare.com/v/0ZYmw94d/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www39.zippyshare.com/v/Y7SnIe9O/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www25.zippyshare.com/v/t1Wd5vhe/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www83.zippyshare.com/v/xMfdRh0X/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1anN1YnHr85fxfiSPtry8JWEX_t24gypj" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tWBnSuwLdHXtl1gWYsvjF7_dTWE1mqfJ" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1rZJ51cYQvu8A42rVLsDjAvF-3bEqjtwY" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Uxnvrxt27-WgVzBzvEFM4_LAAX2I1U_X" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www29.zippyshare.com/v/OfT9Lfq8/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www55.zippyshare.com/v/K80Uqmzb/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www20.zippyshare.com/v/erBzPY9V/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www98.zippyshare.com/v/3xSQ0XGR/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1a-MNfyVUGT1wKUXu3OUy97R1cTwsetfp" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Y_D64TS_nROHXZ3HOyBOFSATQmrfBbX5" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1ft4tIPXi7eVFRJOvyffNKaxRZGcCa6zS" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1i2bH4x-xYHQS3FMDwxDuWvv0NZxmIegs" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www80.zippyshare.com/v/exrwLf8K/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www9.zippyshare.com/v/GyAqXS0v/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www54.zippyshare.com/v/k3Cw2NQD/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www111.zippyshare.com/v/N2Q9hfoN/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1bXRs8E-k5PFZKNN78pZvisWNCZAI8lSM" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12fpfc_qSVgs51hj7BZy8KKVLG3WvIzWL" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1S16whbogULEBq5zClIC5BQ4vP7BuCmJA" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1azVyLqjaw84d_mN3nWY85pU7VAlisf7y" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www119.zippyshare.com/v/Dw3rMfi3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/qnYIvZiU/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www28.zippyshare.com/v/D0Fq5WYB/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www16.zippyshare.com/v/g4hNfqhv/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1fRV2rU1V8Xv67r2uRlz10tJCwkNjUEOw" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1Bc16qEFQqA9Q7jkZlVMQbrlp9qrgQ_MD" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=19YNj4dlgnoxWFfaAdDikGKvTfOgFAtNS" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www82.zippyshare.com/v/ofkW3gA3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www59.zippyshare.com/v/rgo9ECG5/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www99.zippyshare.com/v/10iTQLev/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www95.zippyshare.com/v/UkFrfRJP/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=16YibMDV9Ei_MgL6l4EvUjacjxwRuI9HC" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-2iqV50AtNouOGRlcuNnPw_WF-SSiudA" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1-_1azMXOrNzDTExPvJRsquXU8I4FYX-G" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=16ccQqSJ_LC2z_xeisHrN42A3-i2JqskJ" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www24.zippyshare.com/v/PjGZEquB/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www50.zippyshare.com/v/i7V7SvSj/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www45.zippyshare.com/v/YJhZjHAz/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www49.zippyshare.com/v/7JGMb7br/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 12</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1gDm-tcHna5inEUys8dBHZkK2a4sRniXm" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HyL8RNrKFsolqEvOR2D3ic_SzkzShHPZ" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1npAxM1O0KqJGIr2r71FdqxWOelKwuK9-" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1GXuDGdp1MLxZA-9EPk1Higy3bESsFBeA" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www94.zippyshare.com/v/Tsus9wIu/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www49.zippyshare.com/v/yV11r0NK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www73.zippyshare.com/v/pDZ3n6E4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www54.zippyshare.com/v/Dsah2cAK/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 13</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1nCv80uMDupVKwgTAFxRmDpweH7zTVny8" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VTDio2qg0etji1CKRRT6_VIO2IOeHuXC" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1xTpZBENcFKIW29x0UgMZ4keRyO0z77Ga" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1On7pQbXkzIBEv4P6c2ZQVPifd3hXSYlz" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www98.zippyshare.com/v/cJ0TBJ2b/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www28.zippyshare.com/v/n05SQv7R/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www34.zippyshare.com/v/25BrAOxQ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www72.zippyshare.com/v/Fe0BRyNs/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 14</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1xOgsrTVnGt0U_fjs0ekRizFjF8c0LVQW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ljFo2dsnZCGiGvT6uAhZ2pNASNLipdQ4" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1YTVkT7cGRcjaH-93df2FUcQeOSsz_DWU" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1a2FSDkBHboC9Te_V_WprHWFApbPBLOlJ" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www82.zippyshare.com/v/HJf04iTX/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www99.zippyshare.com/v/8E08Qmyc/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www10.zippyshare.com/v/SYCuDY5f/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www28.zippyshare.com/v/XT12YvaK/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 15</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1Z9XV0-mSzjTVcsBcVO1eumVdlqvHFpDW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1egkVJ-ycIgWUNSjC2BLNnrERl66KNyUY" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?id=1Nt9sZ5Bj_Gk2W7VfRN_jTPBwXcBJ2enZ" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?id=1Z9XV0-mSzjTVcsBcVO1eumVdlqvHFpDW" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www106.zippyshare.com/v/qJKONOUJ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www4.zippyshare.com/v/6BWKE2P8/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www92.zippyshare.com/v/jJYgYAFJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www51.zippyshare.com/v/iv8g3DIe/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 16</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1S7d6VWxDnyJphuUkS4VVOM1wE3fpODrM" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15R_nR2M0tr20uy1qrgZAhrAiXo8Qaxkf" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1ToHXR7OdzLrqqeDgNpbF5V6Y6hUGhs5_" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mUEUwMV5Wq386PfEuozZZdNdm3bnxN2V" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www52.zippyshare.com/v/OTPpH6kn/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www23.zippyshare.com/v/kH6TsQbF/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www21.zippyshare.com/v/MW5mx6lr/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www84.zippyshare.com/v/4Vr10aho/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 17</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Y-HV2Ag_r6bcgpNlXu84Najk4pHzm4kW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14849RlxttwDXvg7NF2Yzp2NvoxNMfqyp" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1E7-QxJNom7tFGUmbxmceH3wHYX_j5RXi" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IXwvHmdKeeSByPysz9zOi3OeOb77VvmI" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www45.zippyshare.com/v/QTcxvPSA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www105.zippyshare.com/v/koYOePHi/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www27.zippyshare.com/v/5s2A1pE8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www19.zippyshare.com/v/DqyOrhBN/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 18</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1JiLwlWt1suOXr2wNh4QWYAloR5KQCHm5" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1T2cXyqT_Vmuff4LML4sTuhpwOMACOhs6" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1ebZ5mgEJ83bnfzPRupsbRcCUVp9AWzOn" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=16viTx0focOPBBZ6NqDNPJJ64-Unouegm" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www109.zippyshare.com/v/WNkhpH7Q/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www46.zippyshare.com/v/OX7S30n5/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www25.zippyshare.com/v/yApi6A41/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www88.zippyshare.com/v/kNAVX2z7/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 19</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1tv_a-Tg0_SsQKJSyas0wO2u2d_Fqwh1-" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CfXZ-s6hX8PqRlyJAC6u3UFI83nXOQ3R" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1U5_k0511zL5M753uA2FMK5BYZI8ASmhS" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XT-A9rpkzDCALT6_HFX4HLtOnIL4m5v5" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www79.zippyshare.com/v/aiLK5mRY/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www51.zippyshare.com/v/nxTSaqOM/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www116.zippyshare.com/v/ltDBsMu7/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www89.zippyshare.com/v/0amh334f/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 20</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1sym6V3InuSInar4tyhaVWfxZVl6n56Lb" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1GWAyLffAtEwDmHdB1UxYu7ksJbQVjUPX" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1ZUK3vg6i9_3-ppke4XsXWucnFbT3f7HU" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j5FieA2AXRC1-i0aRxdqdLPbQlJmhvKT" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www74.zippyshare.com/v/Vy9pk7pE/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www95.zippyshare.com/v/dHpQXsX8/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www108.zippyshare.com/v/DU3lJSYo/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www40.zippyshare.com/v/gEGQtNie/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 21</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1FngHgQ_hx_PIyIbbrlH-fdiHcdEsyFeU" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_ufSgBSmsecWVJj-qblVfMxOqqPkU5Y2" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1DwF-BJizM-k9ajub09FiW_eDnV4rMO3s" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1cVJRKCYYj2hMdq1hptyM196wEzK7-3ra" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www33.zippyshare.com/v/75MhvHr3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www59.zippyshare.com/v/CHDkAcnQ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www114.zippyshare.com/v/Jb1LZAUd/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www42.zippyshare.com/v/YuGS6H1I/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 22</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1T-ez80rrvDE_jMSzexxXrGPaOCZYGZgG" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1GsCEsswkPsXmcUd6DyX8DZcLnyMQrqZN" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1S-T9rMZlrFwQl20ZByn-sna3zHUSbODh" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=174f1oGBgYLFP2pvTaGf6lRB8CHxGpEO3" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www11.zippyshare.com/v/xsTi98jx/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www73.zippyshare.com/v/ZTGSl8P0/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www73.zippyshare.com/v/ZBvGUFE6/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www81.zippyshare.com/v/YS6xtWiM/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 23</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1OzG-DeiRbqs_EyE0Z9zZaMhN5cyFqeeW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R-rjG8UHUAXV-M6scCkWvKsbLPtypPwk" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1oFvfC2B3SUNu5PKswQSbfTv1qqkrDkAj" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QxcxXB1hXUaBbTcxldpd90HpRGIYRliB" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www24.zippyshare.com/v/7rFcPoXD/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www16.zippyshare.com/v/sJ00CIHC/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www20.zippyshare.com/v/GNzvhSQT/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www79.zippyshare.com/v/0eO3QLdQ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 24</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1YLs9mdyNy4f-oIEubVT6iuRu8JNjl5XL" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11ZNUXuPtPZGYTi7knEOcObLW3rUeD1i6" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1InG910CzOmd1qgxKK36hj5D9mUht4iCw" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tjmSkPP73M3X57oCDX0IcUQpX5TeTgYX" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www33.zippyshare.com/v/NLO5eXv5/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www24.zippyshare.com/v/JAOCSm2o/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www63.zippyshare.com/v/Y6EVQjE7/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www46.zippyshare.com/v/ddwCHDLb/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: center;"><b>Toaru Kagaku no Railgun Season 3&nbsp;- Episode 25 END</b></p>
<div>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1uK1bYMaGi6pwD0aGfm3Npzy7RXczMLID" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UwjibQNZc9FaAeDm7QK9TumHWd0z1rJg" target="_blank" rel="noopener">480p</a>] [<span id="goog_2077977681"></span><a href="https://drive.google.com/uc?export=download&amp;id=1AZ5eloxnmm_u-WjDwFvvefeMdMhT_UaM" target="_blank" rel="noopener">720p</a><span id="goog_2077977682"></span>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ULNxL4SfbUJXi0LXQamyrSnzZxgmTG8Q" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/viGgl9td/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www59.zippyshare.com/v/eEEPq7px/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www26.zippyshare.com/v/ATdc70lY/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www57.zippyshare.com/v/K1kLOPX0/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
