---
layout: post
title: Radiant Season 2 Episode 01-21 END Subtitle Indonesia
date: 2020-03-21 08:06:22.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '19776'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=1201&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/10/radiant-season-2-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '1933'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1663316497;s:7:"payload";a:0:{}}}
  kata_make_header_transparent: default
  litespeed_vpi_list: a:1:{i:0;s:57:"radiant-season-2-episode-01-21-end-subtitle-indonesia.png";}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/radiant-season-2-episode-01-21-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-U2OkZzXVKVM/XZTjgBZS0yI/AAAAAAAAdZs/XHGJhDTUXgk9e_1BDiLRlDtCbK_NyuffgCLcBGAsYHQ/s1600/Radiant%2BSeason%2B2.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/03/Radiant%2BSeason%2B2.png" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;Radiant 2nd Season</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Adventure, Fantasy, Magic</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;21<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;2 Oktober 2019 - 26 Februari 2020<br /><b>Studio Produksi :</b>&nbsp;Lerche<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;7.29 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Musim kedua dari anime&nbsp;Radiant.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Radiant Season 2&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ZeJrsuxJonHowkFGVdmgssRaudD7Spw1" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pL3umVltYhDtWxfVAkDrlpF2KHfUKA8Q" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uFVDJYYpAXMe-POL4OzFQPPetgJ8NiYz" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=165Info3WLNN2FLrdqD7PocKmqrrQI3bb" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www104.zippyshare.com/v/4nu28CoK/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www104.zippyshare.com/v/1vQ201wV/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www83.zippyshare.com/v/WkKqQggE/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www106.zippyshare.com/v/FOYYcuTb/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=14dQ2BhiOmREIHv0X7FqXflwV3kCUCdXB" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13B3Cr_GdFcwxA-ZoflZ3JXYvetc4PCnc" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FOlhkpd05Wojuzlql8YBkl49hapL4IT1" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=192TeivRUafiqOciiePuyzl6NAoKiXmEj" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www6.zippyshare.com/v/RTKP83Gj/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www6.zippyshare.com/v/7kCQXp3b/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www13.zippyshare.com/v/YowYZh4U/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www2.zippyshare.com/v/bGtHgCYt/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1j4PHqCrtPQ3Lm5blRd98IVhuUcPIFmLo" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1THvyysmYOlcTJyf0ESCO_eHE-vTD_gkb" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nIJHNo7EQYDLDWayPVHpo_X27mRsoyMo" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uEJwnrCbTJ6KhTjaq7vdO0ZABXxhoQsU" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www37.zippyshare.com/v/YEdCFMoA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www37.zippyshare.com/v/TaozGNjg/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www102.zippyshare.com/v/y1RktjJW/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www100.zippyshare.com/v/VGhwQcyJ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Db4PiMZBVEoU5JTXB4HlZGN53fyj0wT7" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VxxkICFG5pPUm7TPuGhC08YEFdjxuwEd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14s5YJRzX4Yqhy2yZqfXENOtuXSyFbAud" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Lh8VBuwJAQeFJezuPp8xI6NDs5M-qbou" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www99.zippyshare.com/v/WNZAWN1s/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www99.zippyshare.com/v/EcpJ01ma/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www34.zippyshare.com/v/7GTp1ZLQ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www36.zippyshare.com/v/FxAq1LT1/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=16np1FqA8hFncOTS_l2InTBP7gixRK1iV" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1ZAL3xZBkHigi0saWQ5iYApG53H5nAr4o" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1o0EiaOBz0K5NnWkGi3bcbwtYpx0IvdyB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1umGorADVF0r0t9ojFm4Gcg-IrIUUvmwC" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www32.zippyshare.com/v/VZSw3gGk/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www32.zippyshare.com/v/VgUy2SR9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www99.zippyshare.com/v/h8UUORNG/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www91.zippyshare.com/v/QNSu0n1d/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1OqQNNLHijkGio8e0Yz6g-GKiiIZv-4TE" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1D1xXiYwhIZuTCmVOyYtKjV-oo8_RoqCR" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1bHMOVt5_9vG3BXYlwtVEhgNl44lt5wH5" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1I5UTIamfmVRGdH06jMGOrNgD-V6NM1H2" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www53.zippyshare.com/v/IVt3UF4H/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www53.zippyshare.com/v/n8V1kHQa/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www63.zippyshare.com/v/y3WTTy3F/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www60.zippyshare.com/v/CXsWp0Px/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1qtI_mUDyw1WNtBc_KIaqpwm-alm0UPP5" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1huBC16MOKMMVd98eHtje2keOYVFJwHwV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1k4Q3ISlCjZRipJQjMu-VFv-YqxUCmedA" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1GDPmJbLRyyPAIQSLbSujAloxyRxvOFe_" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www4.zippyshare.com/v/y26CocXh/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www4.zippyshare.com/v/v7ycVgiW/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www57.zippyshare.com/v/HYYORw3M/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www18.zippyshare.com/v/oWILXA2I/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1xGf6GReHx7QzwNaTN5O1s3gi08wiRP7j" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1if69g-hiiscmlsO4oLI4ka9ioWeNb_XU" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1Bu4OvCTD2k95m4pE9zbFToDk9zv4iNC3" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1QFaeuIZONqUAbqpTcZ-_Y-INNCPuxz_B" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www9.zippyshare.com/v/77HBF7xD/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www9.zippyshare.com/v/05aKFrz1/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www73.zippyshare.com/v/3Z6Yn9af/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www22.zippyshare.com/v/g6xyhFxR/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1pG4cnKIMc9Dq1f1QgIpgn9MzNtnxikQf" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1KBaF4n3EldOMyzZb0lUmj-Nv3OFcwwlF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1U4SwNkRenHvwLNvSPoP-prAomXtHyy2a" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=18oxEn5tcZGuyNm19vOLK6FkIJdIDosVS" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www78.zippyshare.com/v/kO27IUNQ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www78.zippyshare.com/v/g3kxpaFg/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www7.zippyshare.com/v/I76TJHsx/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www25.zippyshare.com/v/OiEGcLoo/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ePBMxNDOft5XawVCjewFEZZAifZ-EqiP" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1NqFWxc0ly4Zaqz4aTnXXhqvsHwHATy30" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1-CbOHzWQOeDL5tyCfgYT1_Nz-XmS72TS" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1wRcLIijS1JXilzaHzprDpPqnNfpbQbHX" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www12.zippyshare.com/v/3s1kF65W/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/5ays4py0/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www41.zippyshare.com/v/v8HC7asg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www67.zippyshare.com/v/X8IfH5Wd/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1oVMEA2RDDcmYURw1E5Z9vL1VhQvvJjTd" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1L99wdLzGmiCLAJFFfVmFsR0vplJPf1Tp" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1VVuSpAD1P6SUgibtPmxXfL3jstKh6cQm" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1IGm8e5M2luznZvB_DII6JmOTxSnkbSJ7" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www99.zippyshare.com/v/vmAmurqC/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www99.zippyshare.com/v/oq3qVGNg/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www114.zippyshare.com/v/x9S2UGzI/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www28.zippyshare.com/v/Adgua2UV/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 12</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1zzz-EgUu1NIHmNukIV8RZW0zSp9fUIqr" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1qcjRVlJrv1_mNfgw6hQ4IawJpQQF6F-e" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=19n4SLSQhDTJlT0QYI7csWEyUnCuzA3bV" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1dNpqrrCxiBp22nxZfg966Xi6GSYpnVsp" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www80.zippyshare.com/v/kH1SjlVe/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www80.zippyshare.com/v/38fwt2An/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www40.zippyshare.com/v/Ix1N2Tuj/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www83.zippyshare.com/v/D71q4Yav/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 13</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mbBYBJULDFUW_81GxzHt9oRLVBpAmrS2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1vgUGm1DBh5YJZ27g9vmEb9HshfCYn7WW" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1qz8PNGw1A__ybPGkdpclHJ54rCPHZGyE" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=16hrHT_zwUUexqy4dC3FBBGnWuzQOybYC" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www53.zippyshare.com/v/urh8H1F9/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www53.zippyshare.com/v/p9MXZZ7G/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www111.zippyshare.com/v/2Ai3u6R4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www92.zippyshare.com/v/vAgIuPkG/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 14</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1EAVDUqcI4-4kZEfjsP8xEck_1IH7R1sM" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1fbv3yKNLQG25VM5mW_jug6AYfbuurx5M" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1Tt3wIZzilZbXtqcU49d7s0XfMvGXub05" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1zQ39_WCbIq32EXA7klrwdf8CLTuixkf2" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www59.zippyshare.com/v/Qhc01OfW/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www59.zippyshare.com/v/WyXFa5TO/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www76.zippyshare.com/v/DSRtai3i/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www116.zippyshare.com/v/wrHEJpty/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 15</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BPX_AgbObCDY4VDHZazBbeK_pVZajggW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1VqZTyMpzseiwgzuwZBbyM9AbXcDnHhcq" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=174qx2phaTKv2Bndm2-tDgqz_AROBkUvJ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1C5-NFFDZbBwz234NY5kD-NErEJk8E0TN" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www27.zippyshare.com/v/8MxRMCix/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www27.zippyshare.com/v/1FVkeP7D/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www98.zippyshare.com/v/9z2lLVY" target="_blank" rel="noopener">720p</a>] [<a href="https://www.blogger.com/"><span id="goog_1456143290"></span>1080p<span id="goog_1456143291"></span></a>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 16</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1b899Cerbx4bgc9O8ZeL6h5Qvb5_fDPzV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1VmJ6OMStrPYfB5F1k06fcxpx3mqKqdRt" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=19PxH0Ueft15u-iISIqD6N9pSkstFpXyg" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www63.zippyshare.com/v/ey4ncLPa/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www63.zippyshare.com/v/5BunF86D/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www112.zippyshare.com/v/mpNXYquu/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www51.zippyshare.com/v/cmbNq6RE/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 17</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1ZNbaTNl8EufzKkxU-tSW0EiUlTXYwjI2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1E6P20aQ0DnrOfX2jAFGyQ55LYPkM1n26" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1uKgk0SkVJoiQZ0TG5e7SBAC2maWRnGMh" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www28.zippyshare.com/v/atSeo4P4/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www28.zippyshare.com/v/UgZUTsSr/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www71.zippyshare.com/v/ddzuG4Uc/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www13.zippyshare.com/v/hpZDyX3m/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 18</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1_f5OThxAcSCFWsXsDiWa3aMvk_Xb2Dj4" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1uC82_VOJrQB_fC_h4Lejnrqna2uPOZ5U" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1yiYFtWLVqimfYJTUNqegOEBED-d2Ag1I" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www12.zippyshare.com/v/y0prBfcJ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/rlbr8g72/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www53.zippyshare.com/v/e0kjYWfK/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www73.zippyshare.com/v/0MYi8Rzs/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 19</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=18zT2iHTWlDR9i-J_mE3qzwudzZLxdpC1" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tx-ZhXSM81_W6WZuN8AV3-ZGnPCE3MWY" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1syFubppj1gj9wbgCWEhKzUDERgASeCa1" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www117.zippyshare.com/v/aaPfhI09/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www117.zippyshare.com/v/5sKsrrBF/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www54.zippyshare.com/v/u64gZmAQ/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www22.zippyshare.com/v/a7YoOziu/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 20</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1sNiUBBAYjucpywGBWA8oBkEAQVk_PRmA" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1im-8cwPAoSNXVgjnjFpEHxiUweuEzBol" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xnI_W4Lo87ZmFxPvQUD7RUPTVl9qSmhi" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www112.zippyshare.com/v/ejIDkZou/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www112.zippyshare.com/v/oc2PY3Q7/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www48.zippyshare.com/v/UCwS1EE4/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www23.zippyshare.com/v/1ZKx5yBe/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</p>
<p><b>Radiant Season 2&nbsp;- Episode 21 END</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1-xnvFtfSs5oSGTLaLqz_K0Y3NRlT_-La" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12pXr-hSo19RIWkryjP-QmmHap4w--V_n" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VFOEPVh-0Ko5Grgej5gbJIJrLQFYTP8U" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www97.zippyshare.com/v/emMqvMIR/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www97.zippyshare.com/v/zCo8ta4R/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www111.zippyshare.com/v/xHYV9ty8/file.html" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143290"></span><a href="https://www51.zippyshare.com/v/UaN8umkW/file.html" target="_blank" rel="noopener">1080p</a><span id="goog_1456143291"></span>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
