---
layout: post
title: Vinland Saga Episode 01-24 END Subtitle Indonesia
date: 2020-04-09 16:29:53.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '20084'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=1351&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/07/vinland-saga-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '1499'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1652036121;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/vinland-saga-episode-01-24-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-51_GSDIMp-g/XSL2FFCbMOI/AAAAAAAAbP8/LWEr0ZEnIcMwVDyict38xZLxeWdbm2D2wCLcBGAs/s1600/Vinland%2BSaga.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/04/Vinland%2BSaga.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> Vinland Saga</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Adventure, Drama, Historical, Seinen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 24<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 8 Juli 2019 - 30 Desember 2019<br /><b>Studio Produksi :</b> Wit Studio<br /><b>Durasi per Episode :</b> 25 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 8.57 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Selama seribu tahun, Viking telah menyebarkan nama dan reputasi mereka sebagai klan terkuat yang dipenuhi rasa haus akan kekerasan. Thorfinn adalah anak dari salah satu prajurit Viking hebat. Namun, ketika ayahnya terbunuh dalam pertempuran oleh pemimpin tentara bayaran Askeladd, ia bersumpah untuk membalas dendam. Thorfinn kemudian bergabung dengan Askeladd agar dapat menantangnya duel, tetapi akhirnya ia tertangkap di tengah-tengah peperangan.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Vinland Saga - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1402FGsQoSkL24XxfQFjYSs8X1r_WIG0L/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1H-NU44VqACOAnjxwh2UYj24lttL4U3bt/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/128FLq8Yb2Y7X2qQxqZJQpEnrB_72gKrc/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1TmcpgRKOVLHaf3KXHO84mkkrx2KeJhrR/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1cCIUfeAy9IYu-wVOFVPvN3a05Noc3Ft0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1X5NUfAWs6okK_ooeFbb6nTZPa8DbZoIi/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1nUsGesaP1QQlKLOXMNWHWRxs86jIc1fM/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1U9AzmF9WRJbqqpNb7JNGl-Lts0dWPVRQ/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 02</b></p>
<p>GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Efy2jyB9b1eEppnd2gm7p92PXXmGURo8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1JpPYcxpwj7BS2pZxu6XDSv6Nj9-W9TCK/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1DUVIw7uFCqFv_XcBst_TMyGOEMGDZqZg/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/11BbjBTerKohoImJvgxMbK3FOT3vawnPC/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1N2r_QnUSWa-pSdrlecG5SJqQ-xT-gDJT/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Tr7msMfsS5m3zCexAQUvEd3GspCkj3wS/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RWl4J4a5neBuyouB5UDkYqu7urHL4Po5/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1n_612AVXjg2AHxe5KU3ifpcSYJ7wjhMy/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1C5luggLmlvH5jQHURA9WU-MqYFLDugIi/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QM0s4f1GCw0ll_QXgMgOPkyQZlmjxquc/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1T-eHAjGp1JDthUoGOC2_pef7i8gOLX6u/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1PVdJwC2TIGZkmt3rmQU2Iz_Y-HLy4fPf/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1mrZzCRq4WCvtsaC_vaCiC-G-fqtA5kLQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1THB-wfvmxdJXxyXFngN77mDksVk5kBFT/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1gwgK0uQKd69oDz11tos7ILbRTNvPY_us/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1aLc25QzRX1jizO7GYrRQjrENC22fJp8j/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1KdQGpCl8_-LLdmRcVLDAkxlTX-tZbdX_/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1XJtimK6wlDodcYEZd0R9hHrwrJcgpQih/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ag8xsKkAlP1xiZ_PijyIratznssCPeUg/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/127aHUJgziINFPZGnyEd-UqgSsLdgiZIK/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vXGM3j6awI6UyJLOA0S5cilC6fWQUSZc/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rLC2Ajc0_yFgQBccBvh3XC5zShYEJsFL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1l6ForjQg3WFfukR211PM_4XySkb4XdGH/view" rel="noopener" target="_blank">720p</a>] [<a href="https://drive.google.com/file/d/1RQjx3fFIKxGMUFgljhUDbGGUlJ4UT9Xp/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Hx5zNuLHFt5ORGmmWsgsSabhW6f-KZ09/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1EpLGPBVwTUPt0qxuSsn-jrmoFrmht41h/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Pw_4cmvY6aO6KI8TF1q4mo6qFpMchv3j/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/14GHtl3k5aA8Gvo5lwm80kdiNJweAzDk6/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1j2-KR-1odFrgfKarOVWuRieqsK99U-9L/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1z_HExauvlgFVw3kegMpk-rKczkQfZC01/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1XzQZLaSxQriPKUiqOEqWTRvukWUQ5KXc/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1ieie0oI68TLcv9woxcxsWxZElTKX0SxA/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13bWqPJu5GbIvCRDMTBTSSC1qQdHotD2n/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1M7uEQXhI2FMCnVlJSXX2hEScp8C67s9x/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/13J2VljRWZDOdQNs48EgqlACI7wJTxN4N/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1_5MGRk5jQBjoo1a3Tf_kc5yaLH8URTVy/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SxA6UoFUsyrFgmBrpeBgJ-3Fbx8eSgLQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1yBfBpuUXIvMlyUbMyYZfyaSV-EXAc9dD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1FIVulYeBPc29IpKmCDTcQF6tK-XLpXMb/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1tBYwg-qlStOY3IgBztssnDHBItsqP4mW/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/15BrzE8Vo57bgCKYOXPIHZ_mMn3v_pos0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11qAn5dDBeOLAfpYMU4QOP0JboagNjqLi/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1IM6zlcyFnYwZQ6lzK7ERs67U3mezx50i/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1nEj9mgLTE2ud3RI-g6tJecUUi93dKgww/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1MJoZFzonu7ZLrYTtbugRt6uGhANnAQZ-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1xY1o25_Hz-5W-PhdX1VmXkcjSnGDCrK_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1qJBmxxidqILQSfEAJ5VZIstD0zI_yt0G/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1yHdCH-5cUV7dm17TCDmQjE1xf7WsKzpB/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1No0HfP39L7lKFH9nJAIKVYR7zppEihed" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1K6YoDL8qMqVKhtsMhbYp00auhzqB5YW9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1F5m6xXdtu5Hcs7W6MvheomO72CnFUpKo" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mEVTlo4wcUS0O7Eux0qiHcQCk5-Jb_qI" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1lzV0_CD-qn4KKzcq_e2DVl3laBdNUhPM" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sn2lBPvLoF6P-s1Jql_fLWyCuFTcWVna" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mCYJME6rMvLjxXVvTaQeVL0fLwHMiidL" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vDXKig_efgI3gKOqZvzpEy8TM7IutIMB" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1-2fYDp65e5VOxOCXmxWA3NEl79SKLi3W" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DZtx-KmZ_Rxf6NWURHIBWacnRMVFjI-1" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1afZ7bJ4dtF-T4SvBn0_SUfAdwQyMb2lM&amp;export=download" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DZtx-KmZ_Rxf6NWURHIBWacnRMVFjI-1" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1-2fYDp65e5VOxOCXmxWA3NEl79SKLi3W" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DZtx-KmZ_Rxf6NWURHIBWacnRMVFjI-1" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1afZ7bJ4dtF-T4SvBn0_SUfAdwQyMb2lM&amp;export=download" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DZtx-KmZ_Rxf6NWURHIBWacnRMVFjI-1" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Hqxg5nmFo48BxgU9ekDzver9xIiA6JPs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wbnv0VTZiGblY9-izlY9DdCIAZDmEoM0" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UxmqXa2bOUt3mbHH3I99otZ9RI1qGdHD" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18u_J71SF8iVVOPWVcq4p7VksN8AF-hHe" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Hqxg5nmFo48BxgU9ekDzver9xIiA6JPs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wbnv0VTZiGblY9-izlY9DdCIAZDmEoM0" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UxmqXa2bOUt3mbHH3I99otZ9RI1qGdHD" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18u_J71SF8iVVOPWVcq4p7VksN8AF-hHe" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1fBC2vPqeK_-I5c3ltU6xmJbWzLjFaLGn" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R5Dlz9zV3kkaVWlXKKwisvT5FKHyDoLv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13wz_-GqQWedY-6An-Bu13EPxMHuFJXo4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zoV3Dx4Ul6e2_6v6M23GkUuRF1ON72zh" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1fBC2vPqeK_-I5c3ltU6xmJbWzLjFaLGn" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R5Dlz9zV3kkaVWlXKKwisvT5FKHyDoLv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13wz_-GqQWedY-6An-Bu13EPxMHuFJXo4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zoV3Dx4Ul6e2_6v6M23GkUuRF1ON72zh" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 12</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Nh3ZcU6SWqk4x7tMa0TfW9LCXC8WPn5K" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I_-Hi1nNiHxhpfjsjrVBuYLtYtqDgwWK" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16dVW-NzeqLUNxfVm5VJbX0Vin5tnXSZQ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mZd5qVC5WApazfYtsZnRQ1uJDk5hz9Hd" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Nh3ZcU6SWqk4x7tMa0TfW9LCXC8WPn5K" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I_-Hi1nNiHxhpfjsjrVBuYLtYtqDgwWK" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16dVW-NzeqLUNxfVm5VJbX0Vin5tnXSZQ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mZd5qVC5WApazfYtsZnRQ1uJDk5hz9Hd" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 13</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1WB5eoNyXQYOnMGNMgLOfyNc1AiKiKjiJ" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qMCvMtFq2zavkfyKBe00plgHqYIq66RT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1OPHX9d5g271Aru3jizAUirU0ynnjkokG" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1MP0PmLjXV_WjT6PKocKM9vKimy5wbLe3" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1WB5eoNyXQYOnMGNMgLOfyNc1AiKiKjiJ" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qMCvMtFq2zavkfyKBe00plgHqYIq66RT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1OPHX9d5g271Aru3jizAUirU0ynnjkokG" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1MP0PmLjXV_WjT6PKocKM9vKimy5wbLe3" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 14</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mKmBOoJVY6NyeN2zAK7GmX12N23Uvd4x">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Yikl4MedYgHhMyo1Ocv6bjn_sEDNwVj_">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nIbFRhS855joVR3siT2U2LDkc4qE1_oN">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IWC-xqsABl_zYTUeruyNtkLCBCv5l9N6">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mKmBOoJVY6NyeN2zAK7GmX12N23Uvd4x">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Yikl4MedYgHhMyo1Ocv6bjn_sEDNwVj_">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nIbFRhS855joVR3siT2U2LDkc4qE1_oN">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IWC-xqsABl_zYTUeruyNtkLCBCv5l9N6">1080p</a>]</p>
<p><b>Vinland Saga - Episode 15</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1r3TvAOL8RO3hVkCKmnFe9onjbBcfIjwF" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=19LzO7DIGqBM6qI76rXBqPO2TQEIwHqlo" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=12uJ75I5NJJ_fFpBEFviDcMtsPHMGJEbf" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=133tlZu5noHnWG14rakrBkaO4r63JTFje" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://www62.zippyshare.com/v/GwCUVEPK/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www9.zippyshare.com/v/P432hbf3/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www96.zippyshare.com/v/mTVojbHW/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www10.zippyshare.com/v/5Ex36sAh/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 16</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=11pXmIGcS-SVEDkoKcufB5zRFC0o60aGK" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1djYCGYcNHMZcqQpuoFgFpHWLx8KXPBi3" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1d_N1BjyhfjAXb5uECqm4ttdT8-uD_AZc" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1Da2IhUrQzhm-NYjxUrM-uSsu4otro7DY" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=11pXmIGcS-SVEDkoKcufB5zRFC0o60aGK" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1djYCGYcNHMZcqQpuoFgFpHWLx8KXPBi3" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1d_N1BjyhfjAXb5uECqm4ttdT8-uD_AZc" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1Da2IhUrQzhm-NYjxUrM-uSsu4otro7DY" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 17</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=15NRLws1D0BLrml2ComtYa_R4cHkL5HFs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1fMvZOEFWzVBMEDrXq8BYyCZNOA4_Xmu-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1idupA3FJXIRcEEoimltE5O_hxTGkTuL2" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=16n0LFsXMEso1t4NUJhz-vUmjeOOe-DQA" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=15NRLws1D0BLrml2ComtYa_R4cHkL5HFs" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1fMvZOEFWzVBMEDrXq8BYyCZNOA4_Xmu-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1idupA3FJXIRcEEoimltE5O_hxTGkTuL2" target="_blank" rel="noopener">720p</a>] [<a href="https://www71.zippyshare.com/v/OIwbMvk7/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 18</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1x76l2sgRHMjYyMWZIWiwZFRwGER7CBtI" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=165HF84rZOf1Rib3ncYH8CEJ1JWeBZSFh" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1SfVj1g0HWH2lDPL4LBE8N6AaYJnOzkZf" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1Y3KQZuYUBsgxlH8okh4OR5XxvSQk7DYm" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1x76l2sgRHMjYyMWZIWiwZFRwGER7CBtI" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=165HF84rZOf1Rib3ncYH8CEJ1JWeBZSFh" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1SfVj1g0HWH2lDPL4LBE8N6AaYJnOzkZf" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1Y3KQZuYUBsgxlH8okh4OR5XxvSQk7DYm" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 19</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1zss2bfZQ7_k_-wHUk0qu64zs56aLQxDP" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1sy6ycAZrxcEemgb6bEA8DLogEXGzFFVs" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1f9nZGxTvM7o-svNWJQ6JdBfvOZ8gg6BB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1t0B7tDgnnigWBZSV_Keq2hot2J-YoRel" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1zss2bfZQ7_k_-wHUk0qu64zs56aLQxDP" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1sy6ycAZrxcEemgb6bEA8DLogEXGzFFVs" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1f9nZGxTvM7o-svNWJQ6JdBfvOZ8gg6BB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1t0B7tDgnnigWBZSV_Keq2hot2J-YoRel" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 20</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1sTMhYSPfT1uhfVGUeOSRP3YrEdVma3JV" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1vzwJR6kzRvTHh2Zg6ZjKzRMRb3llWAR4" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1eoYVy4Odow9_qFOPnCMWd0-zjve07CF4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1yEt92yshBLVpipECLvuoqHCG7g5lRFJC" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1sTMhYSPfT1uhfVGUeOSRP3YrEdVma3JV" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1vzwJR6kzRvTHh2Zg6ZjKzRMRb3llWAR4" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1eoYVy4Odow9_qFOPnCMWd0-zjve07CF4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1yEt92yshBLVpipECLvuoqHCG7g5lRFJC" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 21</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1cIqQ1_LCyVTyWqW2_apepxPQo-c85tGa" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1bEbZXd7Cn5uLKHs36lF3_OqfRg2i7vJa" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1k6HaMoiPj2DWOXT2sJXpKy08gzSKR2DX" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1BERgyT5buoEKd-VInLrd6wSrnqGRKKGq" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1cIqQ1_LCyVTyWqW2_apepxPQo-c85tGa" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1bEbZXd7Cn5uLKHs36lF3_OqfRg2i7vJa" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1k6HaMoiPj2DWOXT2sJXpKy08gzSKR2DX" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1BERgyT5buoEKd-VInLrd6wSrnqGRKKGq" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 22</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=17-lqYZkXbP0nrNZlRS9Em9BwFchzmC24" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rH8fsg1LDH5wjB6p6HaPnb_TZFugO69L" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JL8K8d2ZRV9J0AYX49VA1qXkm-6IYB1z" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uJDNQPiV7yEN_2mIMJvYGMDoPZTD7KOr" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=17-lqYZkXbP0nrNZlRS9Em9BwFchzmC24" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rH8fsg1LDH5wjB6p6HaPnb_TZFugO69L" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JL8K8d2ZRV9J0AYX49VA1qXkm-6IYB1z" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uJDNQPiV7yEN_2mIMJvYGMDoPZTD7KOr" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 23</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BOb_jGT2YrYR7XOWJidBPZyNI8a2aKm2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1EJeI670W0yrtvPSfCmLxbOZmHXG7ova2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HrXugz7g0JUacfLbZIoBFWuh9MzOg5Ti" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1inA4cAucaFMCc29oVyzX8vXdX1anVqvU" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1BOb_jGT2YrYR7XOWJidBPZyNI8a2aKm2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1EJeI670W0yrtvPSfCmLxbOZmHXG7ova2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HrXugz7g0JUacfLbZIoBFWuh9MzOg5Ti" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1inA4cAucaFMCc29oVyzX8vXdX1anVqvU" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Vinland Saga - Episode 24 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1XQD9r1rEnuVeVzwPug6CV4jS0ATR4oXL" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FalzQLi_I_ZSMsQ8sGWi_BBXTnavHmo-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iKoN2fX5JxUZ-v4vXzokJNOA4S1WMiO6" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TSGnPvUkAxadJw5sRb27LDrTFxD6CrF8" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1XQD9r1rEnuVeVzwPug6CV4jS0ATR4oXL" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FalzQLi_I_ZSMsQ8sGWi_BBXTnavHmo-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iKoN2fX5JxUZ-v4vXzokJNOA4S1WMiO6" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TSGnPvUkAxadJw5sRb27LDrTFxD6CrF8" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
