---
layout: post
title: 'Diamond no Ace: Act II Episode 01-52 END Subtitle Indonesia'
date: 2020-04-09 16:23:49.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '14955'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=901&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/04/diamond-no-ace-act-ii-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '1519'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1645289120;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/diamond-no-ace-act-ii-episode-01-52-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://4.bp.blogspot.com/-LXqZPPfPdwk/XKWEkglJ2cI/AAAAAAAAL7A/T7YEyD50WzcdslO2daU3Vj50CPKqpl30gCLcBGAs/s1600/Diamond%2Bno%2BAce%2B-%2BAct%2BII.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/04/Diamond%2Bno%2BAce%2B-%2BAct%2BII.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> Ace of Diamond Act II, Daiya no Ace: Act II</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Comedy, School, Shounen, Sports</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 52<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 2 April 2019 - 31 Maret 2020<br /><b>Studio Produksi :</b> <b></b>Madhouse<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 8.32 (MyAnimeList)</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Mengambil cerita setelah akhir turnamen musim gugur. Ketika dimulainya turnamen di Koshien, Tim baseball SMA Seidou bertanding dengan wajah-wajah baru dan lama.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/18IaQwVFhIjONQ-DqrYCr5itCJ8cz1DKf/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1sqSsUVhBYD4exDWYFrGuzRLsO0PvpuD8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/12oPRq9A1hkSDsOYIAgpuPWdgbgXTxbe8/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1krH0g8rSiADQGJHnnFOVTyvqtC94O_uy/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1InuD6E-L2TJhgWkBYIJhT84Q39Ai1iS1/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/15TTor1AHyNlv_wrhxsL9aeXtOHVPFqKh/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hZ7v6lAIBjrn7JcC-3yChWP0-rOJQUl2/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1P0D0dhKHRoAW3BO2w6wJCQN6ZzEJLgTl/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1IuGtdPEbm0S6Tf63MQm4KVeR3MP8OmpU/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/13jBZg8PNaJ7m90EBvCEES2v_M3zACO6c/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hOSh7-I-7KRePbV6XCY2W2x0DevvfybR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1FaWp1Cwn9BvXaG1pGlATjtwZj8API-Nh/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/18dGeeDAHxd4Ro_Y8u-VfBBYYKN7n-Dd_/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1L_UOE4YLCGLzZasYqaGWGLvvLzrm0_qe/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1O48pBIKIYnx9aHME_haSn421BWXf_86a/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rG47HtBhqzHZrepOMJMGYYACxkP_1G0i/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1A9IAzaF2VZIq-xVKnv4IPI_janQ0RcxY/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1fe234gunRyU8zt89-tyDuqCy1l-R-idK/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/134FauMKi6mGI8xohgZ6rKv4KP0NApElD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1pS2Dmw1IT3BEbvhTnN9RNOxYgOH9T8US/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1iElT7izK0iUmit7WBRsgp5IUEbowG4wa/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1XY5YUrUYewuARn3qc-QopkC6LbQc2SGo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/146EIctvJU11x8W0C2GN1JoPONPlo0xzl/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hBuB3rPq9E9nof3xH0-BMGbGiay4Vtdf/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1oaxhbO-rj9cPJHdlmKe6lPw2xiUlytt3/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1DU85YUtln13MNyIuXi5zIYpyOM3qHt6Z/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1eNVtOUNbWg9fsDgLVysrsNfy4x_X0_Wo/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1cXlgdOu1ukedsYjALhU_HgjpQYQvZcN6/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/10M3w3HCMA9r5Ux1JEynotXT8TUodpc_P/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1bvjvUXThdHvgfiIIdopxMU3z6mV_ldMh/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1D6CK4q0WOeQVjw1_z0dJ_3kAlnCuEZZZ/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1yeKsWEUS25pqNK-DwHVxSTnIhcsAK3ca/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1pn930S171MXhSHXrG3dRu1xo7wbpGrDQ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1SRQDh4PDj3GZJW-z4BSIWWBH7Dz8uVRo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Y5WLTOJ47DCKKiW7149ubUeO5WDtPrZB/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/165NELeUh86W49G1ImWCPRv4EBAJvQl_t/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1pGK_dDi1P9FupEJhcRzZQqtSfcaU4hJB/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1lWNlKNNvJRG2Xx2T1LsuHvAWbKvGsFib/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1N5iCWdztUt_DvkNLbC392dAUrOXkmgos/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1gjcFsz9vXjNTeCFFSkjSLvJwf27t4ZFf/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1kGnYjYbSuBC3eXRpjde7tFsRmw_f_-Ji/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1wxUc49FOVdSnN5GQL7VUY2jDa70Zmu_v/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1sHRsk-n9uuS08TiSP6eyyBSqjenRM0Pq/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/11ZM9NuBO3RwW4eQ1WFmYK_KD5sy2qBAb/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1xMW9FN4b_t4EYlacV7365vi0plomxOdM/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1v_KE7hxN7d-0QvBkS8VzXbcU6-R-z6w1/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1896PTjwqHrnzs6YSMkKvmL1mQ1ca3VMg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1d8DjUbkhbJsHb4Adlt7Ih7TVHQyecphd/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1djhiUZLC_bbgYKQtu_At9o_sHYDE3_3C/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1s4qwXimVHvvbNgFnfDhZiXBC06eKuIzS/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1S1_XMj7TjsKfKH3XGPbVG3gXn7GSwvQ_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1rzEPRT0dBDuiDDMc3BNuLHHNzOR09A7d/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1sbVslddscEcbPq8Oq0WizxGz1O_AdD8N/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ECFSgBvchxT2GINS7NJjxSxqrzei31jf/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1KQit7poYTxHIBeRkWlYXCQvLhvjwsSpz/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1SnZSJ57mtBZPlQu2Jr9--RgEjAaUBctI/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1mhzweuim1KhZdYtkv-mgHhjbMWTR4bH3/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1EWRodUs6U_7YYz-glSzqtCGJ233ctI8Y/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1pcOsK94CAkaN-qiAlcMvluZ0AKhPxbhN/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1SzQPLQfNcF-xq3EzIBkVDQGDLRZYb9IN/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1tRcSgc-i3Y-x0VvwNQnuWeJwfJ7jAxaU/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ndYbT8Jga6DufBOu57VFkCSuUpvSak7e/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1xlzeyj8hqatqiLcgD_Kn1Vz4Il8-oaY0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1cf8Lu1KEmr4dyiDtEq_fN0VrnYAYLRPN/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1JLUjRNJR3TPLAkgxIyrJOAQyJISjM7VD/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/13xpy2snx1khkWhWLMi91HiI1JJK9w0mo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1JRg8GKJBN7u1pB5-f7jV_TU2DaDJ1P-n/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1uBlJ2-mORYQFsIAyJH9x21mZXmKfS23L/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1hD8bZlJTsO0HXC8bPqtTmKlKzciii8WP/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1yz9d0WnY37TTDP3iEqnr39EHusIYyie-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1fy2QqTiB6QxZpu4BBJJCTGLl-T6-UW5g/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1P1jqS2zVkoC9LOKSi4kKlklIFyjkk7Yz/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/13vm_vQgUG6ZQRMzCVe0aEeEkCpM1vcDD/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1Evt6Qp7yKeyX8c7xNXrFJqIW2W13A1Rw/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1h7hWpyNVq2YlAg646Lfpx5r8dX0fChW8/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1nVxz7iGb77DYBKjM9H43iJQY7F-Ulmcc/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1gujrAz9bFRxEsqTY99KmLKocSx1_m9A1/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/12mkYe99UaUG3Ply-XBDSjR7zJIsVac2G/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Qud9im9LNpz0GDWNkGMYjgF_hZnWv-G0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1E6IvDDU4g_qUVotoiiqzAeK6s0Ul-Q9J/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1-yqd3hwqsPRgnWpROGSlHobIq42tlVIE/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1LbsEE8Wm7VjAA4Jorgi_c6av9Zaer4Ug/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1cYtucIHEjo08W3limGCw6TtTX4_o3dbq/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1O3fJ3oep3Uf755SaoQv0AvlCWjaab10e/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/14DrESmpwb238cG4KcOSkCm31-fLbSJFP/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/14JDwUfFNrVaAT4J85mcw_cIcB32AWHsr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1d1r9ScvmBcajJDacFMKttkLBJSeNp0sE/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1M850tUN7rVUxxAZ5oNHzQUVj1s0FaLFF/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 12</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1SEpm_-mmSmGzoSC7g3Y7E6H4UST8Vu4r/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1DMhSQyJ-LPfIpf1FJTD6X1wdU-E4sXyB/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1T0k7lGl4PYJ8Cjo7IhRTvL3Wp137wivR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16Tqsy85CCO7NM4v39zN1M65_ESZlyyqu/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1f1114MPPZQyu4UHqQW57qh-S3H9bHbCY/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1tkwEV6TCZ05f9MQKg3yVkPnobl2HqbMV/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1xc-MQO20JmO3XPTsWiC_hZ-AetN7nGog/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1BWGuh9cTI0_1fcZ2t0Mt14jD9gGZBisM/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 13</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/11OqM9xMvOMevNDlq_3c05po697P4LMtu/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1H2ZqEaje2NLlsNHvGIE7UXNZirOzkb6W/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15acJbl7NSKYFirwMNcS7aG8-zEwDu7lw/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ILujnAnDkRKr8oDWC5wODtHSBINVAgWN/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1Qln_60EoNUGikEREOpX9A_isHq-v3e_f/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1SjBC07SbuvQxD_GSDlYk3Up_bi7HrrsG/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1mz7VitDuQYhyHIrEUjOw9-6XXuMdRyyW/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1bumzfSj8cF4FL_qYLYJXGvfqX0QfsmVV/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 14</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/10cP0wW24U70SbNUH4yTtfIj-KWYmsghn/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1PBNDWmpu19p8i0YO5vHLksv8e-84Upu7/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1uHPgadv24xEOJaFloYhXM-ZkRpS5W-Zm/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ZvWSPGVJd-VAmZApr-3f0aijNPtjexfU/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1LsSLgkTIOCsh-KxQmp4RQs6wRbLggcWW/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1dEzCcIgUct9PPLF7jkQ_z7ybAoMQnVbv/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1uifcm_jdxsgO2EotoS6sCy6ZA0vodTuV/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1vW_rC6K1cVvsqkd5avCfPabZRAvy03Eb/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 15</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1CPI9dSD9332O6XxIWVXX_zNCRHOmISRz/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1S7IMukw0oAzZgJHHm9u-CAU1U6nnMQj-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Dwr5U2LGBcE-mfZKQyI9NicQOIj-RoLo/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NiDg43Ulov_L_ZbpvbSgqIholK_kksjv/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vkQdM-z1wuM1l1O8GZk3uwRCb-OAOtBi/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1dfqpOf5vtFGnT-Apsv3w7Alg5EprA6OW/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1VSSw6NmrxSnnUgrIZ0IIYoCUI2USjPSx/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1eOpRaawv33puPns-CoDhpozFtya85o3J/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 16</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/122MrfRMMNT0q7RkteWq3JD6iyezQtlJ7/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1YjCxENoooVyvHOiolVTL31CUY1bLQQAS/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QrrVCudNleT9PVK2J_nqcgiBA180IHwk/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10Iqd35Af9gmsuBZ1dnn0sSlyEXIgXxPo/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vhilgmo28D6zTM36CnXbIrRx9ROxV0b8/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1qeBGN2uratSETz-grxWtt76zlV6lqf5Y/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1t8we62SW-4jBxC1t8UCSuMBBATeaiViS/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1jpJLlq1BZxfG3trFARxggHWkxnHtT1fE/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 17</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/156HQPAX__-YBbJSLteY-gFI-vk5kqvbi/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1PfPyFC2QSLA-ZZmztPyqg9W4O8T2tWjB/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/10WT3nZnWEsmSesfSUFi7WgE6uIqAk2eO/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/16bpCPMUWDdOG8DR4kVxPHSlyA5_pZval/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1wJV8cPGymntzxadXRfl_XkXQpDbTHQnO/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1goafNEtLjyyzRACo8YOnEuCIxs_4iZ2v/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1H2K8Wp_qu-7iW33fE1_1tAdbjk7dIvYw/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1JUS6cGNMcQ7HWEkqm-SsQbUyJZU_VWED/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 18</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/19d-vFzkkd_AsDfL6m5u1drfzdUkjPvAJ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1jHouzNSqFXbUE0eIdBv7heiq5Hg34rHB/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1CQ34HNy1cY2p_Ro8M26LAeYo7_juOria/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1V6WT-dABmHHCN-4xGrKux9dw6cp-0dSa/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1zov5MG_78ZC-GFmQ8vXT8u3FzgZ76ZQF/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1pBMPbYCw-wVQ3Mr2ODEiAoFtL5ryFZeA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1qXhNgk3p0_haGOAqXDQX9seLA5l-cORR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1hY1fmQJ2Ub7r8bOgYfM_37ABCbCJG-QC/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 19</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1D4OJRAYvugvuJSfSU9gsrQHYTgdNA7j6/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1CNo-aNjiC_38w1sM9OSZHky47-SzJ1Xr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QmglS7pzWxBuMc8vA0iBKv6f75iquyOh/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/17kgzRbNfi4oEphVmF8GC1VxLbbZ4EPiU/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1FmZLrY_Barwkb5cgwYOY_9GlR9-0GhjJ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1ULRL2FNI_tg5JPyOpNWheudz-OGLVMm-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1nRP9LDO8UPA8qZ_KRYrJjNljxE60rJKO/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1kyou3Ai-r0qvMsnx78a-arwxS4A-ZFmy/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 20</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1NU2E9SMwxlsuViY112XiwF3Q0X_AIkyQ/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1BL_f-AIb6z78jo04iTcY-X0gdZEtu6O_/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1IcRUWX8whlnUifB-8Nfp0fIIS7QDAFQB/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1E3bhirrpJ-0ASp1br0fmjVGam6aH1ZM_/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1vcALhVeKbwzZ4NMYCoNU41TkxXtVkw_-/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1RBDQ4ldJRX_4Xzh-2mZqQ8IGl2VrsMNu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1saxe5MsNiQBMZswK0QFi2DF_JOs4beQ0/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1pbQKxQdN_AAxMCM77jGOU_pXXg1IMT9N/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 21</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Nh78NObc12YI6SOA9CMbEUVeKibnrK6n/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1VgsfcrDDE0RpgqpUbuYcQedU1n4lNA_6/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/19hcPUfnEaBToUbgHN4XZco0lc1YFIlmW/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/15L2AWmXQFrJkR8LgBlgJygnfMH_DgZem/view" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1xuIQ3jMPmTqHWoMcsxVExN9GXjIGji9T/view" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/file/d/1t9hFExTdyBBqbPF9hBo0OyVM1HxB9TF8/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1mGT2o6tGaZeI95J8rtxMSnhHfj1X1wlL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/18Odv8fbT6Xl0_ZhijF3neIxxpvnCU1ET/view" target="_blank" rel="noopener">720p</a>]
<div style="text-align: center;"><b>Diamond no Ace: Act II - Episode 22</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1cXqWe5zDJe0ERnQXiSBEdkNtD9puQbwx" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1T7VjtcbatH8anHFS-_NFJZLmmKJdg4Y8" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RELfxl1Xs6HikBAZNMSPaudFm2_bQ4f-" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kwaijXKEfww3blL4geeyJQ_eJ3V6BRnl" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1jGtnaT5-AYIQxYZjl9R7DNHqLPqox7b5" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1eHdoKBZLraUQK65rQH8etPfLtzUXAF6Z" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Vr-39WfZnKaQLV3aNr-yOExMzxhaalzQ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rnLk4EQNJtP67wnPhbIcu-1GzPap41G9" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 23</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1hW0OJaoLYKM5QrxSxWyIeytCQnQMRn6I" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j8dr0Kt2vicV0-WA6cza9J9TA_Xa4RSl" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MmAi4UC9HRQsdwBroBEOXi_zjY4u3oGe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1bnAvyUPTamZaL1S0BCzi_kSo3ypjU8g4&amp;export=download" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1hW0OJaoLYKM5QrxSxWyIeytCQnQMRn6I" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j8dr0Kt2vicV0-WA6cza9J9TA_Xa4RSl" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MmAi4UC9HRQsdwBroBEOXi_zjY4u3oGe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1bnAvyUPTamZaL1S0BCzi_kSo3ypjU8g4&amp;export=download" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 24</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Zr4c0CDTfcfDOPFCsvvY8vnC1qVZLRAo" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fz46DEWeH36U70vFOqxWBVPEmk172HKW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1K_VePbWcOgn9BMT7V9XOhLlzib9G9u43" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1JwSVDBytu-SN8IGWUbK95bEBEN9-KqKR&amp;export=download" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Zr4c0CDTfcfDOPFCsvvY8vnC1qVZLRAo" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fz46DEWeH36U70vFOqxWBVPEmk172HKW" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1K_VePbWcOgn9BMT7V9XOhLlzib9G9u43" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1JwSVDBytu-SN8IGWUbK95bEBEN9-KqKR&amp;export=download" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 25</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1iFtiKzqakT9mqn_Jvcv3aGQrsbnNFbLV" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1B_m9acIrdhNgpQlemEF9PMzGe5axAdZN" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18mlqBAry-FoP9to4Q6XNm9o29xy3DnYT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1-XwWLvKbEl9ZBJxjHNxxf1HhZn35vPUK&amp;export=download" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1iFtiKzqakT9mqn_Jvcv3aGQrsbnNFbLV" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1B_m9acIrdhNgpQlemEF9PMzGe5axAdZN" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18mlqBAry-FoP9to4Q6XNm9o29xy3DnYT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1-XwWLvKbEl9ZBJxjHNxxf1HhZn35vPUK&amp;export=download" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 26</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1cTkc8jnrAvkQd7gROPvrdx-NR1NJvG0x" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dmu_76kz1BZEBDBxuv4cg3ose7oKEby1" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bTSJe1teMgjyDlm5ZTDWnsTyqS4dt1-8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1ndwci4ZeIExTKWq8ThsdgpIbWX7ZRChq" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1cTkc8jnrAvkQd7gROPvrdx-NR1NJvG0x" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dmu_76kz1BZEBDBxuv4cg3ose7oKEby1" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bTSJe1teMgjyDlm5ZTDWnsTyqS4dt1-8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1ndwci4ZeIExTKWq8ThsdgpIbWX7ZRChq" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 27</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1eTy7CJZ4WDRMcPtjPIP3YSkWyXF1IpSS" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ViXXdKBFulEOtElNf_ZiJz76jKLz1NW7" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Gi63UoPXPSUREjwWMRJR1sSuYN0Przqj" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1ctvjO8D2TblFzEsULesGbuhXTC79WJeE" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1eTy7CJZ4WDRMcPtjPIP3YSkWyXF1IpSS" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ViXXdKBFulEOtElNf_ZiJz76jKLz1NW7" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Gi63UoPXPSUREjwWMRJR1sSuYN0Przqj" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1ctvjO8D2TblFzEsULesGbuhXTC79WJeE" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 28</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1RAnLcjotwnS6q7EHND5pv8H3JZwhsokm" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1KxoI35C2wcCFPQHj-wJelVfg4K44fc4I" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1Gr5wJY_o46c5uBvPKVLBqEmQMJN_Eemw" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1XfDupHgmmT-qVfC5v-EuJMhlNQTcp7Mz" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1RAnLcjotwnS6q7EHND5pv8H3JZwhsokm" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1KxoI35C2wcCFPQHj-wJelVfg4K44fc4I" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1Gr5wJY_o46c5uBvPKVLBqEmQMJN_Eemw" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1XfDupHgmmT-qVfC5v-EuJMhlNQTcp7Mz" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 29</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1unch5WjtZuqso38xqPht3tGpG0RfWbhL" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ea8huvZn1UyjWxN0e0VgKQk1CIY40Z92" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16xyrWUlp_uGfJqGfAHMBsbmC6ck43BuH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QcZDxLZm2HT2goI2KpHJsAy335By0FbF" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1unch5WjtZuqso38xqPht3tGpG0RfWbhL" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ea8huvZn1UyjWxN0e0VgKQk1CIY40Z92" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/cozr06cO/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www12.zippyshare.com/v/7QpPm9Ei/file.html" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 30</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1lJYf9oOZzoqhz5QYl4xen-NFK26Qo9A4" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Br2yu6CAbHRSqBzkkET3nq6-8V_7mmIw" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AViXEfcjLHzUUmDbh50TmvUSJZFo5638" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1FJBQv-XkdHTqIjwUMjBsTjyvr_pK43_a" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1lJYf9oOZzoqhz5QYl4xen-NFK26Qo9A4" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Br2yu6CAbHRSqBzkkET3nq6-8V_7mmIw" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AViXEfcjLHzUUmDbh50TmvUSJZFo5638" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1FJBQv-XkdHTqIjwUMjBsTjyvr_pK43_a" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 31</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1f49Y2ccd7yeTHnZmiQKh-4oZbqsgaIFE" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tomhLGDmnyxFGuSEJxUgNFmISwjPmtae" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1que6sbINbHmIZjUXOWVLumgsJHqR_CLm" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QVzLytrida7mXvf_K5KUbPZ6DQehYb7E" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1f49Y2ccd7yeTHnZmiQKh-4oZbqsgaIFE" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tomhLGDmnyxFGuSEJxUgNFmISwjPmtae" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1que6sbINbHmIZjUXOWVLumgsJHqR_CLm" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QVzLytrida7mXvf_K5KUbPZ6DQehYb7E" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 32</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?id=1PLjAIvbscH7rRXD_yRWNDfUK9xfAHOxl" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1GASg5ievd9-Dx-vgIFkRIXo4EtWj2pmb" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1zzPRtVGoWADOi6y52fd9Eyn7PM4mjKdv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1oA9P-T027G_WM8jP5xNUpcJJ2q1rHfA7" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?id=1PLjAIvbscH7rRXD_yRWNDfUK9xfAHOxl" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1GASg5ievd9-Dx-vgIFkRIXo4EtWj2pmb" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1zzPRtVGoWADOi6y52fd9Eyn7PM4mjKdv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1oA9P-T027G_WM8jP5xNUpcJJ2q1rHfA7" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 33</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<strike>240p</strike>] [<a href="https://drive.google.com/uc?id=1ZtKa1CFeeLVYjSNADAkx1IXV8PF3S0WF" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13vEMxg_5I16Z1uNiP2Yb__NErGj7g3f7" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19D1tKtU6bvr8XBV040_QutBenZeaXeh5" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<strike>240p</strike>] [<a href="https://drive.google.com/uc?id=1ZtKa1CFeeLVYjSNADAkx1IXV8PF3S0WF" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13vEMxg_5I16Z1uNiP2Yb__NErGj7g3f7" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19D1tKtU6bvr8XBV040_QutBenZeaXeh5" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 34</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1MGSpmgxCFxWcHIf3uWHoNUFWT0rv4gPO" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1bki1cdMhuPZHgcCc0kvnNk7J_miLsK8M" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1akSnSLh13BxQZyxN4v150CGNC7BOfqCO" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kkY8oxRqUS3dxa8rWzPfphRlyPYHhUfK" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1MGSpmgxCFxWcHIf3uWHoNUFWT0rv4gPO" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?id=1bki1cdMhuPZHgcCc0kvnNk7J_miLsK8M" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1akSnSLh13BxQZyxN4v150CGNC7BOfqCO" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kkY8oxRqUS3dxa8rWzPfphRlyPYHhUfK" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 35</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1i5X236dR2_RADjvE23ABQmOJqtM4g7_Y" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fVIVSjbFnsYrOPufcvxKyYplrnswTu05" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j9YBpFNpumR0kXo1Dul2Dt6_hLOqPh8i" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k8lG4UxG3YPB1Ugjz4KV8nx2RrOZdrzB" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1i5X236dR2_RADjvE23ABQmOJqtM4g7_Y" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fVIVSjbFnsYrOPufcvxKyYplrnswTu05" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j9YBpFNpumR0kXo1Dul2Dt6_hLOqPh8i" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k8lG4UxG3YPB1Ugjz4KV8nx2RrOZdrzB" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 36</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1op8-ctZhYwluWYss-abNgve4PqAb_4CK" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16su95qwht69v59YjQEw4nCjIO1IIWJ7o" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_omMAUlG_t5ccCe9p-MAYAWb2N_-NSJG" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1v1Sz2ckf1L60lszk-Gz7VSabb-T1wL2D" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1op8-ctZhYwluWYss-abNgve4PqAb_4CK" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16su95qwht69v59YjQEw4nCjIO1IIWJ7o" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_omMAUlG_t5ccCe9p-MAYAWb2N_-NSJG" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1v1Sz2ckf1L60lszk-Gz7VSabb-T1wL2D" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 37</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mpoIMteRgkRNi2kDmcRgJt-pRhXWYKiR" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f_mxxzGvkRCX74yiWYa7KP1ZaqBkSFQV" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SErUIixp1frAXtPKsBIDk2euWzXDP7ht" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_veo_j8kIibo17yOacueH99aeZhl6Rmu" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mpoIMteRgkRNi2kDmcRgJt-pRhXWYKiR" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f_mxxzGvkRCX74yiWYa7KP1ZaqBkSFQV" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SErUIixp1frAXtPKsBIDk2euWzXDP7ht" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_veo_j8kIibo17yOacueH99aeZhl6Rmu" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 38</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1WWhiT_8cln1h53OQW85Eh4V44ldIqSFh" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1C_PEsrAjBndsz9qyhWvEWHqrurPz06MT" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=113yNGaNiElasO92SjEcVyQVdTtyIiFAe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=142JmR9N43_gQN6yIqgTEoibj24FyJ-5e" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://www110.zippyshare.com/v/EiBrVlh8/file.html" target="_blank" rel="noopener">240p</a>] [<a href="https://www110.zippyshare.com/v/mekkNbS6/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=113yNGaNiElasO92SjEcVyQVdTtyIiFAe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=142JmR9N43_gQN6yIqgTEoibj24FyJ-5e" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 39</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=104iybKEu5M6R5-d2863VGoqcuypP8WPB" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AzQ2lv3LMtLNDfBR3WWGV9ML-9N6gR_K" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1VpCDtu3W1inQ-nmg4CZZMGBempGiMDEr" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=13-j7oKqtMkBaMXPDJ9HIvc0vtHSPN9fC" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://www33.zippyshare.com/v/9ewZnqeU/file.html" target="_blank" rel="noopener">240p</a>] [<a href="https://www33.zippyshare.com/v/TJiAIhk6/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1VpCDtu3W1inQ-nmg4CZZMGBempGiMDEr" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=13-j7oKqtMkBaMXPDJ9HIvc0vtHSPN9fC" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 40</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ReY8cLF7oN3iZiMO3V5HhMnd4cyr0N_H" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Uwj4mYyuTe1rdtUEcLXVmAmY2pGee98C" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MtLZvDscaO46dmVafck2HvywoMnmo3wF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kOFbWf3mRu0AsfdWv6Ve5B-wONz1wyxI" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ReY8cLF7oN3iZiMO3V5HhMnd4cyr0N_H" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Uwj4mYyuTe1rdtUEcLXVmAmY2pGee98C" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MtLZvDscaO46dmVafck2HvywoMnmo3wF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kOFbWf3mRu0AsfdWv6Ve5B-wONz1wyxI" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 41</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1jpIcz1Nfds80Ja3-Tf6D_usN-wiJuAk3" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11JM1pJ_N7KjeRWF1dvkPA4oWfeflCHOg" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YUcxi7EWn3wte31VuVCdhrWBaLxbCOnQ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IZ67bHtM8kXk9Rf0g24K8G1tnLzCxazJ" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1jpIcz1Nfds80Ja3-Tf6D_usN-wiJuAk3" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11JM1pJ_N7KjeRWF1dvkPA4oWfeflCHOg" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YUcxi7EWn3wte31VuVCdhrWBaLxbCOnQ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IZ67bHtM8kXk9Rf0g24K8G1tnLzCxazJ" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 42</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=15hUjC18oedjqJy23hJrmbXqdNoHyxgF4" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lSXYa2dtgX84QInEIAvA-OJ9t6AAYYo2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12M2C4DfEZtdthk2gwxykBAIvxduzGn3V" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1YupAfre2yPJdZW4JiwPmts7nXINzA80z" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=15hUjC18oedjqJy23hJrmbXqdNoHyxgF4" target="_blank" rel="noopener">240p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lSXYa2dtgX84QInEIAvA-OJ9t6AAYYo2" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12M2C4DfEZtdthk2gwxykBAIvxduzGn3V" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1YupAfre2yPJdZW4JiwPmts7nXINzA80z" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 43</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://doc-00-24-docs.googleusercontent.com/docs/securesc/a7oe47091eq0vga11m97g0oo5ljob6kb/fr8ti96tpagsc94lb8lkgjuklqcsovcg/1580824800000/00582916440864707194/09153262204597614716/1owVukYrFVZzeGQshqvg91553J27qNxIX?e=download&amp;authuser=0&amp;nonce=bskpcc73s016e&amp;user=09153262204597614716&amp;hash=kbpek9a5ripqb4990crn7bed0ns5k4j7" target="_blank" rel="noopener">240p</a>] [<a href="https://doc-0s-24-docs.googleusercontent.com/docs/securesc/a7oe47091eq0vga11m97g0oo5ljob6kb/0qjonklmp9o45rbtreqvfro4jqh6h20q/1580824800000/00582916440864707194/09153262204597614716/1-UN1jpaeiOX068GrRTqrbt0RLlMfI7aA?e=download&amp;authuser=0" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1NsWTecdjHJXX24yKIpMj8ddSlH9MZEoC" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1EuI0UsIAfNQOqeSMunvRiQuJZMIXmjMS" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [<a href="https://doc-00-24-docs.googleusercontent.com/docs/securesc/a7oe47091eq0vga11m97g0oo5ljob6kb/fr8ti96tpagsc94lb8lkgjuklqcsovcg/1580824800000/00582916440864707194/09153262204597614716/1owVukYrFVZzeGQshqvg91553J27qNxIX?e=download&amp;authuser=0&amp;nonce=bskpcc73s016e&amp;user=09153262204597614716&amp;hash=kbpek9a5ripqb4990crn7bed0ns5k4j7" target="_blank" rel="noopener">240p</a>] [<a href="https://doc-0s-24-docs.googleusercontent.com/docs/securesc/a7oe47091eq0vga11m97g0oo5ljob6kb/0qjonklmp9o45rbtreqvfro4jqh6h20q/1580824800000/00582916440864707194/09153262204597614716/1-UN1jpaeiOX068GrRTqrbt0RLlMfI7aA?e=download&amp;authuser=0" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1NsWTecdjHJXX24yKIpMj8ddSlH9MZEoC" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1EuI0UsIAfNQOqeSMunvRiQuJZMIXmjMS" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 44</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?id=1AJHy_AzmJ9Mse1D4iKRJmyweToeIadLX" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1nRUCIgCshMXGSQHS7ER8PucK-gZaIq1g" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?id=1AJHy_AzmJ9Mse1D4iKRJmyweToeIadLX" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1nRUCIgCshMXGSQHS7ER8PucK-gZaIq1g" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 45</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?id=1SfI9qxj7iPc51UM3kZfwhYuEhMCS3VEl" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1PJ3BgfkQUaD7ovrGkqHkCsPROZAxgide" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?id=1SfI9qxj7iPc51UM3kZfwhYuEhMCS3VEl" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1PJ3BgfkQUaD7ovrGkqHkCsPROZAxgide" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 46</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1uHkhIgJDsqnyA-hlHZBlp568RPw1OYq8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QHGxqbWB5oOx7y5Nb2LqBx_95UOUI2tZ" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1uHkhIgJDsqnyA-hlHZBlp568RPw1OYq8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QHGxqbWB5oOx7y5Nb2LqBx_95UOUI2tZ" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 47</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1VvPPec81wDQ74zc56WUm7fxT_vafrw1_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1o8GuwJBbJKYRONKTc32l0m5mhiMh_I8j" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1VvPPec81wDQ74zc56WUm7fxT_vafrw1_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1o8GuwJBbJKYRONKTc32l0m5mhiMh_I8j" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 48</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1MIYwBw3NkgBDmFOvID8BixMKht55L5_P" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QPNNEJfigthBCsDTYaaaCsqDhzhkz_dI" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1MIYwBw3NkgBDmFOvID8BixMKht55L5_P" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QPNNEJfigthBCsDTYaaaCsqDhzhkz_dI" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 49</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Wi46GkGQmhxqRoU-Rli_q3p4Z1btagE9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15yimTyHMoiemX8aBBmduF6ICIR0Dtuu5" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Wi46GkGQmhxqRoU-Rli_q3p4Z1btagE9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15yimTyHMoiemX8aBBmduF6ICIR0Dtuu5" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 50</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=13ZHpSL9ynQhUhKNMYoYjNZUYz15G4BRt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O42rIU9ZYO24jWQmn5g6C_OtzfUBOwb_" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=13ZHpSL9ynQhUhKNMYoYjNZUYz15G4BRt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O42rIU9ZYO24jWQmn5g6C_OtzfUBOwb_" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 51</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1C7kurvstFLejSuDx79Zx6YGa6Jcz3bNe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Is_6me3uYlSlHVXF3jagqRNixShMJnLy" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1C7kurvstFLejSuDx79Zx6YGa6Jcz3bNe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Is_6me3uYlSlHVXF3jagqRNixShMJnLy" target="_blank" rel="noopener">720p</a>]</p>
<p><b>Diamond no Ace: Act II - Episode 52 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1jTjnhUsSrkywAQ5t7CMuiqXw-_SJ3tCY" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fmr6DKZ8Uwcedft0QDwvHfKHcYYHVxxz" target="_blank" rel="noopener">720p</a>]<br />GDrive 2 =&gt; [240p] [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1jTjnhUsSrkywAQ5t7CMuiqXw-_SJ3tCY" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fmr6DKZ8Uwcedft0QDwvHfKHcYYHVxxz" target="_blank" rel="noopener">720p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
