---
layout: post
title: Fruits Basket (2019) Season 1 Episode 01-25 END Subtitle Indonesia
date: 2020-09-24 03:08:32.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17866'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3001&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/04/fruits-basket-2019-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '838'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1653508400;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/fruits-basket-2019-season-1-episode-01-25-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://2.bp.blogspot.com/-_W_Zr2feYKg/XKgjLzMOQ4I/AAAAAAAAM8g/XUpBdHZRLBgLzV0m2O1TsL8y4Y_PEFWUACPcBGAYYCw/s1600/Fruits%2BBasket%2B2019.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/09/Fruits%2BBasket%2B2019.jpg" width="640" /></a></div>
<p></div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> <b></b>Furuba, Fruits Basket (Zenpen)</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Comedy, Drama, Fantasy, Romance, Shoujo, Slice of Life</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 25<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 6 April 2019 - 21 September 2019<br /><b>Studio Produksi :</b> TMS Entertainment<br /><b>Durasi per Episode :</b> 23 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 8.21 (MyAnimeList)<br /><b>Credit :</b> Samehadaku</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Setelah tragedi keluarga mengubah hidupnya, Tooru Honda pindah rumah. Kini ia tinggal di rumah klan Souma yang misterius. Ketika Tooru mengetahui rahasia para anggota keluarga Souma, mereka berubah menjadi binatang zodiak.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 01</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1JvP3odz3s6DySQZ9JaPTwv3_N3dDpaIK/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1V3ecS8by88kpePWyElx1CokgXb7nrRri/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1vbBewV3hwwa-JdOOllj9fMsRcKAYHDnH/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1XH9zTVT2a2X4JnJIQxo638Tn8JtOy3nt/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1_aPoHTDDwNqgt2L73YY1yl8FpgUt7kQI/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1elm1NnYoe4VZQigq9OlPNRQb88i0OOXG/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1q0IrGodd797jSa_Bbw8eB3tQodJHjQSK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1uR3gkAu2vmAUKr7eLA_4r8gGuWJleJ-F/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 02</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1ob6WkUljTbP-LsN9QE7b1BHp2LTGRqhZ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1lt13rPewenTesIKPMgxgf0AFoA2neHgT/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1N4JcQyMfmqS_NVkFH3j2_PQp2ED4u1Ul/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1vxCqofq_74KFfYUao9nb5ay8fjxztYVf/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ECj3miJcdzeNXWRguMkXFFqZ0hMlq0DV/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1GqkOfSmub4NBPFgrBP_Wj4mz2b60vqyP/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ZbHPruIjORn1CxRzRw_YjKfjl7P7HHi1/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1lAah__air1tWuz7BvmWKKF9_2vxKvbg8/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 03</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1Shr8VaWT_F-54ijss5uoy1VMQyNA5x6B/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1htSjDMpxIidXXIj2JdA5p3lD8ivLQAGG/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/11n6YPg8nhTnEIFEc9B0qzMGYV4NTGBLf/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1trMW_tUtqoxf8L7esMdx1I0F7vIP9Dl-/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1OeaVzyl2rJpu66gXrKBUsFoAbXAZKz_M/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11gcSpu1Hm9rT_75ejEg9aZewLx9jgSVg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Yhi1nRp1-03NsIV4IVw7pCwfQidWgFzv/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1XVMEIHJEKIKe54iPg4gYcKDEwLDXeBqV/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 04</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1RDt81lDPQfqqfOxZ6KwwqAE0_txO96m2/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1rZoMlGluhZGJpSgEclz4hHtqCABvRy9J/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1qQW7-TDgkAKx37Rds6Df84VkL9k5_71f/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1JbXOhqOv2bFabKCJs9h83mEAewbOPQMw/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1c7BZfs2Mq552oXhIjNZHpH_CqyQpjcib/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1gPPfqGNOdrynGzSCA_herG2A6HXmQeeL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1N6sqZqCbpZB8d2a5yYekUWbKiz3d4X8Y/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1UJT7BCKAsbp_LNmpZAupBl-KpGtjBJr_/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 05</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/14I5RIn_9fAteM5HuAdDLoABFNzz8R_fr/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1KKJIXv1LpIXlR3EmZrxnY8PEmkJy7pEs/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1l3pttskyv8OlXAuV52SRnTt5EfwJenk2/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Rj6wE9hElDKyGVMPPtu70mDn0_VKca4c/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/18JKZTaPNd0KHotY0_6iiPT4Ap3SyUYZA/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11dvY_0RJ3xCYMP3hwLLm5k_Q2febATGq/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Dv35AQ0bZlxib0LZInyYvpO_6xMTFadW/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1qLSxRR7Uo6ghCFG6MbwLtJiG9P5VfMv4/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 06</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1L_87Ods15kbTImzgbqVNwxzTwSW8RUbm/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1_NtTM0AJsXAXDphtuF0Kn03Y3LId1BQa/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1qD4sJEr2sCmskIOxfbIC9-s85bYH4LoY/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1EX38gDHHq3o07JSHRn4nrJ7N8JEdwQS_/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1sgp1tvMPyFcmjiNuUFkg-rgjzC9SRzub/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1yiW8Cqzjuj7Yj4IWwX5Px5NQZQdebS89/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TAuWbnymYRSeKilPQJzlvpEExCsItZPE/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1AzKeb3mGJSz89HDbozFSIMbSpyBs8BP_/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 07</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1HJLR3h_Y5EUbRoLP__Nry8hg0fljWuCY/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/17MHrtrjOFpbn5ZoKFhjm8yob05awwLPj/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ziu2dqaGV5Q-I3SUpu9wPQzcGVxBX3DJ/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1rWYzuHQ6KOJvil5HRyjvlJqclATvtxNb/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1ydH-q1F9SK0DSRC3gmeDpLQEnBrKG07f/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1byKzAJrPPKwNUTTTbgPJtKVmImiw1_3a/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1HgYPy-KQc9Ty8mINn_7HXu008pe-v7xw/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/12f1QdORVaIMGpXtItS3gAPhnCUWWJ4xY/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 08</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/169OVZ_Bg-o0FAZRZAzPRp2QIkE66UGvb/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1CCsUofDbulvfMH-lGqk0WSlKVYdyKP1j/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/197mKdCEnERyGX-QRGN4XIW_ER35DNhVu/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1MXUj-p3QLS15Odl3KQ7kyps-e4bbyyIZ/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1lKB4ckOIPwIhry1VRqSeCQb9IMRIU9Wz/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1pQKQYVRw1AK6kYFJECTWgApAYi03NlWg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1tSfoaySNlaC7x7uYz5dgwmwBYlKXIsII/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/10Z0-grdX1AZ6-4WHonUHRbiD8byw9F-0/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 09</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1JTjupKPMvAt7CDZUbvZRULGjyfARHhHa/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1NWla0USg72Pi4kFJoZrcKNqvGR69bvCg/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1Q8PLZcPbtBpfP-tZMWmt9mpDq0xbwmYn/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1CXbuoD0-IDS6B27-PHRG5ulUy6dii_A-/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1pwJsCvVDWOT6IOCGXMe2bPM8HHSMkZiy/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/18g5nS4jgOEIa2fTiplnkpuegKeFmydCd/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ukHGHEFqXt7Gvm5wlwc2-nz9rb_2LG7f/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1dhAnCA3kGXCbwBqsTs7O9S1gNZY04f-J/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 10</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/19UKz7JJkfsgxmj1GIFrB4F566-BBhs9G/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1C7eg-juPeg56hE4ORrb8l4WYvMkXzzHL/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ewDFnWV7HvWwqPhh3KB-I91ypvkZ6XON/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1HSvU8s2BsJf6LQDyU_rX9NfoOjQvVzow/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/19NBGb-6se6_8RsT6MYsL4RcRIG0WHs2P/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1dLWrbshcJalnQLOCjBDRsWandOx5Gb3x/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1mAjZMEQprOsNQr7rsMkUvYRLw6d3BZvs/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/19TaxNtEBau_3qPhp9z7mQRdksFYpxeJV/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 11</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1PdMHHwpkHR8jik_goXOt4ydiOjLH96v_/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/16kT6Bq5OSadw1LYS-05xDjfENw8UYSo1/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1AyNnZpeB4irXAsMJ2VNmbJBWdUC3rrus/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1FoF189C_l2MH5KUzJhN4p5AJEMRPDGNh/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1s4gMX2hx9soXfJAQFBz68RzJ5YuXgrB-/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1GHxFHkv87Mfcuuqs9ZpjuzC8t7R6w2XA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1oHOgMSIMjf9Bcf_9WlFnS8bFbA3CuZFv/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1mIobHZX9UTwMeV0kMLrY3Y-lyvn_2110/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 12</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1C0N5TCW6EIfUkAVV-8ThoM7jynPD6SwP/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1oD4ounhbZCGu9tLpsryGHtDoJacj6U2z/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1bud9XR9MsAgxLJ_YgEFn5AwrmWXn1PP1/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Vmej5hcSoogY6EA5vwO7q7MCM7oHdHVx/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1SGX9-tUaENsK09t-0SjNhxyseEkqabxC/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/11m_43CVsFs1Pm2nUbRd92Wjy1df--D7s/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1TNrAh7Zgkp53vrlOdE0hE-sn1r69VJUN/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1n10M-YQEBZIknh2Sif7SRy1htTPyMAeS/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 13</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1TNctIBlrS643c5KBNJGDpg53imGlJRbl/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15Zi2P8vzPfO5ru3yBYJ8aqXa2WTaHUDR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1WepNrHcg5KUewkqmx-ghJbFGJ3UtuBhk/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/19MTLD5GFmp68L8FdcunQ2DxArskeAiAz/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1YtKEWpJhR2froxiA4-3bJTZd92HIPwbV/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1LNvyzw5BxTK8P-7EgAHBStgG99i2gEy9/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1sDn56u26xEjQxT3NVmkKTyydmxwNeo4M/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1Lk4NjOWGQGUszTZ3Qun2WwapFec3mbKk/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 14</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/10JqCv84Y7mKqTaa58PAXFxXvP4beI5tR/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1QPjprbHZZgj-4Y6jYwKYL0Dxl31OFzwp/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1KGL7KhJ8cFNeM65XsfgOO4Z2OWqtLnPx/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/12rs9JPViV8SAoY00o9jHlo92m1ARobe6/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1y3TcbnfFFK6vKOaEQ1ROcRnKM5dnWmXo/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1sJ9XWl3mH-VkPgpgSJ6Naw2aofb0c3SI/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1LgRfIVJPfky5Ojv6SCgr1Jw62ZDVQNvK/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/12v1buiGFRIRsQCvxmqdFdDgaJDYfF-tI/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 15</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1P_WeJTw0rPFBA4us89BZzf5N--_A5N1B/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/13whuKK761gPPcPtSo5zeeA4L1oGC--1_/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/17WQycQpLd4oJgCLjUESmMSWVOLr5_Uqe/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1TcmdMElC0nv3QM0-cyROAYIu9IJMoxhf/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1xPYYvysOu1IKXf4Ed9mHhvxF9vNEV8x0/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1JqS_fwER4bfKn80UOyYv-gNq6ymBs2lt/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/19hI_Unc037-0QfiWXOlAXrzDZwzJlGRG/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1qG7Gtbcm7bVlXy6Y5nzLHS79sLraGzX5/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 16</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1E8kLvOOQLtP3D9ZjkP4UxpWz2qKrC2EQ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/13ybdCw2uQI97Uvp0Bvkp-H2tNKIgmVUU/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1XogqkNUY3a1lI9kt-627cNGIOPQHkted/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1MMn70IeY769nmGOb84RR6HW8rv9KQK-8/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1QlwngOHHiUFwovt7gZxzqDmVA2Ph851O/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1ymLvWKyd_CIuvc8K-GNUJ1EgIGeiAgwY/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ycR38K3NNcGI6N4bCa7R7QQCCAM-Sp38/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1WwU_2ZV6M80Bc8_piOiFe8ZEENWJimAc/view" target="_blank" rel="noopener">1080p</a>]
<div style="text-align: center;"><b>Fruits Basket (2019) Season 1 - Episode 17</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/10f-utZlFUIDJiLgHMQfWG-UMMKawM0qd/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1Ym8i104inaFfHylqf8G0H-a4MJzaqElj/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1GKIh4PTxhnpKc5BljYnzOoNamqBmaYuP/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1OqHN8Q7nq7MRbn-sHVDpuOM-werlxqrO/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1KoqZ85CVQgaXC7yYavFYa4bpGZwNjXDE/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1hGD083916evTgzAMjQBxOBIO-nmPfCDo/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1NVou_VOhH2reNGvX9jwZlKiHP9Gh_-aG/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1mqCl_E5ePwKW3sqfkQE_SbBeMDsE2X_T/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 18</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1hMOfatPHYybKDXJgcGu4i6d3kipPOQGZ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1SZDIBt_3O9kJmMsWNDJOZ6bTiHMSOQRR/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/12cd3EjTLexrmkcSkM0_wBG22jnBV_ks4/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1588Lq_h5Njxv8cL_gSQWT0z0iR9G8gTX/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1xFBax8hZe4_mrySl1Dw5n39LvZGq5cI7/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1VnA3YKOnYYHdC70_1fEyybG6q3MDSJRI/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1ja4z-Xf7Zbv9WvYwJ5U9Wck7y3IFQV8Y/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1NEc9HenZLRjf84nP89AywY0rxoLVQxb9/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 19</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1cX7zu7wVG60V-oRqHvwZrDRmIyIlXQNb/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/15wlE5gPD81DIdzGwLfXF20_VMqmhasOA/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/10EnCVcCblTKh09Sq93dwwAFdIeRDyD17/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1LAiBqlDc9bJ9F_jWDDuq5Tf5yQ3xlhYr/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1qzjcSaavlhRymlZK6MxphhAQTKJLhEnu/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1XwptioARn2blnTNNfQd2jr-kfdMa5qDD/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1RCpmWJcG-nZQGJ9fEG0XeMxjDsvU2C3B/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1kt-VcBZForREHbaeS9t7nelhUfFfFtD_/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 20</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/file/d/1SPSwf-H5IieVYUxKWHtlb3-k3x5ws9o2/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1EQ3lXKfK2tvKzGyem3SVKUR1OuYwJsrI/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1p4BJyxOSST8fow-fv3Ra6-aaFJl1EuNw/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1FNUoRqgQlmycmtfMC1o2QEVVuvSZ_55q/view" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/file/d/1oojeQ4YHQXPLrl4m-tc6PR1mW1Eaq6JZ/view" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/file/d/1WLLKqxGngAwWwfbCY8EHwk6jrSXi9sa5/view" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/file/d/1wm_j_Wc3LUgM-sYaAt89PVw3xOYGcAqe/view" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/file/d/1PgLtRWqf4-Ze3HAgCkroXJjq7HqgMdtd/view" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 21</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1hgI9xprVBtCKFdDHQSDA6VbE3UUDHJu0" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-jDwhuNwk7PIzMjAT36eejVYCWt1Phdo" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1N47hhVN3degnWwUO-ptCK8X3rgDb_BXe" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1POJfZ89P9OLEGQ6VBf-MMGE6hYQxKs11" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1mm_K0C9AH_Lg4KxqyRylV8RqXcHvPZXa" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xk-AsV0wqnpEkkXZKo1Vt5h0DUwSIpAM" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uqdhlwm8HW_AhzpG6X1CxQ7siGPk20hf" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ccriCXPB9bnBKdYjxMi-bJ8_5ejPLlD0" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 22</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1aARaW9OHDrvjlpJT460yvlhBSUr5srdr" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dIByQAMZWIQBXQKyb9rqV4xJla9VR2e5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-IiWkD-_UmCMkcwDocsBqPRUBxxmG3Lb" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gDufZ0wbqbU5pYM8JKVmAXzjcvriNRkr" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1aARaW9OHDrvjlpJT460yvlhBSUr5srdr" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dIByQAMZWIQBXQKyb9rqV4xJla9VR2e5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-IiWkD-_UmCMkcwDocsBqPRUBxxmG3Lb" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gDufZ0wbqbU5pYM8JKVmAXzjcvriNRkr" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 23</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1_34h2GQ6sncwj2E7f1NQhAr6vfwkTqRr" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FyaDr2h-uJ0UDaHspZGfSGu81T590hXV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hGWH_k__dLC44EpKgSUk8-wYtCKzYYUe" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1S2IEji0SVjWp7TrEzYToZ7lHT6w5vw6V" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1_34h2GQ6sncwj2E7f1NQhAr6vfwkTqRr" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FyaDr2h-uJ0UDaHspZGfSGu81T590hXV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hGWH_k__dLC44EpKgSUk8-wYtCKzYYUe" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1S2IEji0SVjWp7TrEzYToZ7lHT6w5vw6V" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 24</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=12vEnjPp9NptcvYrY3iWC4GDQHVBFd4Mh" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FDpDcVCC4_YbjuMrkHtwXxmXjLmXgppD" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qE76TD6uQ1X6NRSgesVGB7z9Q3C0RdUp" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Mg-3Tafmh4zgN4iVMKlJO_yVSoVRxXLM" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=12vEnjPp9NptcvYrY3iWC4GDQHVBFd4Mh" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FDpDcVCC4_YbjuMrkHtwXxmXjLmXgppD" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qE76TD6uQ1X6NRSgesVGB7z9Q3C0RdUp" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Mg-3Tafmh4zgN4iVMKlJO_yVSoVRxXLM" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Fruits Basket (2019) Season 1 - Episode 25 END</b></p>
<div style="text-align: center;">GDrive 1 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ADEApDrwKME68US1IjVyY5vSwR3n3Jn3" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VztRrl-qOuwlBGYOZfmcKperEisztGQ5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fQ9D-xmi-HIQJ91oCVfLJDhH4kYSBOHk" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UvsU-XNR-BUdOTmIr0m6EgMUXDOctoa9" target="_blank" rel="noopener">1080p</a>]<br />GDrive 2 =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1ADEApDrwKME68US1IjVyY5vSwR3n3Jn3" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VztRrl-qOuwlBGYOZfmcKperEisztGQ5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fQ9D-xmi-HIQJ91oCVfLJDhH4kYSBOHk" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UvsU-XNR-BUdOTmIr0m6EgMUXDOctoa9" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
