---
layout: post
title: Deca-Dence Episode 01-12 END Subtitle Indonesia
date: 2020-10-03 03:59:36.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '18150'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=301&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/07/deca-dence-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '803'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1646488990;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/deca-dence-episode-01-12-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-UHhMRvAn--M/XvoCbj21s2I/AAAAAAAAeMU/FGLxAKEky5MU5oi4ZYo5TjDZGxX0mzR3ACLcBGAsYHQ/s1600/Deca-Dence.jpeg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/10/Deca-Dence.jpeg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;</b>:</b>&nbsp;Deca-Dence</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Adventure, Sci-Fi</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;12<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;8 Julu 2020&nbsp;- 23 September 2020<br /><b>Studio Produksi :</b>&nbsp;Nut<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;7.51 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Bertahun-tahun telah berlalu sejak manusia dihadapkan dengan ambang kepunahan karena kemunculan makhluk hidup yang tak dikenal, Gadoll. Manusia yang masih selamat tinggal di benteng bergerak setinggi 3.000 meter yang dibangun untuk melindungi diri dari ancaman Gadoll.</p>
<p>Penghuni Deca-dence terbagi dalam dua kategori, Gear dan Tanker. Gear adalah pejuang yang bertarung melawan Gadoll setiap hari dan Tanker adalah penghuni non-petarung yang membantu Gear. Suatu hari, Natsume, seorang gadis Tanker yang bermimpi menjadi Gear, bertemu dengan pria tua bermuka masam bernama Kaburagi, seorang tukang reparasi armor Deca-dence. Pertemuan antara kedua orang yang sangat berlawanan ini akan mengguncang jalan masa depan dunia ini.</p></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Deca-Dence&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Xk-0Ra4Faw3eitNaLVxJPq_4h0NzVFWj" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WerDysqnZXiwnFLyd9RSqjkJTCu0WdUb" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k60c7QAF-VSc3XgktQ4iPjbbFbHfgzIX" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ArJajirwZG3BzGQOeO3yXZtoN0xrqKRw" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www15.zippyshare.com/v/BaE2pvWA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www41.zippyshare.com/v/cKG8c586/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www23.zippyshare.com/v/S93FOU12/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www45.zippyshare.com/v/cTYFUxSL/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/1lnfhfslqvl2re8/%5BAnitoki%5D_DCD_02_%5B360p%5D.rar" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YR5Z6c5Z-560Ix91WJCf6NVUFGjmT6lx" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19Fta3vH7MpTKIAluqoZ76X0-u-KMYsZG" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ZVD9aNxmJjqS9uBBICuXJqT_mjlVy6Vc" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www71.zippyshare.com/v/Bc0Amr9Z/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www59.zippyshare.com/v/QzpbPfkv/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www114.zippyshare.com/v/i8snig7I/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www110.zippyshare.com/v/2nfR7z7S/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://mir.cr/YKKEL29G" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ySxqgoM0Wixir191tfzzF1_pUihGLjLe" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13leodeKrvDjabZJlMv4eLuA6vsdO4wI2" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QcV6WWIjL7jBZpvR_Xc6VEOpmfEomb_K" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www84.zippyshare.com/v/U4mIOOdg/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www69.zippyshare.com/v/VaL4G3ww/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www32.zippyshare.com/v/e7gyXbRh/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www20.zippyshare.com/v/SRzsfvmv/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/qjj73nfsph9s62u/%255BAnitoki%255D_DCD_04_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12DxiVLidUgpt4X3a8jdjehTRm40Kmkoq" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KXaJH1DdK0AOPqJQn97fy55rUB3A4oss" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hyk7cFgTFixv8ILH8HYEfeYGHb26cGu4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www72.zippyshare.com/v/FZJOrrfL/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www101.zippyshare.com/v/iOq7HXFK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www9.zippyshare.com/v/5HddDYtD/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www68.zippyshare.com/v/PPFKoeBj/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://acefile.co/f/27089535/neonime_dcd_05-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yapQqmELemrMKOjBfbLZgEKDxAcAxWhw" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pI9WnTUbVbAlrC4_vptxaEqgOihtl9PW" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O7NXGO7yvKgMnI2WnmeDMhgK6pLGViwI" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www61.zippyshare.com/v/AVjY6Jo7/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www67.zippyshare.com/v/n7Culh4j/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/rLVXHkpV/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www59.zippyshare.com/v/QXo5nLmI/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/2d0ot0mscnj7k09/%255BAnitoki%255D_DCD_06_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DMDh9Zy-JPJg-hF13o3IvRCgtq3_bPOJ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Afpu7h36ncaxmIRy0Wgrk8U7rG1afaWW" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19jf4umdvsapXlKWRjO2LqnXYN0ILeKXB" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/qoH3QyCI/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www6.zippyshare.com/v/pwvHsSyP/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www105.zippyshare.com/v/mDdTKznj/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www74.zippyshare.com/v/2rRAv6mG/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/0v8q6lm3nvy5deo/%255BAnitoki%255D_DCD_07_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19H7tW5eigED7JoSc-sK3I8gG5jf6xnS9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1jzqnCXGndTPIl8icC4amWfCcWJLYOECb" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j0M2I1Sntg6mDUWQmv86U0Re8lCGUJZ0" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www13.zippyshare.com/v/PwgBbNMS/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www6.zippyshare.com/v/mxfpq2tY/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www99.zippyshare.com/v/XOVf1eEB/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www45.zippyshare.com/v/32HXS8AT/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/cacrg4nt4g7q08i/%255BAnitoki%255D_DCD_08_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tOfqZrX2gI9du8cjsXlcjl3tomC9NDrt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JqfE4WMNb3fwK_wNNYkvyzk8gKdxtfwm" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iM8XG8oPGLDZPi2f_aMbaNQ3bhTVzK31" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www114.zippyshare.com/v/liLVeDmn/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www23.zippyshare.com/v/YTYWxneA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www39.zippyshare.com/v/ub9pkY75/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www21.zippyshare.com/v/26Lyo409/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/8ws02ip8m35hwv2/%255BAnitoki%255D_DCD_09_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Hi9pUxvWSuL_W1Jxcnm4v1Vip2-JVwqT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PPLXX845bUjd0dESCdYgQHlIYMvBLp2q" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yTvumh9hVNQGiwT6hysstx0hI9rMA7sL" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www75.zippyshare.com/v/rgjKPHNU/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www67.zippyshare.com/v/lYFpg0Jt/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www8.zippyshare.com/v/eQ54MOTs/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www33.zippyshare.com/v/s4131Nos/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/jwyjfu7fjhw4oky/%255BAnitoki%255D_DCD_10_%255B360p%255D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r27qRn-Revctor7ErlKbKl_py6mimlkY" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DBH9kM2-FMlZ3Y9hzR152tu1Ai1hWwK-" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YiW8qSjxSIfvXRNQplAFzAP5Vqy-csfd" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www2.zippyshare.com/v/I4kCuFiX/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www10.zippyshare.com/v/lBgVIV1N/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www53.zippyshare.com/v/pyGz5ZZo/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www14.zippyshare.com/v/GF3nI2ld/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Deca-Dence&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="http://www.mediafire.com/file/iyxq12k6xgz83r2/%5BAnitoki%5D_DCD_11_%5B360p%5D.rar/file" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IP7Ac7gO_SQTrsFqsxPYSyebCdeFOYVf" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O8jspBN4ISaZ2jA8Hz85fhpEzdrBIOWa" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mXMER_7RgiP0QSWXmW4PPyiH-RQhFukb" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www110.zippyshare.com/v/mBr7Xeje/file.html" target="_blank" rel="noopener">360p]</a> [<a href="https://www44.zippyshare.com/v/jtsN9Mfw/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www52.zippyshare.com/v/hadeRKTd/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www114.zippyshare.com/v/74GOqSqP/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: center;"><b>Deca-Dence&nbsp;- Episode 12 END</b></p>
<div>GDrive =&gt; [<a href="https://mir.cr/AXP4GUBL" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Mqhshgc9YD74i-3jI85xS7O6spMoO4cA" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ofW2ZoQFhjbRpJbtXOtLdO_XWpZ8w2uR" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17mPKSzG1C1dUcbdYPD-1Q-JIgBAlApad" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www14.zippyshare.com/v/UVRYeSUF/file.html" target="_blank" rel="noopener">360p</a>]&nbsp;[<a href="https://www83.zippyshare.com/v/cA52H5bw/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www47.zippyshare.com/v/fbVB6HLY/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www102.zippyshare.com/v/kgKv8V48/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
