---
layout: post
title: Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu. Episode
  01-12 END Subtitle Indonesia
date: 2020-04-09 16:28:07.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '15099'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=901&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/01/itai-no-wa-iya-nano-de-bougyoryoku-ni.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '1505'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1655496444;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:26856;}i:1;a:1:{s:2:"id";i:26858;}i:2;a:1:{s:2:"id";i:26862;}}}}
  litespeed_vpi_list: a:1:{i:0;s:12:"empty result";}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/itai-no-wa-iya-nano-de-bougyoryoku-ni-kyokufuri-shitai-to-omoimasu-episode-01-12-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-zwDHgNbziS4/XhSXFA3mr_I/AAAAAAAAdyg/PDdS0t_QlwAIcPexyZryyAbIShtgPCxnQCLcBGAsYHQ/s1600/Itai%2Bno%2Bwa%2BIya%2Bnano%2Bde%2BBougyoryoku%2Bni%2BKyokufuri%2BShitai%2Bto%2BOmoimasu..png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2020/04/Itai%2Bno%2Bwa%2BIya%2Bnano%2Bde%2BBougyoryoku%2Bni%2BKyokufuri%2BShitai%2Bto%2BOmoimasu..png" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;BOFURI: I Don’t Want to Get Hurt, so I’ll Max Out My Defense.,&nbsp;I hate being in pain, so I think I'll make a full defense build., I Hate Getting Hurt, So I Put All My Skill Points Into Defense</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Adventure, Comedy, Fantasy, Sci-Fi</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;12<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;8 Januari 2020&nbsp;- 26 Maret 2020<br /><b>Studio Produksi :</b>&nbsp;Silver Link.<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;8.27 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Setelah menerima undangan dari temannya Risa Shiromine, Kaede Honjou mulai memainkan game VRMMO New World Online sebagai karakter Maple. Karena tidak memiliki pengetahuan tentang permainan, ia mengalokasikan semua poin statusnya untuk pertahanan. Akibatnya, gerakannya lambat, dia tidak bisa menggunakan sihir, dan bahkan diserang oleh kelinci. Namun, dia mendapatkan keterampilan yang disebut "Pertahanan Absolut" karena memaksimalkan poin vitalitasnya, dan keterampilan lawan yang membunuh dalam satu serangan. Seorang pemula "mobile fortress style" dengan keterampilan beracun yang membuat semua serangan tidak valid dan mengatasi semua rintangan, ia pergi ke petualangan, mengabaikan penyimpangannya.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 01 (Pre Air)</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1qiijf6ZdjtLpFB5jAUsl9a5FAciRswD8" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1N4pdVi9SMopgA4-UDsnTY1VtuzMPFv_8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1nn97NqBcsZmntVx8FrTQKRjB5aSTUQWU" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1s5jtbvek9i8oxgJVzU90vGlZfYPn9VmF" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www86.zippyshare.com/v/CTyMGPsF/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www45.zippyshare.com/v/sJOtfDWD/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www40.zippyshare.com/v/UV2JcoYu/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www11.zippyshare.com/v/DC19JXKz/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 01 (On Air)</b></p>
<div style="text-align: center;">GDrive =&gt; [<strike>360p</strike>] [<a href="https://drive.google.com/uc?id=1kB8zWgZpDd0-iodW9WCE69JjbzsFZY-R" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=12Z11rsuKawJFSXQA7VJxFBBMg0Ipt--9" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xnoAlRVzfkrrpkW8blXD9kvPIhzioncY" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www25.zippyshare.com/v/h4jfEqbn/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www47.zippyshare.com/v/FB7XBnOU/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www17.zippyshare.com/v/f7eFCLRz/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www82.zippyshare.com/v/jaiOSHvC/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1btjth1OuwS0ScWXj57thY5B9PqZgNQ6R" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1iHuteF8tjErdPVJZGR1l0zuCwWWCXPxN" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1NOx4TWEcgWPIDH5Cjej0k49X6TAbUnMF" target="_blank" rel="noopener">720p</a>] [<a href="https://www.blogger.com/"><span id="goog_1456143267"></span>1080p<span id="goog_1456143268"></span></a>]<br />Zshare =&gt; [<a href="https://www102.zippyshare.com/v/ZGG0eOZR/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www57.zippyshare.com/v/yqkidNxS/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www69.zippyshare.com/v/O0bMNzsS/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www92.zippyshare.com/v/tb1Jev2l/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1FPN-73967lRA0b-il3Qk4GrUBz__KNDN" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=1QhfNIR61zEYRqQYmxt9gT9TYH5pHSFRK" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?id=17xjoEyNysC6Chhz9JWHX_U4U806gzL3v" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www54.zippyshare.com/v/PFctw79Z/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www82.zippyshare.com/v/Blk2LSuu/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www74.zippyshare.com/v/lyPuT9Zg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www66.zippyshare.com/v/MuDlqM3Q/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=15emb6Ol4gf9HE8BcFwGuG9opUqDrjAPc" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1EvCuVzdynINEMPYKZBjJ3n4pcJ1fmQw9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=10Kk84Cvi-Pei-jo_qsorzxE4nsTlq5xQ" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?id=1aAOyxj6pbrRGJr71ISQ_LOs9LR2kaYd-" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www19.zippyshare.com/v/7Euv371e/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www52.zippyshare.com/v/wSsl2OAL/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www33.zippyshare.com/v/UOA8K1Wg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/k3HcfW5X/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?id=1R2IziuULRDiKBQo7KlAyxqJXuhv-lXG9" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?id=1E8yqj1Nrobvvc5XCAhf23Oe6tFeMyrxn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?id=172JaYx5kZQO5S91OoxRS8BaZcei2i_Cg" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?id=181pT9BaWy3tMVG2A6KVoLr4AB7Bge8r1" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www50.zippyshare.com/v/GE1kQhrV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/Jdsdhlu4/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www12.zippyshare.com/v/Jdsdhlu4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www52.zippyshare.com/v/4N0Kiydt/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1GlpVhMJKFVz9QA9J-czHQYXZ3ehWJiL1" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xnn5z2i4AWmZlWrByKaYuqZML1nMENkV" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1s1Hl5ErV96DbniB7sHwt6OMoOlbJOq_x" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=18knCbuKFPTs3QGpEcVDM6AczuxE2brO3" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www16.zippyshare.com/v/SDND3gRS/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www19.zippyshare.com/v/0IocrRGG/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www83.zippyshare.com/v/1UXRuvgK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www100.zippyshare.com/v/jHrIoIRy/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1p9lPnZw3pp7QMjdmLkLKBC7USzlw9BD4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1HsO1X80BeVVuwWLK-mfrl4VwFOuEZcbO" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16P3UAgJsDVxHksFGBPYz0dIIjPKiVjXR" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=1ULfsy7y6S6QpAYc1Y8lA5Ec5SHrOdmNB" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www81.zippyshare.com/v/LkDIIgIf/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/hTmFOJbo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www9.zippyshare.com/v/P0VrLluG/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www34.zippyshare.com/v/1VFJlu10/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=19FH1vu-k2S6UI_t02ZmRvpRoBF4RaU7b" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1n3W2cFo6bA-4e3__CLB3y8brVSJsjYDQ" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_-xiWfFy6-IWylqXA5jKc5mGG731rlKu" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=1Uq1UeQzrpHroGVbE5YgWTeiOOjffGYfG" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www46.zippyshare.com/v/A5zwWcm3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www108.zippyshare.com/v/wAcyiXrD/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www30.zippyshare.com/v/t24tx82K/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www75.zippyshare.com/v/Vgh4ZzYQ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=120_IiZwhGbX2QS1vRJxMaJ2_EdUo9RD6" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hRbBG_u6MBCdTXONrl160ax-HJlVJWQv" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Bp42Aa9T22f6by2MmkFDXvNGOBh3Cc3B" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=1C5Rrx3JkSM0bV_eOz0N1yeUihTmZoOf9" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www25.zippyshare.com/v/5p4cc12L/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www22.zippyshare.com/v/4Ua6gFJ6/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www37.zippyshare.com/v/yscAnjzq/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www109.zippyshare.com/v/al01Y9yg/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1IO2crksxlsCvDH4bmIXYTm2-jNszERLN" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_J7ZH6YWwuzZM7LKdTalUrw5sEt5Yx0O" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=1AOUrFh7ufdcrustKwvEx1YMdB-dX4J6C" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www120.zippyshare.com/v/399IntxF/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www29.zippyshare.com/v/ahryD6Dd/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www71.zippyshare.com/v/1ejkMFFO/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/u3Arfp0q/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=14bKs4EeM9pYUgsFSLa45LtoTTGu2QScN" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1j7F8TF3Pd31tQSmlzZjtHIg1xeXSCM9n" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?id=1Q6qw851mLrdXPwMiJh4ZnVn5l7tgP1P1" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www101.zippyshare.com/v/J7vRg5Zl/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www107.zippyshare.com/v/dU4gWEqo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www88.zippyshare.com/v/ZgSUAWor/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www14.zippyshare.com/v/ioTf5jRD/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu.&nbsp;- Episode 12 END</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1NocADSJvwSKYT-4HVJrAwBofnkt9i9dx" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Vw7sZqVPonQmxk8o7LxinZP_ZfUsmZ6V" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vi3f4efr8c-dkhqeRhcqCTovyH8wtqAv" target="_blank" rel="noopener">720p</a>] [<span id="goog_1456143267"></span><a href="https://drive.google.com/uc?export=download&amp;id=12WiyQi4FWZK6U_Z7Mnq6KYDvECxryjk0" target="_blank" rel="noopener">1080p</a><span id="goog_1456143268"></span>]<br />Zshare =&gt; [<a href="https://www104.zippyshare.com/v/NHCLDxo0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/8S55D601/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www37.zippyshare.com/v/sXlvpcJW/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www104.zippyshare.com/v/HByiySwc/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
