---
layout: post
title: Gintama Season 1-5 Episode 001-328 END [Batch] Subtitle Indonesia
date: 2021-07-20 13:54:58.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '15487'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=3151&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2019/01/gintama-season-1-5-episode-001-328-end.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '385'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1655074930;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:26785;}i:1;a:1:{s:2:"id";i:26787;}i:2;a:1:{s:2:"id";i:26789;}}}}
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/gintama-season-1-5-episode-001-328-end-batch-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-KTPlwXc1nLU/XDLUWJvlfrI/AAAAAAAAGcg/kwLkvMe1-yIc-YzlR27l-mq0ouT6wvchwCLcBGAs/s1600/Gintama%2BSeason%2B1-5.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/07/Gintama%2BSeason%2B1-5.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul Alternatif :</b><br />- Gin Tama, Silver Soul, Yorinuki Gintama-san (Season 1)<br />- Gintama (2011), Gintama' (Season 2)<br />- Gintama (2012), Gintama' Overdrive, Kintama (Season 3)<br />- Gintama (2015), Gintama° (Season 4)<br />Gintama (2017), Gintama. (Season 5)</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b><br />- [001-201] (Season 1)<br />- [202-252] (Season 2)<br />- [253-265] (Season 3)<br />- [266-316] (Season 4)<br />- [317-328] (Season 5)<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b><br />- 4 April 2006 - 25 Maret 2010 (Season 1)<br />4 April 2011 - 26 Maret 2012 (Season 2)<br />- 4 Oktober 2012 - 28 Maret 2013 (Season 3)<br />- 8 April 2015 - 30 Maret 2016 (Season 4)<br />- 9 Januari 2017 - 27 Maret 2017 (Season 5)<br /><b>Studio Produksi :</b><br />- Sunrise (Season 1-4)<br />- Bandai Namco Pictures (Season 5)<br /><b>Durasi per Episode :&nbsp;</b>24 Menit</div>
<div style="text-align: center;"><b>Skor :</b><br />- 9.00 (MyAnimeList) (Season 1)<br />- 9.10 (MyAnimeList) (Season 2)<br />- 9.05 (MyAnimeList) (Season 3)<br />- 9.13 (MyAnimeList) (Season 4)<br />- 9.00 (MyAnimeList) (Season 5)</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;">Menjelang akhir periode Edo di dunia Gintama, spesies asing yang ekstra-terestrial kolektif disebut Amanto turun ke bumi, dan tidak lama setelah itu, diadakan perang yang disebut Perang Joui. Banyak samurai dan Joui patriot yang tergabung dalam laga ini untuk mengusir Amanto. Namun, militer luar biasa yang Amantos ‘mungkin, ditambah dengan lemahnya Bakufu pemerintah, menyebabkan pengajuan lemah lembut dari Keshogunan berkuasa, sehingga memungkinkan Amantos untuk menyerbu bumi dengan mudah. Pemerintah Bakufu menjadi pemerintahan boneka Amantos ‘, dan sejak saat itu, para Amantos mampu angkuh menyusuri jalan-jalan Edo. Di sisi lain, para pemberontak Joui yang berperang melawan Amantos menjadi target operasi pemerintah Bakufu. Sebagai bagian dari kampanye penindasan, larangan membawa pedang di publik dilakukan, dan samurai sampai sekarang gagah berani kehilangan semangat juang mereka.</p>
<p>20 tahun setelah datangnya Amantos, remaja dengan nama Shimura Shinpachi terlihat bekerja di kantin yang jauh bertentangan dengan keinginannya. Dia mewarisi dojo dari mendiang ayahnya namun memiliki pelatihan pedang yang sangat terbatas, sehingga tidak mampu untuk menyadarkan sekolah keterampilan pedang. Meskipun seorang anak muda, ia masih percaya dengan semangat kuno samurai. Pada titik ini, karakter yang luar biasa muncul di hadapannya, karakter yang masih mencerminkan semangat samurai kuno. Shimura Shinpachi memutuskan untuk bekerja bersama Sakata Gintoki yang disebut Yorozuya untuk mempelajari semangat samurai. Tidak lama setelah itu, seorang Amanto dari Yato dengan nama Kagura dan Inugami dalam bentuk anjing besar, diberi nama Sadaharu oleh Kagura, bergabung dengan Yorozura.</p></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download Batch:</b></div>
<div style="text-align: center;"><b>GINTAMA SEASON </b><b>1</b></p>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 001-025</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1lYqDj8iFK7JEdFWKVp7gY7zLv8Scn7LU" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vcqwuaikhLEukOmVUa0XYC59XC7LRIj-" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1o4q7zCdfts7e0gvVeflfUMsmWYBJCPtW" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gkEovX5WPLqIuDD4RfdiyxC2wtEwK_lU" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1YJVRoQGzK3Eq460NV4wlGTVXQ3PYV4lI" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zbo0bSQjpMa1Sot1x3KmjpbRA4BaYGJZ" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1z4DxzZ3LjPeKM12chPuXh6m8eSDbcOjF" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzMTdpOFpZTl80LXM" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1kJC-lVuZEnAd9-tjnZ-mhb-xg0Pxijfz" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13QgsIRlyPUpaFBac8cXA8xi-Jr-Xml62" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 026-050</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=14NhSjqeCgDuSzuStt4fG_gyunEw3MqC6" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QVGZfNl3f13u5XxZQHn3lj1UOiwU5fBt" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19XoU2uY7gc2MXHq8s0AsxczuZbpdDnd9" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16XaXkjk1hAdIq8fqj7juaMTukNLbHfDV" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1fplopJJuPYmu0sRPna6dcCBxLy1EHGdP" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1O4xX4ljwh0R920AJEQWLYRA9dHyXDvpO" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-q2ewbT2lkShV-ZVShC9mg_nkfwXaObq" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzTGFaV3VjOWxmYjQ" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1z0nMnP0IM7v-7WzmL01K_dqFE4TwSwCA" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1C8UM7zGolmRD_Cz-yToWp391oI7zoiN_" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 051-075</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1cNCj0GtYrEF1DNLJU9fzI2Nh_keDJM5K" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18s4u8E5e6fwqjGKm18nKo2-C274Um8j8" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1EJsU-tVU7tULkgJrLeRpc7s5XXB_JWcE" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1K8HXGLHrc6dwVrGeyfsdUrhuoDYL2Pc8" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1pxWqqSliEbZ5hLXTT14Gruk0zdtXsNbr" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oqtaBeXKAh7iO8zO-LxEMdcDhSVtxps2" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15F1Nbu7Q4huZrhUygTpOoW37lriCHS82" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzNWhScWJKelluM0k" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1V6WFjHrh2c_uxmeGWvQwmiiiRRtsS1N7" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CkZOEntMwFXkxInO4Hb2wBlGsml-8ROL" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 076-100</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=13CZuF2fVIB1uFrYusgv1Bt1h2qENxbxC" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1F4QPMfSZc66hshB484rJxd1TI7l6jLyA" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13CZuF2fVIB1uFrYusgv1Bt1h2qENxbxC" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1jxoQrvN5K4cbPjKBBOYwQCHoUHwKkolN" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1asdLqZZvvfYec8o_s_xgWVm9TizDOYou" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1J8Jm4xLrb9MfvyMeOoRbbVGox1q3T-cS" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1p9Ddzwd56L_zwm6GWeOlw5KgfXjosYZ2" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzcnNrWDlPaWhaaHM" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19mQ9TGupyQ9B0wZlmETYJvrelJajH0jV" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vLwPFKjPBjUl36n3g8p1dBYo9mACe05X" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;">
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 101-125</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1P3w7J0_h0rPD2If918g7QKcHnAGityhI" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dt9D6K1kfzk3SiqOLw6JX9vVGGOQh1fR" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Hz-do85CW8yC3hTtI3v8I2QTImHxePLk" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1y6GDr2mma7VzIbD2K2oHzkj3pLDCF1kz" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=0Bx96jYNTpwYTQWNCSnF1MVZmbEE" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1TSm8ShdZDHLVep9I63pW3AIzN04PA880" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oAZV6F9y6Ko2mON7fpDJeAMR3Klc-51F" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzd1VRNnE5TEctVm8" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13PB_jCziUNL-gQpvpptR4mRw0bkEMK3O" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1z7GeADVpw9z671AQmB7lBVZkqRLnzZ3n" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 126-150</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1fR5_Di6qUFupTfs9x_LxO0Csvw0fttXS" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OegnfapQUStQG3TsvNMGwWDbrhkp6Pcf" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1K4LYX46I1i5d5HEvdYSWguaadQ8D8tAr" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dGwVj_t_wad2T8ev1fMFexoIMX-ePUi9" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=0Bx96jYNTpwYTcTNGVEhaTzc5c0U" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12stjQkuN8JIkHKg3-_wuqqCa7z2YHLNI" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dxcCLJH9EgKUTJ4c_t8eqQ2AckJVKjBs" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzUXMtVDFDNXZaZ1k" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nX-9e-cohodTlA-lPWZ-Lf47_TWovkEL" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1q6Y36ITqbJUb6y1ljDTo4Qb292m0lc6X" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 151-175</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1Zvs91lPohxwds_NYAjqxvyy-PId84dZT" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1er8AyEpWc2FkbFLljNqplY8Dzfp9W2Qm" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MvBND8Vs09TARkiiF14sMsdcehdX6riR" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1drRn-cdNQq_6QI91V6m_Dr5xd8Rr3mfv" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=0BzR9oMwvou3kaHlxdXRqNjE3S00" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UrfBe0Gk4re1VT5SmmWqeyzLX3GAXzgP" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UbbR1grkshlmiJnahhSQhl_SKRvrKv1X" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=0B6i_0azgihpzSjJKRVpUNGtEX2c" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dll4pE97IVw0KGfTAhh7zBBlR8oW6PUa" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nuksxZExlAxyRzDRc3uOzHJdFh19qweM" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 176-201</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1jiQ7zyiFwBeGE_Ec-xacVz2L4p7gmKRs" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13l3TTl_L9XxA5vZuI52i7CsvS5-gD-cE" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15EV9WZfurtljg0GkqS0wU1DHfcBa3bpi" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1cJahAVJjw6mAap4E3gHJqfrqBQbWKSFY" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1V39pioDKDwqsvKIl_erThJVbtRb-qUTg" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rrEni4omiU2yKGtobQkuLQsQkLkmltO1" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lncL0kIi2GD_iNSx4h05qmwHZApH17Vb" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15EV9WZfurtljg0GkqS0wU1DHfcBa3bpi" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p>-------------------------------------------<br />-------------------------------------------</div>
</div>
<div style="text-align: center;">
<div style="text-align: center;"><b>GINTAMA SEASON 2</b></p>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 202-225</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1phFIeK06l_G9F4P6HsKd4k0vXIly24Ho" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PyS30W_IE113RUyPRd4N13fzbEr644mj" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pTvnW7ftzbdDJmqNqgj0aHbBG_gtzI5m" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R6UPJPgAcXHsG6hH89URMq8i2de2rRS1" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=0BymICEGldK6QSGxDX011dXlCaEE" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Dv1QhNO8_FodCn4Y3cvKexVZXTmKcIpM" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1R3lGJ3_eJEX4X_nk-SWuUJhoASfkVrqb" target="_blank" rel="noopener">GDrive_3</a>]<br />[<a href="https://drive.google.com/uc?export=download&amp;id=1ckJIx6judPU5B7w76RMYvCCRVpWlOzcZ" target="_blank" rel="noopener">GDrive_4</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1axnfGnyZjGah5mqHibFgtlf0JO2DOQMV" target="_blank" rel="noopener">GDrive_5</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18eqPd-7rvgrljtXQs4j5zhu3yEWdL-Wz" target="_blank" rel="noopener">GDrive_6</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1xyFsC57NFRouVGzfXVVkWTD9P_eLfV4f" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-1Hig6OoqKIsffQeEkCvR6OHPAexWNb4" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JjuOaroKg54RZsvxDLl1PjEzhusRirsH" target="_blank" rel="noopener">GDrive_3</a>]</p>
<p>-------------------------------------------</p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 226-252</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1JAX2epdYpmi-rS6JZKZg802Sl4hKwtYl" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f-CSoVlSlykmPkDKVzbxRg4lSsyURnkq" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PVl8iAs5_q1AeJYDOCYOV8DEy_eHXsfh" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KLEz2AhhcScInSMEjflGi8eQZG6hZC0W" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1edOR9qlKewApqLVIyvPqZq2VQz1T9_LU" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1c9L_iLW2MsK2mN3DaNSYNE7pwMzsIzPx" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JjKl5AKxsJ3tJ01soNXnfl_GHRY-RjJ5" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VHEZ8end24qnYxfBF8E7XNsVRMrp2Thg" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1-rWLc-WjmmYl4ZI4CXyoZa5Vlm6h98_h" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CfA7kJ4ebFOUQSWtGYUXypRB6T8ukjQA" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QnVEYpoAFG9Mp6-1URGhVBQQex3ao5QA" target="_blank" rel="noopener">GDrive_3</a>]</p>
<p>-------------------------------------------<br />-------------------------------------------</p>
<p><b>GINTAMA SEASON 3</b><br /><b><br /></b></div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 253-265</b><br /><b>(360p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=141r7pc9W6RNIYV82Hb9ISkRAOgf-Py_6" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1f-CSoVlSlykmPkDKVzbxRg4lSsyURnkq" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PVl8iAs5_q1AeJYDOCYOV8DEy_eHXsfh" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hZUO-055pdrZ2GybURBBTDHqm9naCV0F" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1CM5sIAcSoaXjr41YR69Bc_Ixqn4Ciix4" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1c9L_iLW2MsK2mN3DaNSYNE7pwMzsIzPx" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JjKl5AKxsJ3tJ01soNXnfl_GHRY-RjJ5" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iefzB8RD4NGFwGb8o5nroz__ji2gWZMI" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1Eh7JS2xVl_NoMY6RsMQF5N4B5__Z9bdt" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CfA7kJ4ebFOUQSWtGYUXypRB6T8ukjQA" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QnVEYpoAFG9Mp6-1URGhVBQQex3ao5QA" target="_blank" rel="noopener">GDrive_3</a>]</p>
<p>-------------------------------------------<br />-------------------------------------------</p>
<p><b>GINTAMA SEASON 4</b></p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 266-316</b><br /><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=11wfI5TmMKDlsvxbBm1SshxaGzs348T67" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1v82LQIGUEGiqR1ASvyUG7FvV-UmwsyDh" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CQseKB7cvzW-_tjJhjB9mD0GSFuh2Lfe" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=11wfI5TmMKDlsvxbBm1SshxaGzs348T67" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1UHkQIqT0aZf-0_7gcGjdlb7mp0TZYTsE" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1oUQBYsXXErx0ntLvrChcJObHBY7PJvQM" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1h4SNH0tHBVQGRZSpceV77zP2EslPwX_H" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UHkQIqT0aZf-0_7gcGjdlb7mp0TZYTsE" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p>-------------------------------------------</p></div>
<div style="text-align: center;">-------------------------------------------</p>
<div style="text-align: center;"><b>GINTAMA SEASON 5</b></p>
</div>
<div style="text-align: center;"><b>Gintama -&nbsp;Episode 317-328</b><br /><b>(480p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1DRgAQ2Gt4A0YVvyWB9hiws6uqfm8oiRr" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13EqmriE82FbR62-aAQEY9hHMKjipQyNv" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AxT9gYjn8rioAuQvt0mj5zvsMI2nQBGw" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OXs37gxfKb_lopaObd2lkPV-9i6f_Fla" target="_blank" rel="noopener">GDrive_4</a>]</p>
<p><b>(720p)</b><br />[<a href="https://drive.google.com/uc?export=download&amp;id=1rxW-iPTKJnFPrHO68n_wA6xMSV9isu-Y" target="_blank" rel="noopener">GDrive_1</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hrOHKiMdKPThs-nml-6eanWFAitbRwJ_" target="_blank" rel="noopener">GDrive_2</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ilfxarOIUdLIFGszohKAlWli_Mjpfsve" target="_blank" rel="noopener">GDrive_3</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OSuu1sdz7M-dEg_hhlQrDCNEJNY2hZnD" target="_blank" rel="noopener">GDrive_4</a>]</div>
</div>
<div style="text-align: center;">
<div style="text-align: center;">
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"><b>DOWNLOAD SEASON LAINNYA:</b></div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;">=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/gintama-season-6-episode-01-13-end.html" target="_blank" rel="noopener">Gintama Season 6</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/gintama-season-7-episode-01-25-batch.html" target="_blank" rel="noopener">Gintama Season 7</a></div>
<div style="text-align: justify;"><b>DOWNLOAD MOVIE:</b></p>
<p>=&gt;&nbsp;<a href="https://www.ciunime.web.id/2021/07/gintama-final-movie-subtitle-indonesia.html" target="_blank" rel="noopener">Gintama: The Final</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/gintama-movie-1-shinyaku-benizakura-hen.html" target="_blank" rel="noopener">Gintama Movie 1: Shinyaku Benizakura-hen</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/gintama-movie-2-kanketsu-hen-yorozuya.html" target="_blank" rel="noopener">Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare</a></p>
<p><b>DOWNLOAD LIVE ACTION:</b></p>
<p>=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/07/gintama-2-okite-wa-yaburu-tame-ni-koso.html" target="_blank" rel="noopener">Gintama 2: Okite wa Yaburu Tame ni Koso Aru</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/08/gintama-2-yonimo-kimyo-na-gintama-chan.html" target="_blank" rel="noopener">Gintama 2: Yonimo Kimyo na Gintama-chan</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/01/gintama-mitsuba-hen-episode-01-03-end.html" target="_blank" rel="noopener">Gintama Mitsuba-hen</a><br />=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/08/gintama-benizakura-hen-live-action.html" target="_blank" rel="noopener">Gintama: Benizakura-hen</a></p>
<p><b>DOWNLOAD OVA:</b></p>
<p>=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/08/gintama-aizome-kaori-hen-episode-01-02.html" target="_blank" rel="noopener">Gintama: Aizome Kaori-hen</a></p>
<p><b>DOWNLOAD EPISODE SPESIAL:</b></p>
<p>=&gt;&nbsp;<a href="https://www.ciunime.web.id/2019/08/gintama-futon-ni-haitte-kara-buki.html" target="_blank" rel="noopener">Gintama: Futon ni Haitte kara Buki Nokoshi ni Kizuite Neru ni Nerenai Toki mo Aru</a></div>
<div style="text-align: justify;">=&gt;&nbsp;<a href="https://www.ciunime.web.id/2021/01/gintama-semi-final-subtitle-indonesia.html" target="_blank" rel="noopener">Gintama: The Semi-Final</a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
