---
layout: post
title: Major 2nd Season 2 Episode 01-25 END Subtitle Indonesia
date: 2021-03-30 11:49:48.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '18048'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=301&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/04/major-2nd-season-2-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '536'
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/major-2nd-season-2-episode-01-25-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-M6Ul-kGLO4E/XomucEN56eI/AAAAAAAAeBg/vWNxG9if2GUwr-82DwYV8Gtjnddh9PNjACLcBGAsYHQ/s1600/Major%2B2nd%2BSeason%2B2.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/03/Major%2B2nd%2BSeason%2B2.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;Alternatif</b>&nbsp;:</b>&nbsp;Major 2nd (TV) 2nd Season</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Comedy, Drama, Shounen, Sports</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;25<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;4 April 2020&nbsp;- 7 November 2020<br /><b>Studio Produksi :</b>&nbsp;OLM<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;7.48 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Musim kedua dari serial anime Major 2nd. Daigo merupakan anak dari Goro Shigeno, seorang pemain baseball profesional. Daigo ingin mengikuti jejak ayahnya sebagai pemain baseball profesional. Namun, dengan kemampuannya yang masih di bawah rata-rata, Daigo menjadi tertekan dan kehilangan hasratnya. Akankah Daigo berhasil menjadi pemain baseball profesional seperti ayahnya?</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Major 2nd Season 2&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1NIfFkKn1eTAyLJm6Wy7Zn33pu3QxkCs4" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fyFQzArPF4Jt8pnYL4WfR8FEOfyXCIti" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wdEHRMEAJ0v0DMDET26dYl-y0AsGQ6Ch" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www6.zippyshare.com/v/drLvzolm/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www120.zippyshare.com/v/8FLeRmqD/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www71.zippyshare.com/v/KP08cyc4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www93.zippyshare.com/v/EDYCgDTQ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1QYhT2bNZ_qIU5PF9jpPFbkVY2SjMuB-V" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KMD-uD_bX3sI1c8TFwEisoOjJyO2E4sE" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1D2HC4gEu26W5WnQVIN387yHJ3neUIrqW" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www92.zippyshare.com/v/bSgTVNly/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www49.zippyshare.com/v/lDXlKCyU/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www6.zippyshare.com/v/g1tRgeFU/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/ZRVb67RS/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1qAlGo_b2gpGeD3iWghNydHFO20_hLZVd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1a6yKTDSvqi7oTJPi04Sipk1HqhgQOWw2" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1l6i1gsYltWU2qJ9wbpaHjHztghFNs9xX" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www63.zippyshare.com/v/xnylhcYx/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www63.zippyshare.com/v/hr6Tra6W/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www54.zippyshare.com/v/SpDxDVCW/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www109.zippyshare.com/v/DeXSEdxI/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Y1-oIS2Lch4IrwuXmoWtS7nvCPij-oLW" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Urw6fvZVgnZ-yTA-hW1OV40HE5pICiBx" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hH69QlrVR2Ix5TbMmYx0z8ZIBnvya3L7" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www73.zippyshare.com/v/DbkYHPRX/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www73.zippyshare.com/v/2a2ey5L2/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www67.zippyshare.com/v/dFmBnnwe/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www67.zippyshare.com/v/IsOrGyb1/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 05</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=13fMbxW5SjiQwN_ElX6pgMHDhQyLEWKXn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JRAM8kihFdmTXoB8Ys7oXMJufEUGaZ1W" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1d3iVIrYKqyDs8Rd2jYr8v9ptHg-NLpcm" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www21.zippyshare.com/v/GjsD32mq/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www21.zippyshare.com/v/JjOVSf7i/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www75.zippyshare.com/v/EurRBC1Y/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www75.zippyshare.com/v/7seIpqgH/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 06</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=100zGFeLM0W9BvvP_VE5OmOvcm68zu3Ho" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MjcX6v0MUXSgkZer5180WOFLBEfl2yED" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1axkHUyJLuYbnDLEmyKZSZfsTumpGHg9k" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www43.zippyshare.com/v/IpiGzGUl/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www43.zippyshare.com/v/0OLqXe1f/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www43.zippyshare.com/v/ds9h5hk0/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www43.zippyshare.com/v/Vc9M8DGJ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 07</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?id=1WiaZVjMOx2wEuVOAqY_gZUH7f0HGkmXa">480p</a>] [<a href="https://drive.google.com/uc?id=1Ig2Rhdqp8qSXhGnDC4VDmt8VFjOD3EYA">720p</a>] [<a href="https://drive.google.com/uc?id=1CW1n10sIVFMU5HEuUeupJnqkJr1rHS8C">1080p</a>]<br />Zshare =&gt; [<a href="https://www2.zippyshare.com/v/vrKO47fF/file.html">360p</a>] [<a href="https://www2.zippyshare.com/v/lVlgadTA/file.html">480p</a>] [<a href="https://www2.zippyshare.com/v/nbv1f7RL/file.html">720p</a>] [<a href="https://www2.zippyshare.com/v/13hrhgJA/file.html">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 08</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1tcnDFAiAXFrhl0oXLAzfPdV7WfT73MDS" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JYSiUN6RoJiIuLoLMQmqx8EEvRAaG94f" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=10w0ue_fS3rvhHFn-UwrddjexsdHSpdRK" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www68.zippyshare.com/v/mJEWuZDx/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www68.zippyshare.com/v/UZFmCAjd/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www55.zippyshare.com/v/sHB6G81f/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www55.zippyshare.com/v/e488QaPJ/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 09</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1gHMHHoNcvkwHoq0hhPeqjO6nrCRIPokT" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19Er0WKVsnPKZutwJcB8BYWx1zr5MrwIl" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vtduY1J1zi58uzdH7yaW1nF7Z_xcXym0" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www15.zippyshare.com/v/9TaD9Bmn/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www15.zippyshare.com/v/WiPQdpsW/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www37.zippyshare.com/v/Hq2QH4Dv/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www37.zippyshare.com/v/gOq4PQYm/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 10</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1thPX4rYvF1b6DCIEI6Iuc0hK3HSKfANh" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Yr7cEEwrX75nQkbEpe3ibJGMg0ZebJxr" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RNBeRjktgXPe_6sU49olnOfEQyNzOUw-" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www55.zippyshare.com/v/BEQtkAy4/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www105.zippyshare.com/v/Ldk5SWvU/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www116.zippyshare.com/v/K0n5cGkd/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www10.zippyshare.com/v/giNeD2DM/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 11</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=157f6UnpphDOy1GQurbi5tb4pRTpIPDCl" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FB6e7oKlg7dmAvJfa8G825XmmpykYuiD" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1E-RVldBaQLgA6NtrC2oXlQVpbltv1y9T" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www94.zippyshare.com/v/qul5d4fh/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www94.zippyshare.com/v/ehdz008k/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www94.zippyshare.com/v/OpqdXLjQ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www94.zippyshare.com/v/C5OLECwm/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 12</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1WR7ccpap9ezLMud5cUju7hJ-SooUykL6" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Ib-BPd7Qyk3L6AMi3G61AfbnIzvQ5EnP" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1VgTujPHJWT9U8OWEN1NkW8vLDqLTYAiP" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www53.zippyshare.com/v/DY00zqGu/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www74.zippyshare.com/v/zrqqmuA8/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www82.zippyshare.com/v/hSRrPidU/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www23.zippyshare.com/v/vKvKbbuR/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 13</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1u6ufdW0h1_UEBoKT3KKr03on47_3GTj8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ywifK6eaEPRcauqmuJ7HfEDZtISqmiQv" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1N2-q9_3UYyTJupYVFyTCybotMb4TzEkz" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www36.zippyshare.com/v/ZmTk3H9c/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www36.zippyshare.com/v/czzKsQwj/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www112.zippyshare.com/v/aHwAHivZ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www112.zippyshare.com/v/ERcKtdox/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 14</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=14XUZxm9WxAL_oodaGDFMDTeTmEWBEYND" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1quYzEOHYmKsSvEf75U4xxSLknplMMwjm" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I4XoEtNW131poS_5ltSWQgAvyNniFeAe" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www67.zippyshare.com/v/eI4j4qdM/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www21.zippyshare.com/v/1wgHFJrX/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www56.zippyshare.com/v/p3ox2fp0/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www18.zippyshare.com/v/BhuXsbCR/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 15</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1ND0EuoO9oX922UlQh1AkzlLnI2S78lqm" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ctZgZhFrxT_v4UB-rdzvMNs2aDJNIRtM" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nmYhKWdDE-kJrv7r33lpca6ZMrbZUk2j" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www43.zippyshare.com/v/Bwmnfddg/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www62.zippyshare.com/v/qqowkXz9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www61.zippyshare.com/v/LPUAuLGJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www112.zippyshare.com/v/hKA7JXIf/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 16</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1qoql54_P_WyVt7Gh1z9odARR1REjP0RH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SdrCcR8cwsBNy-feOYgsrN2vUjFPhRCB" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Bs-Do8pUIqYjs-eHrwFtzVV467a1gqOX" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www95.zippyshare.com/v/RBbZjIaW/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www102.zippyshare.com/v/efWTdfkg/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www3.zippyshare.com/v/5ZJ0m3Ky/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www81.zippyshare.com/v/8YVjMgxb/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 17</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=16CDNreuHjYO2u06E3y96sAYBplOOioAC" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UpAGI4hmChECDMlDrg_hENVrAlHB9kDL" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Fj8z9b9HdKZeaFthAlNFrTN0msY_KASa" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www63.zippyshare.com/v/uiuySNWw/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www63.zippyshare.com/v/KTFBnYEW/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www102.zippyshare.com/v/I4jargo8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www11.zippyshare.com/v/ByIeom4Y/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Major 2nd Season 2&nbsp;- Episode 18</b></p>
<div style="text-align: center;">GDrive =&gt; [360p] [<a href="https://acefile.co/f/28986938/m2nd-s2-18-480p-samehadaku-vip-mkv" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/28988851/m2nd-s2-18-720p-samehadaku-vip-mkv" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/28989926/m2nd-s2-18-1080p-samehadaku-vip-muxed-mkv" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www49.zippyshare.com/v/xu3Nu4MU/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www49.zippyshare.com/v/U40KhlQo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www120.zippyshare.com/v/a6TrJ8yJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www90.zippyshare.com/v/tuzP0MQF/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: center;"><b>Major 2nd Season 2&nbsp;- Episode 19</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Un1aVtOSuIPwY1NK7ihEKzFgytrwznvI" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_vaeDSgyZBQ2j8qHEMd7lxEVQsK3mmDw" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AsgxBDs_6HI_TzRmQeuc9b9stktqUDeq" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/zTPyEbVY/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www44.zippyshare.com/v/gkQqTQ5s/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www62.zippyshare.com/v/8EIhiXaX/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www56.zippyshare.com/v/Pt41a1eU/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 20</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1LtmM7cEmsA_Mr4bBCqGdNbtEBgSm3E2q" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RiL2uhV2V1IefOpa8VjxKUWpb2LXxV2P" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1AGBeawi-uffqVn6mUVLIead5u5S2OYeS" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www99.zippyshare.com/v/5r2Dn5Jo/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/AlRSWDQK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www12.zippyshare.com/v/AlRSWDQK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www49.zippyshare.com/v/WOO2poVV/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 21</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1VGcKVw4Y-Q62nTTFXXt7ecH82pBz3QVs" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WeoU3pSyawxhxtAJm-ODMzFRHJoigfHF" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vEqbZs5TxSx6Og4DiUVfd1MvxEkV-iVm" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www109.zippyshare.com/v/89niBjhd/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www109.zippyshare.com/v/umqGxFzm/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www107.zippyshare.com/v/XNboS9c8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www117.zippyshare.com/v/Gk702MCV/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 22</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1umV4dQYB-rPslVdBcn0umplMtV-kzct2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SD2PtNpy6HMWWAwu0fBpOajBqU94HyNL" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/30406776/m2nd-s2-22-1080p-samehadaku-vip-mkv" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www15.zippyshare.com/v/njn7ZxmA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www106.zippyshare.com/v/tJDsL3dT/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www118.zippyshare.com/v/DzVvE5Oa/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www72.zippyshare.com/v/mkXMVMIZ/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 23</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1AzmAV6Ja4zvb9x8aL2OfBX73i8_5MOoR" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mDAC3E04IwSSbfYcTjmqS-HYCnX9J_QH" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/30753997/m2nd-s2-23-fullhd-samehadaku-vip-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www94.zippyshare.com/v/bAHpSiqR/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www42.zippyshare.com/v/45Mhrr7V/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www42.zippyshare.com/v/TE09ER6F/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www16.zippyshare.com/v/JhsWvC21/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 24</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Dj4OnwnXlTGUxdy4AS8s7GLbw4DkI9in" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nFqTKTcCHcR0bMhxk-aWaXEunxicIySW" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1E-EaKbIbi7qKh-lEGVamURK_2UyCX0RM" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www4.zippyshare.com/v/MDz0A9B1/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www4.zippyshare.com/v/5sCL3PzF/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www96.zippyshare.com/v/RWumu0Xm/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www96.zippyshare.com/v/YEbQrZpq/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Major 2nd Season 2&nbsp;- Episode 25 END</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1Lk1QVTbXL8MgWEOwnAsxmiPXm4y6wKSI" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1tAic1HxVfdDf-NJKz4WADHfUIfKQYv5Z" target="_blank" rel="noopener">720p</a>] [1080p]<br />Zshare =&gt; [<a href="https://www64.zippyshare.com/v/nnH45OHa/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www3.zippyshare.com/v/zwQZYeZt/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www101.zippyshare.com/v/2NzMxR29/file.html" target="_blank" rel="noopener">720p</a>] [1080p]</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
