---
layout: post
title: Kingdom Season 3 (Episode 26 END) Subtitle Indonesia
date: 2021-10-20 14:22:16.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '20672'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=151&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/04/kingdom-season-3-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '267'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1646721380;s:7:"payload";a:0:{}}}
  kata_make_header_transparent: default
  litespeed_vpi_list: a:1:{i:0;s:12:"empty result";}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/kingdom-season-3-episode-26-end-subtitle-indonesia/"
---
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-9aPf73Oejq4/XoxCgNHjJsI/AAAAAAAAeC4/jEYeVeiDVnULP9NH-3T0sXxpP82kc1N_gCLcBGAsYHQ/s1600/kingdom%2Bseason%2B3.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/10/kingdom%2Bseason%2B3.jpg" width="640" /></a></div>
<p>
<div style="text-align: center;"><b>Judul</b><b><b>&nbsp;</b>:</b>&nbsp;Kingdom Season 3</div>
<div style="text-align: center;"><b>Genre :</b>&nbsp;Action, Historical, Military, Seinen</div>
<div style="text-align: center;"><b>Jumlah Episode :</b>&nbsp;26<br /><b>Status :&nbsp;</b>END<br /><b>Tanggal Tayang :</b>&nbsp;6 April 2020&nbsp;- 17 Oktober 2021<br /><b>Studio Produksi :</b>&nbsp;Studio Signpot<br /><b>Durasi per Episode :</b>&nbsp;24 Menit</div>
<div style="text-align: center;"><b>Skor :</b>&nbsp;8.22 (MyAnimeList)<br /><b>Credit :</b>&nbsp;Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Musim ketiga dari seri anime Kingdom. Era peperangan Cina memberikan jalan bagi generasi petarung dan raja berikutnya untuk memperjuangkan supremasinya. Akhirnya, tujuh negara kuat muncul di tengah peperangan yang tak berkesudahan. Di kerajaan Qin, Li Xin yang seorang budak, berlatih dengan penuh semangat bersama temannya, Piao. Namun, keduanya terpaksa berpisah ketika Piao direkrut untuk bekerja di kerajaan.Setelah terjadinya kudeta, Piao kembali ke Xin dan bertemu dengan raja muda Cina, Ying Zheng yang mirip dengan Piao.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Kingdom Season 3&nbsp;- Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://www.mp4upload.com/vrj3dea9cfgt" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SOMD6AxnzG8CTSSeWRrI2qlnsH09UUqd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DbOntBKWU5thtyXqSdWoacFs5laiUMTC" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1QxainsDrZ7Xq2h5ofBZB4gOrdAOcVgXu" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www73.zippyshare.com/v/cO6uRRg1/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www40.zippyshare.com/v/WACjBiFh/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www89.zippyshare.com/v/tTGlVUeP/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www83.zippyshare.com/v/QeygoUwK/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kingdom Season 3&nbsp;- Episode 02</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://www.mp4upload.com/lnjzj4hxk5oi" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dXwLXAuMVealCdqYgGg-DXrq4oQYjM4X" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1s-hRzIH-cev-5FoA-0hcaf4IAl9UX6_n" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1QJM1RM5t-nIpYjKCwxS9NeYlqvxLij30" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www45.zippyshare.com/v/QsJuTG9C/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www30.zippyshare.com/v/bQYN6OeA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www68.zippyshare.com/v/skCRKYws/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www28.zippyshare.com/v/T9saunga/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kingdom Season 3&nbsp;- Episode 03</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://www.mp4upload.com/lpp4u1mjwztx" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ySogWu-q2xsvwxIoSX_FaOWAJFnR3ksz" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bGRZkZinuPh763sWaUuCJwQHgdG0obvV" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DuG5KzXBo9JLA8QOqf6-9NC4XGABxgBB" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www58.zippyshare.com/v/mGQBnxu0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/vv8FS5BW/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www47.zippyshare.com/v/sKqpIFi5/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www47.zippyshare.com/v/iNImEd7P/file.html" target="_blank" rel="noopener">1080p</a>]</p>
<p><b>Kingdom Season 3&nbsp;- Episode 04</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://www.mp4upload.com/887rad5ejn9g" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1I7OngfcMR494xJke9zNo3lmgVeyuJhyF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QCmqrUQP3WqyfP1wUTE78npxiTkBpjd6" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?id=1wEE1JtkaUPlJ07SJ-zgsodZvL1dwlAQ1" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www11.zippyshare.com/v/h7m82ifR/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www53.zippyshare.com/v/9J94AYEZ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www71.zippyshare.com/v/Rsf5SoCF/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www68.zippyshare.com/v/OgY1GHTt/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: center;"><b>Kingdom Season 3&nbsp;- Episode 05</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/44584676/kd-s3-5-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QJu3F3R3ZgNO16QxdPO0Na5rcePNUAOb" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FPbswIhuPV1Wblkk6kUnt_XdCHhHSbD7" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OAMCLCyZGOxI8yQJQqAqSbRDu7SqFpkt" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www26.zippyshare.com/v/OY58Eneo/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www91.zippyshare.com/v/geAYeThZ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www77.zippyshare.com/v/Fw04TvNT/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www100.zippyshare.com/v/18i1tFJ4/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div><b>Kingdom Season 3&nbsp;- Episode 06</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/45094300/kd-s3-6-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1inmFXfoWv_oWDwyXSbtAjcPKTZfXXsbd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ZtpSl4ILi3Vey62Up1hr_Huoax4WK7w2" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12r9VpFdYkX_E7TiTFU9qZfQdYbMReEnf" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www31.zippyshare.com/v/CWI5caI1/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www37.zippyshare.com/v/OzRpGhps/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www64.zippyshare.com/v/yoEfhz80/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www52.zippyshare.com/v/XyY5YbOA/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Kingdom Season 3&nbsp;- Episode 07</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/45548714/kd-s3-7-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_JbIyAh8-X0kj2vmZW4QgqvGlTy4-JvF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1t-sgO7K-Q5dWHrzOJGCXk8aqqE1YYfLg" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1SB_hcOvJgpZM-eyuTl51OgMHqSWLanaW" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www87.zippyshare.com/v/ueVxvnxu/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www84.zippyshare.com/v/xgMR1lAc/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www85.zippyshare.com/v/sCT7hXSv/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www18.zippyshare.com/v/a9zjScAV/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Kingdom Season 3&nbsp;- Episode 08</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/45992419/kd-s3-8-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wGlloqtz1CsG9ojhv0s21-weCvXNZtmm" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IHMaALmOE0db5e-2xrryywnIQi-MOmFh" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zih2Af3Guwu-RAc_EAmvHPtSYNKHkS9D" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/tSIsnzR9/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www34.zippyshare.com/v/oHaEJeBg/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www93.zippyshare.com/v/TbGkOdSQ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www76.zippyshare.com/v/nZ6gjSkg/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Kingdom Season 3&nbsp;- Episode 09</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/46461480/kd-s3-9-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IKdBpVQaDDg624xemRt90xYvsaU3gJ1L" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gdNnKlbGHIG2u0dfa7M8ipb4l1BrBwG2" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qvVj91wfyawBsaOVYmc0Y436q6mttERq" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www32.zippyshare.com/v/ZvWWdezs/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www57.zippyshare.com/v/yHv9ga47/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www46.zippyshare.com/v/kd0XZfxN/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www78.zippyshare.com/v/hjlQGS3J/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 10</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/46929097/kd-s3-10-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/46932472/neonime_kd-s3-10-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/46932925/neonime_kd-s3-10-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/46932967/neonime_kd-s3-10-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www62.zippyshare.com/v/RvqS1JAs/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www101.zippyshare.com/v/Zact5pbC/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www47.zippyshare.com/v/aWFR7uHi/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www114.zippyshare.com/v/YSXIhn1t/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 11</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/47404693/kd-s3-11-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/47404699/kd-s3-11-480p-samehadaku-vip-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/47404855/kd-s3-11-mp4hd-samehadaku-vip-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/47405205/kd-s3-11-fullhd-samehadaku-vip-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www55.zippyshare.com/v/nTCwPaTz/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www55.zippyshare.com/v/cRYSnvRq/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www55.zippyshare.com/v/2nHaS2eM/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www108.zippyshare.com/v/bJ1qwVfK/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 12</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/47969642/kd-s3-12-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/47990905/neonime_kd-s3-12-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/47991236/neonime_kd-s3-12-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/47991919/neonime_kd-s3-12-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www3.zippyshare.com/v/RlYuyAAV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www1.zippyshare.com/v/oyoYSFYV/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www59.zippyshare.com/v/SgtGrfVM/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www11.zippyshare.com/v/2B69su8s/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 13</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/48539914/kd-s3-13-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/48541112/neonime_kd-s3-13-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/48541309/neonime_kd-s3-13-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/48542150/neonime_kd-s3-13-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www111.zippyshare.com/v/eu0Bhefc/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www36.zippyshare.com/v/ZaeL0OnK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www65.zippyshare.com/v/5Huk9ZM8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www104.zippyshare.com/v/OoUDLwXQ/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 14</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/50343959/kd-s3-14-360p-samehadaku-to-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/50360260/neonime_kd-s3-15-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/50360495/neonime_kd-s3-15-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/50361307/neonime_kd-s3-15-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www60.zippyshare.com/v/EPXRhAXC/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www110.zippyshare.com/v/1zqL8vBx/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www70.zippyshare.com/v/p8gV7Pgf/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www10.zippyshare.com/v/pTpclmE4/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 15</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/50883959/kd-s3-15-360p-samehadaku-to-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/50888826/neonime_kd-s3-15-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/50888829/neonime_kd-s3-15-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/50889358/neonime_kd-s3-15-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www116.zippyshare.com/v/KTajjqUp/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www63.zippyshare.com/v/38Z6Eznn/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www47.zippyshare.com/v/NqfZj91Q/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/3gnfG8xT/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<p><b>Kingdom Season 3&nbsp;- Episode 16</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/51467650/kd-s3-16-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/51494328/neonime_kd-s3-16-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/51468055/kd-s3-16-720p-samehadaku-sbs-mkv" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/51495308/neonime_kd-s3-16-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www46.zippyshare.com/v/AKondlpr/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www113.zippyshare.com/v/7SPdgXcx/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www118.zippyshare.com/v/iTuwmq53/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www58.zippyshare.com/v/SLaq8jJD/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div></div>
<div>
<div><b>Kingdom Season 3&nbsp;- Episode 17</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/52607120/kd-s3-17-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/52614440/neonime_kd-s3-17-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/52614430/neonime_kd-s3-17-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/52614851/neonime_kd-s3-17-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www58.zippyshare.com/v/Q0f9uyhU/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www8.zippyshare.com/v/NZK2x3Gp/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www87.zippyshare.com/v/h0oalrEq/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www90.zippyshare.com/v/Tmf65jzv/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 18</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/53195821/kd-s3-18-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/53245063/neonime_kd-s3-18-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/53245218/neonime_kd-s3-18-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/53245702/neonime_kd-s3-18-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www74.zippyshare.com/v/pU4Dc1Hu/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www34.zippyshare.com/v/hTEajgR6/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www61.zippyshare.com/v/QtIVqjA9/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www44.zippyshare.com/v/Gc4xDZ4b/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 19</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/53767081/kd-s3-19-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/53768571/neonime_kd-s3-19-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/53768863/neonime_kd-s3-19-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/53769336/neonime_kd-s3-19-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www43.zippyshare.com/v/xzCB9OiG/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www56.zippyshare.com/v/vH4KSUMK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www26.zippyshare.com/v/mZpMDlWJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www13.zippyshare.com/v/x4UIRF8i/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 20</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/54288870/kd-s3-20-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/54309350/neonime_kd-s3-20-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/54309354/neonime_kd-s3-20-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/54309358/neonime_kd-s3-20-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www82.zippyshare.com/v/3OIANa1U/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www32.zippyshare.com/v/Ttu8iMQ0/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www76.zippyshare.com/v/wrFVHB3l/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www106.zippyshare.com/v/bX8Yf5rA/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 21</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/ZZzzpW7deZyzP" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/54875108/neonime_kd-s3-21-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/54875112/neonime_kd-s3-21-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/54875497/neonime_kd-s3-21-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www104.zippyshare.com/v/3RZDwKkU/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www31.zippyshare.com/v/fKephoYR/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www117.zippyshare.com/v/OHbnzw09/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www107.zippyshare.com/v/byPSrDCN/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 22</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/55416208/kd-s3-22-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/55455648/neonime_kd-s3-22-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/55455654/neonime_kd-s3-22-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/55455661/neonime_kd-s3-22-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www59.zippyshare.com/v/Vn7jfjkx/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www85.zippyshare.com/v/onBsM10N/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www28.zippyshare.com/v/9YlXSgXY/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www112.zippyshare.com/v/UgdkiDkP/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 23</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/56024908/kd-s3-23-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/56035023/neonime_kd-s3-23-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/56034974/neonime_kd-s3-23-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/56035758/neonime_kd-s3-23-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www60.zippyshare.com/v/o2wGXbkH/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www25.zippyshare.com/v/vKVZlFpT/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/g7BV6Qxf/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www73.zippyshare.com/v/c12X0IMz/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 24</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/56653164/kd-s3-24-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/56692360/neonime_kd-s3-24-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/56692808/neonime_kd-s3-24-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/56703642/neonime_kd-s3-24-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www71.zippyshare.com/v/K20OzOK0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www30.zippyshare.com/v/KntiDLDq/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www39.zippyshare.com/v/lNISQg1t/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www19.zippyshare.com/v/QVhe9WdO/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 25</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/57268238/kd-s3-25-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/57268243/kd-s3-25-480p-samehadaku-care-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/57268626/kd-s3-25-mp4hd-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/57268858/kd-s3-25-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www39.zippyshare.com/v/HgDa1iHO/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www39.zippyshare.com/v/F9Q4F21r/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www38.zippyshare.com/v/lSNh3yg5/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www111.zippyshare.com/v/zHsMtdox/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div></div>
<div><b>Kingdom Season 3&nbsp;- Episode 26 END</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/57860690/kd-s3-26-end-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/57897239/neonime_kd-s3-26-end-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/57897236/neonime_kd-s3-26-end-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/57897230/neonime_kd-s3-26-end-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www26.zippyshare.com/v/BkH9uoqS/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www103.zippyshare.com/v/scI8xADK/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www103.zippyshare.com/v/scI8xADK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www91.zippyshare.com/v/vlazf0o1/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
