---
layout: post
title: Scarlet Nexus (Episode 26 END) Subtitle Indonesia
date: 2021-12-24 10:14:14.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '21386'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=1
  cyberseo_post_link: https://www.ciunime.web.id/2021/07/scarlet-nexus-subtitle-indonesia.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '154'
  kata_make_header_transparent: default
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1644876000;s:7:"payload";a:0:{}}}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/scarlet-nexus-episode-26-end-subtitle-indonesia/"
---
<div>
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-RZKJsIAsJIk/YOQD8hJJCdI/AAAAAAAAexQ/JbQynXH10XsjLKxbypFdC1Cth7usbuYWgCLcBGAsYHQ/s1280/Scarlet%2BNexus.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/12/Scarlet%2BNexus.jpg" width="640" /></a></div>
<p><b><br /></b></div>
<div style="text-align: center;"><b style="font-weight: bold;">Judul</b><b style="font-weight: bold;"><b> </b>:</b> Scarlet Nexus</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Military, Sci-Fi, Super Power</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 26<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 1 Juli 2021&nbsp;- 23 Desember 2021<br /><b>Studio Produksi :</b> Sunrise<br /><b>Durasi per Episode :</b> 22 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 6.70 (MyAnimeList)<br /><b>Credit :</b> Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Kalender matahari tahun 2020: organisme aneh yang disebut Others mulai memakan manusia. Untuk mengalahkan musuh baru ini, dibentuklah Other Suppression Force. Diselamatkan oleh tim elit ini saat masih anak-anak, psikokinetik Yuito bertahan dari pelatihan untuk mendaftar masuk kesana. Di sisi lain, sang anak berbakat, Kasane, dibina karena kemampuannya. Tapi mimpi Kasane memberitahukan hal-hal aneh kepadanya, menyeret mereka berdua kedalam nasib yang tak terhindarkan.</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Scarlet Nexus - Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://acefile.co/f/48837142/scn-01-360p-samehadaku-vip-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/48842088/neonime_scn-01-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/48842329/neonime_scn-01-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/48842611/neonime_scn-01-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www112.zippyshare.com/v/PTUUldcZ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www31.zippyshare.com/v/D8NGqjuR/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www22.zippyshare.com/v/WDGamiV4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www66.zippyshare.com/v/ua8Rc5Qj/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div style="text-align: center;"><b>Scarlet Nexus - Episode 02</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/nkKZ8xNVADV2K" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/49388245/neonime_scn-02-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/49388536/neonime_scn-02-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/49389439/neonime_scn-02-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www104.zippyshare.com/v/3WkvKgBA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www25.zippyshare.com/v/hHrlpt8z/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www38.zippyshare.com/v/IoYXSjwb/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www4.zippyshare.com/v/L1rCPqiy/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div><b>Scarlet Nexus - Episode 03</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/49981309/scn-03-360p-samehadaku-to-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/49984846/neonime_scn-03-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/49984841/neonime_scn-03-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/49984838/neonime_scn-03-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www23.zippyshare.com/v/mrOOCVBp/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www39.zippyshare.com/v/ZcbywHoY/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www93.zippyshare.com/v/L9qFWkxy/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www54.zippyshare.com/v/Wb0bmRSv/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 04</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/50589045/scn-04-360p-samehadaku-to-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/50597384/neonime_scn-04-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/50597666/neonime_scn-04-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/50598046/neonime_scn-04-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www103.zippyshare.com/v/GWuQqIe3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www102.zippyshare.com/v/0mlXgdgQ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www35.zippyshare.com/v/80Cz4dIJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www97.zippyshare.com/v/VwLGIuCD/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 05</b></p>
<div>GDrive =&gt; [<a href="https://mir.cr/ZKBLBTW6" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1OVfdqpZguwDLndTYuUb9kfLJjg19yyU_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1i9D7Wa8IEgyETwE5orMMbLQzJ8a6q0yu" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1yCujaRKQZ4VgWHw9XD4XYj_poAhgONKL" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www87.zippyshare.com/v/LRKq8QxH/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www10.zippyshare.com/v/UOfnB1gW/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www115.zippyshare.com/v/i2CQSk79/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www47.zippyshare.com/v/8KggdIhG/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<p><b>Scarlet Nexus - Episode 06</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/51761544/scn-06-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/51762802/neonime_scn-06-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/51762860/neonime_scn-06-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/51763674/neonime_scn-06-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www105.zippyshare.com/v/hpWnySfM/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www55.zippyshare.com/v/FDfQ7oi6/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www45.zippyshare.com/v/IaZWLuDt/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www77.zippyshare.com/v/q6Iap8zF/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 07</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/52345719/scn-07-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/52349942/neonime_scn-07-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/52350188/neonime_scn-07-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/52350632/neonime_scn-07-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www52.zippyshare.com/v/jBgPqsb3/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www79.zippyshare.com/v/PDxZgr3M/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www104.zippyshare.com/v/j9HpoYWK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www32.zippyshare.com/v/r5RWExxv/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 08</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/52925195/scn-08-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/52927985/neonime_scn-08-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/52928078/neonime_scn-08-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/52928563/neonime_scn-08-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www28.zippyshare.com/v/dJtxR8IB/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www103.zippyshare.com/v/q8h7DUyy/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www65.zippyshare.com/v/kq3kyCVO/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www93.zippyshare.com/v/mA8qdDHD/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 09</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/53476824/scn-09-360p-samehadaku-sbs-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/53476828/scn-09-480p-samehadaku-sbs-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/53477237/scn-09-mp4hd-samehadaku-sbs-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/53477639/scn-09-fullhd-samehadaku-sbs-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www55.zippyshare.com/v/Ww4KRyVV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www55.zippyshare.com/v/K80oxZKv/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www72.zippyshare.com/v/O1fRFVm5/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www109.zippyshare.com/v/ng5cCsXZ/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 10</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/54009645/scn-10-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/54010955/neonime_scn-10-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/54011221/neonime_scn-10-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/54011521/neonime_scn-10-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www105.zippyshare.com/v/Ts5wV5sO/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www115.zippyshare.com/v/yXpAS8T9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www43.zippyshare.com/v/ds4vhtM8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www81.zippyshare.com/v/3i3eB3Lb/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 11</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/54560967/scn-11-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/54562554/neonime_scn-11-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/54562557/neonime_scn-11-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/54561701/scn-11-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www15.zippyshare.com/v/0le5oDLD/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www120.zippyshare.com/v/wpUNZoAs/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www79.zippyshare.com/v/zm6kQWF8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www91.zippyshare.com/v/GpRC0z1Z/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 12</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/8ZBANKYVM4xNv" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/55118717/neonime_scn-12-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/55118729/neonime_scn-12-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/55118734/neonime_scn-12-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www19.zippyshare.com/v/9GvfTKsl/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www87.zippyshare.com/v/w8VXWVwz/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www4.zippyshare.com/v/ekLdzP5m/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www2.zippyshare.com/v/nKBDhGwp/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 13</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/55737919/scn-13-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/55743313/neonime_scn-13-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/55743320/neonime_scn-13-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/55743322/neonime_scn-13-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www20.zippyshare.com/v/hoiL2EEJ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www26.zippyshare.com/v/QYmUg9rS/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www3.zippyshare.com/v/vsPZ1jhB/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www55.zippyshare.com/v/vxz5HfWh/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 14</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/gy9s2thq77yg" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/56355671/neonime_scn-14-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/56355675/neonime_scn-14-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/56355992/neonime_scn-14-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www87.zippyshare.com/v/YucdSS2J/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www108.zippyshare.com/v/GUbx2ydA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www33.zippyshare.com/v/A0gHUevx/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www1.zippyshare.com/v/GnlR0D1a/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 15</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/56968659/scn-15-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/56977661/neonime_scn-15-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/56977662/neonime_scn-15-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/56977858/neonime_scn-15-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www64.zippyshare.com/v/fkzGUuiv/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www52.zippyshare.com/v/rSYBCwVt/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www62.zippyshare.com/v/QiYOAoMn/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www94.zippyshare.com/v/dWSAnlaD/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 16</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/57564202/scn-16-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/57564209/scn-16-480p-samehadaku-care-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/57564750/scn-16-mp4hd-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/57566654/scn-16-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www15.zippyshare.com/v/PWoyQa2T/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www15.zippyshare.com/v/RlBI2CNS/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www72.zippyshare.com/v/XcoRaIwX/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www63.zippyshare.com/v/mNEI4aeb/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 17</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/58131770/scn-17-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/58131778/scn-17-480p-samehadaku-care-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/58132745/scn-17-mp4hd-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/58134327/scn-17-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www33.zippyshare.com/v/1wuu9eDa/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www33.zippyshare.com/v/p15TZi7x/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/58131778/scn-17-480p-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://www22.zippyshare.com/v/6YdZKrPA/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 18</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/58672872/scn-18-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/58682045/neonime_scn-18-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/58682531/neonime_scn-18-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/58682532/neonime_scn-18-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www117.zippyshare.com/v/Wirtpjto/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www22.zippyshare.com/v/KhFOnvEo/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www84.zippyshare.com/v/oMH6FS0r/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www70.zippyshare.com/v/BHdjLzVt/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 19</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/2dQZkVm2n82x7" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/59189649/neonime_scn-19-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/59189892/neonime_scn-19-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/59190279/neonime_scn-19-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www85.zippyshare.com/v/6FcLPIMd/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www114.zippyshare.com/v/XbMYpmXh/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www80.zippyshare.com/v/XCUMkzGg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www60.zippyshare.com/v/BmrYL5dl/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 20</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/d6dpre4nop5d" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/59759255/neonime_scn-20-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/59758884/neonime_scn-20-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/59758595/neonime_scn-20-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www54.zippyshare.com/v/JMTN7YUk/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www13.zippyshare.com/v/VgHSXrID/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www63.zippyshare.com/v/zBb1rnQ0/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www116.zippyshare.com/v/EgAiBz0O/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 21</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/60325568/scn-21-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/60325576/scn-21-480p-samehadaku-care-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/60325809/scn-21-mp4hd-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/60326534/scn-21-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www26.zippyshare.com/v/ELDVJV41/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www26.zippyshare.com/v/PcYb5TWm/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www105.zippyshare.com/v/UiV0UtJ9/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www12.zippyshare.com/v/wE3Ib0gt/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 22</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/2v39412f9s0w" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/60932967/neonime_scn-22-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/60932972/neonime_scn-22-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/60933179/neonime_scn-22-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www89.zippyshare.com/v/XtI138B0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www5.zippyshare.com/v/1ZluaqyC/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www92.zippyshare.com/v/ks89LMYi/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www10.zippyshare.com/v/Nn3qcndv/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 23</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/61492954/scn-23-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/61516277/neonime_scn-23-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/61516478/neonime_scn-23-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/61516778/neonime_scn-23-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www65.zippyshare.com/v/hGWgt7xP/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www117.zippyshare.com/v/ro5og1MY/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www109.zippyshare.com/v/c1S0JG3V/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www65.zippyshare.com/v/OSDSXztC/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 24</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/62084058/scn-24-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/62096057/neonime_scn-24-480p-zip" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/62096149/neonime_scn-24-720p-zip" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/62096390/neonime_scn-24-1080p-zip" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www36.zippyshare.com/v/tM4NPB5V/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www78.zippyshare.com/v/pO6iUlTl/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www40.zippyshare.com/v/r1CxjH7J/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www101.zippyshare.com/v/AnObOZsk/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 25</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/62670186/scn-25-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://www.mp4upload.com/qagtc9zkbzc9" target="_blank" rel="noopener">480p</a>] [<a href="https://www.mp4upload.com/tzc6k8mp5cgt" target="_blank" rel="noopener">720p</a>] [<a href="https://mir.cr/QZUSHURC" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www42.zippyshare.com/v/YThs4k8W/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www110.zippyshare.com/v/jtZT5MeL/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/KFuId4vn/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www101.zippyshare.com/v/2BWpcTQQ/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Scarlet Nexus - Episode 26 END</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/63325408/scn-26-end-360p-samehadaku-care-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://acefile.co/f/63325417/scn-26-end-480p-samehadaku-care-mp4" target="_blank" rel="noopener">480p</a>] [<a href="https://acefile.co/f/63325623/scn-26-end-mp4hd-samehadaku-care-mp4" target="_blank" rel="noopener">720p</a>] [<a href="https://acefile.co/f/63326320/scn-26-end-fullhd-samehadaku-care-mp4" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www28.zippyshare.com/v/my4odKrA/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www28.zippyshare.com/v/xEqdlVRn/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www8.zippyshare.com/v/TPcq5zQg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www114.zippyshare.com/v/cPXVCzc0/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
