---
layout: post
title: Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna
  Monogatari (Episode 12 END) Subtitle Indonesia
date: 2021-03-25 17:46:17.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '17958'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=301&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2021/01/tatoeba-last-dungeon-mae-no-mura-no.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '562'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1657107597;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:27112;}i:1;a:1:{s:2:"id";i:27118;}i:2;a:1:{s:2:"id";i:27114;}}}}
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/tatoeba-last-dungeon-mae-no-mura-no-shounen-ga-joban-no-machi-de-kurasu-youna-monogatari-episode-12-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-gQE46CIXvTg/X_Px8y0K0II/AAAAAAAAeZk/w4HuB3SZfRo9tfkIeeIsHzlttyVe66ZjQCLcBGAsYHQ/s1280/Tatoeba%2BLast%2BDungeon%2BMae%2Bno%2BMura%2Bno%2BShounen%2Bga%2BJoban%2Bno%2BMachi%2Bde%2BKurasu%2BYouna%2BMonogatari.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/03/Tatoeba%2BLast%2BDungeon%2BMae%2Bno%2BMura%2Bno%2BShounen%2Bga%2BJoban%2Bno%2BMachi%2Bde%2BKurasu%2BYouna%2BMonogatari.jpg" width="640" /></a></div>
<div class="separator" style="clear: both; text-align: center;"></div>
</div>
<p><b>Judul</b><b><b> Alternatif</b> :</b> Suppose a Kid from the Last Dungeon Boonies moved to a starter town?</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Adventure, Fantasy</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 12<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 4 Januari&nbsp;2021&nbsp;- 22 Maret 2021<br /><b>Studio Produksi :</b> LIDENFILMS<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 7.19 (MyAnimeList)<br /><b>Credit :</b> Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">Lloyd muda yang optimis tidak menginginkan apa pun selain menggapai impian menjadi seorang prajurit di ibu kota. Sayangnya, tetangga dan teman-temannya menganggapnya sebagai pemuda terlemah di desa dan yakin Lloyd akan menemui ajalnya begitu dia memulai perjalanannya yang bodoh. Tapi tidak ada yang menyadari bahwa dengan tinggal di dekat dungeon paling berbahaya di negeri itu, apa yang dianggap penduduk setempat sebagai gangguan sehari-hari akan menjadi bencana bagi orang lain!Dan ketika Lloyd menentang penduduk desa dan pergi ke kota pemula bagi para petualang, seluruh kerajaan akan segera mengetahui seberapa kuat Lloyd sebenarnya!</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://acefile.co/f/34759320/neonime_lasdan-1-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RI45pjQ1A-W83zsFawvU6H_fgLzRK8Lc" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1DJqRsp2V-B3TDvfTG9s-7rFIoJQbSfv6" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1PDnb1cMmcOLlMMp6HJ-ZF_Tf5FdaJ2es" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www86.zippyshare.com/v/FtAgffKP/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www41.zippyshare.com/v/ma28JePT/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www104.zippyshare.com/v/cpWRO2cB/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www93.zippyshare.com/v/9DRAIGl3/file.html" target="_blank" rel="noopener">1080p</a>] </div>
<div style="text-align: center;"><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 02</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/35180604/neonime_lasdan-02-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1g6qY0eW1ZVd6TAXrObHHj2t_IDfUTiwp" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13rBYYljVKRDjXjVF7gHwyu7L3YRkxXea" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17X12yUxc24qU3sj-Z-llM2cevrU9Wx3H" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www9.zippyshare.com/v/Ok9cG520/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www5.zippyshare.com/v/5cdnMVkp/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www40.zippyshare.com/v/9o0zSOQ7/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www42.zippyshare.com/v/rCGJo87u/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 03</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/35622510/neonime_lasdan-03-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bfw6dQsvfW2okr7eHs_PCD1R7X29-wqn" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1h6GaND0dUhL6r8e3zdLi9RTiS_KY4LmY" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1b46sg4QyVivC8t_1ywIFIA7jltAjxUTp" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www31.zippyshare.com/v/w1ZJegQM/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www46.zippyshare.com/v/7NJnCafB/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www67.zippyshare.com/v/O7BpNwfs/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www97.zippyshare.com/v/wy9sIhee/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<p><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 04</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/36037160/neonime_lasdan-04-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wQ4i13OMLOF_OiI3eBvEhJdsP7GpOCRR" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1jdJ-MSgWXqe7ddS3MU3pHchsvX2ZdMB8" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=10KG_w60xpiGqVjs2Ci9mCoB7oNvl4rqV" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/n1mHEW2i/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www99.zippyshare.com/v/7EZ0f9t3/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www7.zippyshare.com/v/Xg46swcG/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www79.zippyshare.com/v/y4aK6igy/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 05</b></p>
<div>GDrive =&gt; [<a href="https://mir.cr/1XPVXI5V" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uVKUO2XN9RjFo1h3YSkZ1eb1AovLUX-B" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-Dp51f3KRkN-8KI6sFJkekzyzfUleNr7" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15CgtgQygYMMaERNlAkuMYPn8oW9-Atea" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www93.zippyshare.com/v/gAVrkiMM/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/QodCMwBx/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www34.zippyshare.com/v/FDY6KhEq/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www107.zippyshare.com/v/wCHVhCqU/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 06</b></p>
<div>GDrive =&gt; [<a href="https://drive.google.com/uc?export=download&amp;id=1Avez3MVM02cjZOLYmpjXUWqmjdXZX7tA" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dVtsd5ToQIMO3kFq-jP0Px0fzVt34tFt" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dVtsd5ToQIMO3kFq-jP0Px0fzVt34tFt" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15RdBUQHAk6bhUW-EDH5VB2SshRuKGbNe" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/UQ0URVGC" target="_blank" rel="noopener">360p</a>] [<a href="https://www66.zippyshare.com/v/rqVrTJdx/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www2.zippyshare.com/v/yP7znSyr/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www5.zippyshare.com/v/NIDmznO4/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 07</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/z5ne23art49h" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1qVM57osNdindn6Ig7IU9j35naz0USEP_" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1In08MLLeNb3Jy-vraOW-r6jllAW_D3C4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1gKRKQ9bx096C4rkrfNoaTk-petfB37Y2" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www110.zippyshare.com/v/ANOa5gqB/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www23.zippyshare.com/v/Jn1fZdgh/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www72.zippyshare.com/v/voGrgdox/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www72.zippyshare.com/v/6C763kZt/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 08</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/3x2x8aeu862j" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-OFeBpMp6A3F8jRMd9G41bJF8GPg1Ehf" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=19reQZodFgGwPASACpkKGNThLklmpRDaq" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lneWyXas1C_0YXAbrRAXyNe_KWBMjaAq" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www3.zippyshare.com/v/fteSmTju/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www25.zippyshare.com/v/0nSiirOj/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www103.zippyshare.com/v/Lp8SiO0u/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www96.zippyshare.com/v/MM0O243o/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 09</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/38254132/otakudesu_lasdan-09_360p-mp4" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CraM7C6CONUBLZgx_BmmJfNnnHkr4Uvd" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ZL9g0YXZkIIkSukBEN0Stvzb20Z9LqVy" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13kqaRULI0ejRBbV3z0XZygvAgsN9m8MZ" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www90.zippyshare.com/v/3kRpxNSq/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www81.zippyshare.com/v/dFbTNPss/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www90.zippyshare.com/v/IIe2vdEq/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www120.zippyshare.com/v/HTU6sv0C/file.html#" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 10</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/rlu5ag5hfrax" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=18sY6pzhV52hc9vHeLQ5nqtmgeXEw_oCz" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1giUZ20a2ujJOE0aghDmytR7w1OmSlgRI" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WDjZ6nYTNXZMw1MjKp9FISygavVJndzD" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www39.zippyshare.com/v/Tro0Azv0/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www32.zippyshare.com/v/yruJ9tIA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www50.zippyshare.com/v/vgtpYitC/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www19.zippyshare.com/v/9cMJUTNX/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 11</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/9b85ucm29xgm" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lxiK4TMvJHhzDWWmr8bmNT1c5n1lB1or" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1KWAV1Tiw3DaHPvIaEa7GImN7zhFMTUa4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_X4yLMqL3ctGWWl9e1rEojqhYmizv3o1" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www58.zippyshare.com/v/hHKh4o0S/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www105.zippyshare.com/v/tPX2lZ0M/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www4.zippyshare.com/v/6F0fq0HI/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www39.zippyshare.com/v/tbqugxtU/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari - Episode 12 END</b></p>
<div>GDrive =&gt; [<a href="https://www.mp4upload.com/shhd4swg3o2k" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1uCC6Cbt7lm6RRAC7bNKSK1pP0zM0LYx9" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1JGnDAaZlIN1OQUH6SAstGayWR5do7igz" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Gr5dW116EzWLskqv6SbO4wxpyIYAJmxd" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www96.zippyshare.com/v/5aMeIzPe/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www41.zippyshare.com/v/ErLdlRiV/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www117.zippyshare.com/v/3U4WWpt8/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www104.zippyshare.com/v/UIZbq8NQ/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
