---
layout: post
title: 'King’s Raid: Ishi wo Tsugumono-tachi (Episode 26 END) Subtitle Indonesia'
date: 2021-03-30 09:28:44.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  _thumbnail_id: '20930'
  cyberseo_rss_source: https://www.ciunime.web.id/atom.xml?start-index=151&max-results=150
  cyberseo_post_link: https://www.ciunime.web.id/2020/10/kings-raid-ishi-wo-tsugumono-tachi.html
  rank_math_news_sitemap_robots: index
  rank_math_robots: a:1:{i:0;s:5:"index";}
  rank_math_analytic_object_id: '547'
  _jetpack_related_posts_cache: a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1643554060;s:7:"payload";a:0:{}}}
  kata_make_header_transparent: default
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/kings-raid-ishi-wo-tsugumono-tachi-episode-26-end-subtitle-indonesia/"
---
<div style="text-align: center;">
<div style="text-align: left;">
<div class="separator" style="clear: both; text-align: center;"></div>
</div>
<div class="separator" style="clear: both; text-align: center;"><a href="https://1.bp.blogspot.com/-mZY0ocsiw_I/X3fwjQ1ccCI/AAAAAAAAeTo/3rn9n9FMulgF6mVmCUMaDkcX4Qd0zUQ0QCLcBGAsYHQ/s1280/King%25E2%2580%2599s%2BRaid%2B-%2BIshi%2Bwo%2BTsugumono-tachi.jpg" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="720" data-original-width="1280" height="360" src="{{ site.baseurl }}/assets/2021/03/King%25E2%2580%2599s%2BRaid%2B-%2BIshi%2Bwo%2BTsugumono-tachi.jpg" width="640" /></a></div>
<p><b>Judul</b><b><b> </b>:</b> King’s Raid: Ishi wo Tsugumono-tachi</div>
<div style="text-align: center;"><b><b>Genre :</b></b> Action, Adventure, Fantasy, Magic</div>
<div style="text-align: center;"><b>Jumlah Episode :</b> 26<br /><b>Status : </b>END<br /><b>Tanggal Tayang :</b> 3 Oktober 2020&nbsp;- 27 Maret 2021<br /><b>Studio Produksi :</b> OLM, Sunrise Beyond<br /><b>Durasi per Episode :</b> 24 Menit</div>
<div style="text-align: center;"><b>Skor :</b> 6.13 (MyAnimeList)<br /><b>Credit :</b> Neonime</div>
<div style="text-align: center;"></div>
<div style="text-align: justify;">
<div>Sudah 100 tahun sejak Raja Kyle menyemayamkan Ang Mundo. Di era yang damai ini, ksatria muda, Carsel menikmati hidupnya tanpa rasa khawatir. Namun, hari-harinya mulai berubah setelah ada kabar tentang kemunculan iblis. Dengan dipandu oleh petapa, Carsel bersama teman-temannya memulai perjalanan untuk misi pencarian pedang suci yang mampu membunuh musuh-musuh barunya.</div>
</div>
<div style="text-align: justify;"></div>
<div style="text-align: justify;"></div>
<div style="text-align: center;"><b>Link Download :</b></div>
<div style="text-align: center;"><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 01</b></p>
<div style="text-align: center;">GDrive =&gt; [<a href="https://acefile.co/f/29688388/neonime_king_s_raid_-_iwt_-_01-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UhrSpN7kVy5zMd17QsmepLb56BZGa4BH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ke_xHWbkV_fzrgs3eClcSFB4vWl6QIhH" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=157-87eoOd04q0MBiDvNDbtTgIya-9WfH" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/SOCRRFAJ" target="_blank" rel="noopener">360p</a>] [<a href="https://www26.zippyshare.com/v/qFqFKurM/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www80.zippyshare.com/v/Zdz2ByNA/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www112.zippyshare.com/v/yd1zlILT/file.html" target="_blank" rel="noopener">1080p</a>] </div>
<div style="text-align: center;"><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 02</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/30047388/neonime_king_s_raid_-_iwt_-_02-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MKtRgeg-ztt2Wzrxcrzh-b9msJrHT6PM" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1jLmF5FT9Nyri-sAVThna_J3PTwWnW6ZQ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1iincLZ63V3J2X89bcryRPuJb37zP7kP3" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www94.zippyshare.com/v/nduthSX8/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www76.zippyshare.com/v/zBGxENeA/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www41.zippyshare.com/v/NBt8xINS/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www28.zippyshare.com/v/m0BURe1O/file.html" target="_blank" rel="noopener">1080p</a>]</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 03</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/30378950/neonime_king_s_raid_-_iwt_-_03-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-72lGlmx15MbR8G8vPrRprkAuVFQnjop" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ZFNy1E2FP3Lb2t4s6ZWnakWR7uA0O4nb" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=178JH2SZNYvvod3P2Ca2cg1t-K9A_7PXn" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www50.zippyshare.com/v/nRD21P7z/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www6.zippyshare.com/v/N1wpYoL9/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www1.zippyshare.com/v/HOf0uPwg/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www9.zippyshare.com/v/Qgl18OOe/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 04</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/30716590/neonime_king_s_raid_-_iwt_-_04-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1r27jseMgSIYeYmKP8m_XqFZGZZCuAx_A" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WXGUVS_wgjzvQziOSLKlGQ0N4tMg3Elh" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1XtmsB0ghoUnCusD8oGpJ6ocukgGWzR0p" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www49.zippyshare.com/v/5iQeiOif/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www73.zippyshare.com/v/n0EdP601/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www98.zippyshare.com/v/tAyGn2ef/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www9.zippyshare.com/v/dNBTzR3x/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 05</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/31062168/neonime_king_s_raid_-_iwt_-_05-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16VfLXQrazuSoQwAqUJP9zmtFPJFTIoWB" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IKEF7MJKqM8y0Phyv23sbcdLXrFhLwzy" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1doCZ1WBtBWkQxa2QCu8Y9JCEEXg76ZA0" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www48.zippyshare.com/v/cMKdrwAk/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www69.zippyshare.com/v/tJpuVhOy/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/g3CewQlM/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www53.zippyshare.com/v/zSvgb8x9/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 06</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1iRQxfTfUqLfb1ucBva9mUl_q8YEGRg7c" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1Jme7tc_o8TbNLJzJI0guLFLZXLB01v_S" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1RoVYKIelzgVHWgq7b07uKr4IyssNpKzO" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/FYSNPBO5" target="_blank" rel="noopener">360p</a>] [<a href="https://www112.zippyshare.com/v/lYETXUNe/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www17.zippyshare.com/v/5oxtyCAZ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www88.zippyshare.com/v/kqX5LKum/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 07</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/31804480/neonime_king_s_raid_-_iwt_-_07-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1rBrp8SFoK6QK4CD-DanuFElivFHfEK85" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FCMvVKP5f6b7pQaZDM1H-_YFrYdt9-pV" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=17ltkfV8q7Yyl6WsmttOwuDgsmHm7fpf_" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/MRZQQLF2" target="_blank" rel="noopener">360p</a>] [<a href="https://www62.zippyshare.com/v/4Czs4e8G/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www109.zippyshare.com/v/gYjnqdsV/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www51.zippyshare.com/v/GSwQ45eK/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 08</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/32154597/neonime_king_s_raid_-_iwt_-_08-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1k1ksHB1U-rdT0ruapKxL-FZCxYIHLvj2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=14eOmnPF_nevWHvG8HLHcFoYPp9Bmqbqh" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1o_z9M39o9sojUm8XA8V6eKGNtfme9IZk" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www103.zippyshare.com/v/hH64bxGV/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/v1hpZVJQ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www98.zippyshare.com/v/0P02kXWK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www89.zippyshare.com/v/FixRSs2V/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 09</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/32512198/neonime_king_s_raid_-_iwt_-_09-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1vD5I9J9I5kchyo8rg-unNS2vEiby1U5A" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1B4Nw-NLIaNNzt3BpYciiOYAQC2uR3XTY" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12PvUuJ2CLNqXVcx5wPVmWS2wWPh2Ugux" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www18.zippyshare.com/v/xtcopZu1/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www67.zippyshare.com/v/7s2hVh14/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www95.zippyshare.com/v/GDGOhEaK/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www95.zippyshare.com/v/GDGOhEaK/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 10</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/32900102/neonime_king_s_raid_-_iwt_-_10-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1YMHN4lx9CdKbHT9eE0p846_VA1533EId" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hlU7_m6IzkgyJW8h-Hs9bVhUA_uLSgaP" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1xAZMx3_v_lSfLLyUnbIWzhceAW63osIp" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www97.zippyshare.com/v/zOTGDGqL/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www1.zippyshare.com/v/QD15tv5p/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www42.zippyshare.com/v/ztD8sZdo/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www9.zippyshare.com/v/f5ukvnVd/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 11</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/33329114/neonime_king_s_raid_-_iwt_-_11-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1-XNNkPiHVJRVR1xbWVJDMrSPgNoed_V2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1cSIK03rdkSzON7_magrA9E-wppc8udZ8" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1sZDq1QGrr8_bxEZHVNT8Ud7aPV1NMNTp" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www41.zippyshare.com/v/gvwZ3fmv/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www78.zippyshare.com/v/Vz1akYFl/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www113.zippyshare.com/v/H8aHV10p/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www5.zippyshare.com/v/VZhzH8P3/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 12</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/33707327/neonime_king_s_raid_-_iwt_-_12-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=12vW6iuTLXSOGO1UMv_1EnuXpiEpAWDAK" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bDctLK7_D276aieDYeWBDwmmp7Tmq06h" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1WtFWTV2sFvO9nYjf_o5-7vE9m14JsEp7" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www12.zippyshare.com/v/N8ki7wpn/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www98.zippyshare.com/v/el8zbqX4/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www32.zippyshare.com/v/7i5O8HhA/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www76.zippyshare.com/v/KaSNvZH8/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 13</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/34144645/neonime_king_s_raid_-_iwt_-_13-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bugoDMwbJOfCQPVoBCTnuZbywYuA0e3M" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1S-G5x6Jw1zxxgDIOSiEaCjLeKhveqnX7" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1FKVCJi3_Sk_C3-ZGLQqOOXGLB_Ty7QOo" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www58.zippyshare.com/v/CqDpiI1Z/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www79.zippyshare.com/v/ZlS01tWD/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www119.zippyshare.com/v/u8ZsNGa1/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www45.zippyshare.com/v/bPFHinP5/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 14</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/34156501/neonime_king_s_raid_-_iwt_-_14-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1LV0CBtJ-rNgALWMM7QEhs-7w1Tb3WpXS" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IbtiyARriqDfWdoC5wjLVa19eMRjWluS" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15T173pkg1ZK5dqkU0_EUbNj65Yh2J7Ot" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www48.zippyshare.com/v/l35K6des/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www29.zippyshare.com/v/WowZty9u/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www70.zippyshare.com/v/IUasvo5i/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www52.zippyshare.com/v/rO0rVh2s/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 15</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/35042416/neonime_king_s_raid_-_iwt_-_15-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=13UmRlzYmz1c2lyoB6pGMLOc1tuMFit7O" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1nVRzExz9HmxaeMPKqAzOZdvlcL4ZBc0k" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15MmfoBRjRI5do9xFcnQdX0O3BEOOayaO" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www48.zippyshare.com/v/BKNzRvfu/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www73.zippyshare.com/v/04v5l2gL/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www66.zippyshare.com/v/ZZs8dxtR/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www113.zippyshare.com/v/JMzsFvZK/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 16</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/35425346/neonime_king_s_raid_-_iwt_-_16-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1ImoD8sbwNOD5mbme8G6InNnPp2XNboV5" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1byBkXnej7BsBHiWPvMZ3Uc8fnfOR5s8F" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1eVzuPGs9T2ZUR1pBPVfHdFizjqd_zxoo" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www20.zippyshare.com/v/kI28AbTf/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www40.zippyshare.com/v/FYEdInFd/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www106.zippyshare.com/v/8kimFQgM/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www95.zippyshare.com/v/jZE2dg7Y/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 17</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/35867764/neonime_king_s_raid_-_ishi_o_tsugu_mono-tachi_-_17-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1caFcizOVHtgG0RXDfbZS1SCvpNe76U9l" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1NgkvPvFt6zocbUpJfWe_c-ksOWSOZSVZ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1wI4-KA8_eiQl11yAhqYIPm0GZt_41aa_" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www32.zippyshare.com/v/FslRqalC/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www12.zippyshare.com/v/D9bbCXCf/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www85.zippyshare.com/v/GZYQpy78/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www53.zippyshare.com/v/reN0spAu/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 18</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/36307469/neonime_king_s_raid_-_ishi_o_tsugu_mono-tachi_-_18-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1_HYVStHhotY_yLmwphYZgrogVBIXvGBH" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1UW4KYaJie16Qylp7Wy7-3pKGJq0OuKR4" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1e3q06IIdiJnZFqZ8KsnxYD-PUFQBp4A1" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www108.zippyshare.com/v/CuPIy6by/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www58.zippyshare.com/v/8dXPksIB/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www114.zippyshare.com/v/IntQ2bIp/file.htmlhttps://www.solidfiles.com/v/88KkXqqwMqVzp" target="_blank" rel="noopener">720p</a>] [<a href="https://www60.zippyshare.com/v/0B3TNFZj/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 19</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/7GXX2aWkmmnmp" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1CTMioBktRMuhHcdloGQ9Fem6cJRM2oCY" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1cGG9tLBTpPFrw0WfU94JfHlPIqb9armN" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dNBkjDnf2SfSBKyYeBBRbPMXUEQaz3aw" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www94.zippyshare.com/v/JKdjPxMQ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www50.zippyshare.com/v/MrvoYH01/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www80.zippyshare.com/v/ZHCGbkQJ/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www82.zippyshare.com/v/NicXX3O2/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 20</b></p>
<div>GDrive =&gt; [360p] [<a href="https://drive.google.com/uc?export=download&amp;id=1D8VQMpKJTie3dP5tTJ361asOWYhM031p" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1IWrfqMzbSlOJLhA-24BN_BLJAaUbRPBY" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1lKnOVlIN71388QELP_QejOH8nGxCucvI" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [360p] [<a href="https://www14.zippyshare.com/v/hWnYc20Y/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www21.zippyshare.com/v/7jTC37GX/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://mir.cr/HWFZIPCE" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 21</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/37586002/neonime_king_s_raid_-_ishi_o_tsugu_mono-tachi_-_21-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=16nUnuJ1dUQHvuVz5GtOx344SLZ_WG_z2" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QTMDQxahTYJgeRLFfkJvz1hjT_Z41ej1" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bzMCTIKlLBL7hFKRoPE5pWNO4vApjE8C" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www118.zippyshare.com/v/kcLBdvMY/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www56.zippyshare.com/v/EczUc7BF/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www74.zippyshare.com/v/w0NivKTn/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www4.zippyshare.com/v/R8UGUyUV/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 22</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/38031781/neonime_king_s_raid_-_ishi_o_tsugu_mono-tachi_-_22-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1upeuudd4OOUfVJ4nm6_Z9XGUeCNXXbLI" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QCY-cMo5LMeRZizGXUv-upb8kpvmeITJ" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1v23JyiqtKbGcgDKRfa912lWXqXCFY16o" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www18.zippyshare.com/v/vfDD2CcJ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www84.zippyshare.com/v/xumTb45M/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www49.zippyshare.com/v/KAfPbXu4/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www48.zippyshare.com/v/yjYkc9dH/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 23</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/38561199/neonime_kings-raid-ishi-wo-tsugu-mono-tachi-23-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1MiYO-0TUu-igA3bpTKHj_WFWeyfniKSk" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1fm8KIK5ba8ZZsNzxhcLeZXFJu6pa6byg" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1hGrh6B5pdcbIEnrAhD5VJGSOJuGAwALf" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www101.zippyshare.com/v/b3lCmzOW/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www113.zippyshare.com/v/W1la1xjZ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www106.zippyshare.com/v/0mURBraE/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www67.zippyshare.com/v/ec1BIJv0/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 24</b></p>
<div>GDrive =&gt; [<a href="http://www.solidfiles.com/v/88XX2ZnKRmGNv" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1QK7u0hPZlUqWELnub7FKvmH3M6Crb1fF" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1GNQbwJBiT8nbalqkWwpQ0Ak38fsJs_se" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=15uBYiIge8b1p-b-BGJYL6T0eRPadbQ9X" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://www102.zippyshare.com/v/IWPG6FFZ/file.html" target="_blank" rel="noopener">360p</a>] [<a href="https://www6.zippyshare.com/v/pLdtmodQ/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www101.zippyshare.com/v/EheCv8cn/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www69.zippyshare.com/v/aOEG7XAo/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 25</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/40034937/neonime_king_s_raid_-_ishi_o_tsugu_mono-tachi_-_25-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1pJdoWqSqCzn_pZtQ5NOlJrnLWQW9e-C8" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1bYlXQ0LSH3Ao2kl4Pt1jhHA2EPc1TTVr" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1zbgR7dfOLtriiSogpS4F7TUUXuk_XMpt" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/NLIKYVJ6" target="_blank" rel="noopener">360p</a>] [<a href="https://www70.zippyshare.com/v/ckpvWBNj/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www100.zippyshare.com/v/tfGjqcwA/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www112.zippyshare.com/v/YTimZsEg/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
<div><b>King’s Raid: Ishi wo Tsugumono-tachi - Episode 26 END</b></p>
<div>GDrive =&gt; [<a href="https://acefile.co/f/40720195/neonime_king_s_raid_ishi_wo_tsugu_mono-tachi_-_26_end-360p-zip" target="_blank" rel="noopener">360p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1dB_qhsbuAAivEaTyv31aCn_Dm3F8gelb" target="_blank" rel="noopener">480p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1mc1oBp8tSMNOoBdKq6FJXwlL6zz2jekx" target="_blank" rel="noopener">720p</a>] [<a href="https://drive.google.com/uc?export=download&amp;id=1muxTjME_ec0gkqfZoDgngZsoOkUPW3q7" target="_blank" rel="noopener">1080p</a>]<br />Zshare =&gt; [<a href="https://mir.cr/QOEGEYDE" target="_blank" rel="noopener">360p</a>] [<a href="https://www70.zippyshare.com/v/QBliFL0C/file.html" target="_blank" rel="noopener">480p</a>] [<a href="https://www106.zippyshare.com/v/O2VVlbdS/file.html" target="_blank" rel="noopener">720p</a>] [<a href="https://www43.zippyshare.com/v/LjnK23Qq/file.html" target="_blank" rel="noopener">1080p</a>]</div>
</div>
</div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> </div>
