---
layout: post
title: Is This a Zombie Season 1-2 English Dub Download
date: 2022-06-17 16:39:16.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Anime
tags: []
meta:
  rank_math_internal_links_processed: '1'
  rank_math_analytic_object_id: '5607'
  _wpas_done_all: '1'
  cyberseo_rss_source: https://www.animesenpai4u.com/atom.xml
  cyberseo_post_name: is-this-a-zombie-season-1-2-english-dub-download
  cyberseo_post_link: https://www.animesenpai4u.com/2022/06/is-this-zombie-season-1-2-english-dub.html
  _thumbnail_id: '29453'
  cyberseo_thumb_source: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhh-c0GVzxCWr5ufEHgXEw6XmdZfM7mUiqAMXrcEQVMCYhCRuGBaqVLvAoUErYjQsPKyAw4BbZdk1mQxd_dg19eQmo7GR9oMlooNRcKC7soXJD9Kny4qKTTU7_7rqTsbXye16Hs8pe0Qbffpm8HhItVxfFdKV69nDeioTRCYDug4wpbs7ssmns-TLh/s320/magicalgamertm_mg-20220617-0001.jpg
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/is-this-a-zombie-season-1-2-english-dub-download/"
---
<h1 style="text-align: left;"><span style="color: #444444; font-family: arial;">Download Kore wa Zombie Desu ka (Is This a Zombie) (Season 1,2+ OVA) English Dubbed Subbed Dual Audio</span></h1>
<div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhh-c0GVzxCWr5ufEHgXEw6XmdZfM7mUiqAMXrcEQVMCYhCRuGBaqVLvAoUErYjQsPKyAw4BbZdk1mQxd_dg19eQmo7GR9oMlooNRcKC7soXJD9Kny4qKTTU7_7rqTsbXye16Hs8pe0Qbffpm8HhItVxfFdKV69nDeioTRCYDug4wpbs7ssmns-TLh/s1440/magicalgamertm_mg-20220617-0001.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="1439" data-original-width="1440" height="320" src="{{ site.baseurl }}/assets/2022/06/magicalgamertm_mg-20220617-0001.jpg" width="320" /></a></div>
<p><span style="background-color: white; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px;">Ayumu Aikawa is a 16-year-old high school student who is tragically murdered while investigating a suspicious house. However, he soon awakens next to a strange armored girl called Eucliwood Hellscythe.</span>
<p style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px; line-height: 26px; list-style: none; margin: 0px 0px 25px; outline: none; padding: 0px;"></p>
<p style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px; line-height: 26px; list-style: none; margin: 0px; outline: none; padding: 0px;">She reveals herself to be a necromancer who has revived Ayumu, consequently turning him into a zombie! Now immortal, Ayumu sets out to hunt down his killer. One day, while searching in a cemetery, he encounters a boisterous young girl named Haruna, who is fighting a bear with a chainsaw while dressed as a magical girl. After she kills the beast, Haruna attempts to erase Ayumu’s memories of her, but he instead absorbs her magic for himself. Stripped of her powers, Haruna now orders Ayumu to take up her role of hunting strange creatures known as “Megalo,” monsters that roam the human world and terrorize the population. Kore wa Zombie Desu ka? follows the daily antics of the human-turned-zombie Ayumu as he begins his new, ludicrous life where the supernatural becomes the norm. [Written by MAL Rewrite]</p>
<p style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px; line-height: 26px; list-style: none; margin: 0px; outline: none; padding: 0px;"></p>
<p style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; line-height: 26px; list-style: none; margin: 0px; outline: none; padding: 0px;"><b><span style="font-size: x-large;">Information</span></b></p>
<p style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px; line-height: 26px; list-style: none; margin: 0px; outline: none; padding: 0px;"></p>
<ul style="background-color: white; border: 0px; box-sizing: border-box; color: #2c2f34; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, &quot;Open Sans&quot;, Arial, sans-serif; font-size: 15px; list-style: none; margin: 0px 0px 20px 20px; outline: none; padding: 0px 0px 0px 15px;">
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Type: TV</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Episodes: 12</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Status: Finished Airing</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Aired: Jan 11, 2011 to Mar 30, 2011</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Premiered: Winter 2011</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Broadcast: Unknown</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Producers: Kadokawa Shoten, AT-X, Kadokawa Pictures Japan, KlockWorx, flying DOG</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Licensors: Funimation</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Studios: Studio Deen</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Source: Light novel</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Genres: Action, Comedy, Ecchi, Harem, Magic, Supernatural</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Duration: 24 min. per ep.</li>
<li style="border: 0px; box-sizing: border-box; list-style: none disc; margin: 0px 0px 5px; outline: none; padding: 0px;">Rating: R – 17+ (violence &amp; profanity)</li>
</ul>
<div>
<h3 style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: white; font-family: Hanuman, Ruda, sans-serif; font-size: 21px; margin: 0px 0px 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; color: #444444; font-family: arial; font-size: large; outline: 0px; padding: 0px; vertical-align: baseline;">Is This a Zombie Anime Season 1-2 English Dubbed or Subbed Downloading link given below :&nbsp;</span></h3>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; font-size: 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b style="background: 0px 0px; border: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">Download All Episode of Is This a Zombie Anime English Dub/Sub</b>&nbsp;from here for free.&nbsp;All links are given from the highest servers possible. There are two ways to&nbsp;<b style="background: 0px 0px; border: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">download Is This a Zombie Season 1, Season 2 Episodes</b>. You can download either one by or all episode Check the options below.</span></div>
</div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; font-size: 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><br /></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="color: red; font-size: x-large;">Season 1&nbsp;</span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">480p - <a href="https://mega.nz/folder/d2IxgCJY#WxAudjJ18IN_HXio19tWKw" target="_blank" rel="noopener">Watch/Download</a></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">720p - <a href="https://mega.nz/folder/d2IxgCJY#WxAudjJ18IN_HXio19tWKw" target="_blank" rel="noopener">Watch/Download</a></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">1080p - <a href="https://mega.nz/folder/d2IxgCJY#WxAudjJ18IN_HXio19tWKw" target="_blank" rel="noopener">Watch/Download</a></span></b></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; font-size: 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><br /></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; font-size: 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><br /></span></div>
<div style="background: 0px 0px rgb(255, 255, 255); border: 0px; color: #656565; font-family: Hanuman, Ruda, sans-serif; font-size: 15px; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;" />
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">Season 2</span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">480p - Watch/Download</span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">720p - Watch/Download</span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
<div style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; font-family: Hanuman, Ruda, sans-serif; font-size: medium; outline: 0px; padding: 0px; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;">1080p - Watch/Download</span></b></span></div>
<div><span style="background: 0px 0px; border: 0px; font-family: arial; outline: 0px; padding: 0px; vertical-align: baseline;"><b><span style="font-size: x-large;"><br /></span></b></span></div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> <br /><a href="https://www.animesenpai4u.com/2022/06/is-this-zombie-season-1-2-english-dub.html">Source</a> </div>
