---
layout: post
title: Download Anime Lycoris Recoil Sub Indonesia
date: 2022-09-05 07:28:55.000000000 +00:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Action
- Anime
- Batch
- BD
- Comedy
- Slice of Life
tags:
- Action
- Anime
- Batch
- BD
- Comedy
- Slice of Life
meta:
  rank_math_internal_links_processed: '1'
  _wpas_done_all: '1'
  cyberseo_rss_source: https://drivenime.com/feed/
  cyberseo_post_name: download-anime-lycoris-recoil-sub-indonesia
  cyberseo_post_link: https://drivenime.com/download-anime-lycoris-recoil-sub-indonesia/
  _thumbnail_id: '29403'
  cyberseo_thumb_source: https://drivenime.com/wp-content/uploads/2022/09/Download-Anime-Lycoris-Recoil-Sub-Indonesia.jpg
  litespeed_vpi_list: a:1:{i:0;s:12:"empty result";}
author:
  login: admin
  email: senseads014@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
permalink: "/download-anime-lycoris-recoil-sub-indonesia/"
---
<h1><a href="https://drivenime.com/download-anime-lycoris-recoil-sub-indonesia/download-anime-lycoris-recoil-sub-indonesia-2/" rel="attachment wp-att-12849" data-wpel-link="internal"><img class="aligncenter size-full wp-image-12849" src="{{ site.baseurl }}/assets/2022/09/Download-Anime-Lycoris-Recoil-Sub-Indonesia.jpg" alt="Download Anime Lycoris Recoil Sub Indonesia" width="600" height="320" srcset="https://drivenime.com/wp-content/uploads/2022/09/Download-Anime-Lycoris-Recoil-Sub-Indonesia.jpg 600w, https://drivenime.com/wp-content/uploads/2022/09/Download-Anime-Lycoris-Recoil-Sub-Indonesia-300x160.jpg 300w" sizes="(max-width: 600px) 100vw, 600px" /></a></h1>
<h1>Sinopsis</h1>
<p>Berfokus pada tokoh bernama Takina Inoue, dia merupakan salah satu agen bersama dengan kemampuan mumpuni. Suatu hari, Takina membuat kekeliruan fatal agar dia dipindahtugaskan ke sebuah &#8216;kafe&#8217; yang menaruh rahasia. Bersama teman barunya, Chisato Nishikigi, Takina akan studi banyak hal dalam hidup yang kudu Takina mengerti.</p>
<h2 style="text-align: justify;">Information</h2>
<ul>
<li style="text-align: justify;">Judul: Lycoris Recoil</li>
<li style="text-align: justify;">Judul Alternatif: &#8211;</li>
<li style="text-align: justify;">Tipe: Series</li>
<li style="text-align: justify;">Jumlah Episode: 13</li>
<li style="text-align: justify;">Status: Finished Airing</li>
<li style="text-align: justify;">Studio: A-1 Pictures</li>
<li style="text-align: justify;">Musim: Summer 2022</li>
<li style="text-align: justify;">Genre: Action, Comedy, Slice of Life</li>
<li style="text-align: justify;">Durasi: 24 min. per ep.</li>
<li style="text-align: justify;">Score: 7.73</li>
</ul>
<h4>Lycoris Recoil Episode 10 — HunterSekai</h4>
<ul class="ini_ep1">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1MS56aXBweXNoYXJlLmNvbS92L29UYkNsN2RGL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xTENtM194T0JDdkZ0YjNPcHVxVUFKcFhKY29IZVV1dlEvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI4OTczNjUvbHljb3Jpc19yZWNvaWxfLV8xMF8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vN2hmZHR6NjU2YTRq" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVpUTy9MeWNvcmlzX1JlY29pbF8tXzEwX1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1MS56aXBweXNoYXJlLmNvbS92L2FoZXdoSFR2L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xb0ROS1VVb3htU1ZLWFJCY29LbFVQYVBnZVZaLXlkTmgvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI4OTczNjMvbHljb3Jpc19yZWNvaWxfLV8xMF83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdTExcGkzaG05MTU0" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVpUTi9MeWNvcmlzX1JlY29pbF8tXzEwX1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1MS56aXBweXNoYXJlLmNvbS92L05pbjFXZkc2L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xRkE0LWlCdWRXbktYemFSWmM2REFwLTBSZlYtbDNEWG8vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI4OTczNjIvbHljb3Jpc19yZWNvaWxfLV8xMF80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vM3hhdjJuZnhrbno5" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVpUTS9MeWNvcmlzX1JlY29pbF8tXzEwX1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1MS56aXBweXNoYXJlLmNvbS92L3JSY2p2VkdGL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xX1h1Y3NzSkU0eWd6UnBvY2N6OW9uVGktTDZGNlp0MUEvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI4OTczNjEvbHljb3Jpc19yZWNvaWxfLV8xMF8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vbmIzdDBzMXNncTlk" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVpUTC9MeWNvcmlzX1JlY29pbF8tXzEwX1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1MS56aXBweXNoYXJlLmNvbS92L0ZEMnlmclpvL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xTDVsdEI3THBNSVFvZURJUTdvdHNCZ2ZXOU1mMWotZFkvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI4OTczNjAvbHljb3Jpc19yZWNvaWxfLV8xMF8yNDBwLTEtbXA0" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vd2QzemV0Z3RjMHp6" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVpUSy9MeWNvcmlzX1JlY29pbF8tXzEwX1syNDBwXV8oMSkubXA0" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 09 — HunterSekai</h4>
<ul class="ini_ep2">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L0tWYlRBRGplL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xRkZtdEN4VF9DOU1JTllHYXotNjdkdjg5Z3Y4TFNLSFQvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI0MjM4NTIvbHljb3Jpc19yZWNvaWxfLV8wOV8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdjhhbG45bGozMWps" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVplZy9MeWNvcmlzX1JlY29pbF8tXzA5X1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L0hoM0N6MEt6L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xenYyTXhtdEhJMFlaaUhLUEx0Y3RUYlQ4cTFqV1VQTDEvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI0MjM4NTEvbHljb3Jpc19yZWNvaWxfLV8wOV83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vazdjNWl4a2N5cHBh" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVplYy9MeWNvcmlzX1JlY29pbF8tXzA5X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92LzhETUNKSmk4L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xQXFQX3RDcThVZjZudXdBSmFzN3RfcFVFTy1nMS12cm0vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI0MjM4NDgvbHljb3Jpc19yZWNvaWxfLV8wOV80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNW9zNnVucWNiYWtq" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVplZC9MeWNvcmlzX1JlY29pbF8tXzA5X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyOC56aXBweXNoYXJlLmNvbS92L1FTZW9JdmtvL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xZDR4am9Nd25HaThYbF8yVUVUTm51TVB3RkhRaHFzanEvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI0MjQwMDIvbHljb3Jpc19yZWNvaWxfLV8wOV8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdXB1bnJiaDB2aHJw" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVplaS9MeWNvcmlzX1JlY29pbF8tXzA5X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyOC56aXBweXNoYXJlLmNvbS92LzU5RDRDT25JL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xVVhMS2tHa0RQNHNSVnNER2xkR1JkQVpJNFV1eUNqYV8vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODI0MjQwMDAvbHljb3Jpc19yZWNvaWxfLV8wOV8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vOWZ5YTZwaDFvZGdh" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVplaC9MeWNvcmlzX1JlY29pbF8tXzA5X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 08 — HunterSekai</h4>
<ul class="ini_ep3">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDkuemlwcHlzaGFyZS5jb20vdi9GdW16OTNTNS9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xX01kQkwzVGtKQUZuNGNVOFBBRnhJOFpJTVYxNXdMOUUvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE5NTA2NzAvbHljb3Jpc19yZWNvaWxfLV8wOF8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vZmV1NWdzczF4Mzhh" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVl5TC9MeWNvcmlzX1JlY29pbF8tXzA4X1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDkuemlwcHlzaGFyZS5jb20vdi9tWnU2MGFyai9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xNzFXSWNsTXJOcm02X0RJVWsyRS0tQjZLZDNJVzNGMHYvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE5NTA2NjkvbHljb3Jpc19yZWNvaWxfLV8wOF83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vYmtneWlwdWQ5bnQ0" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVl5Sy9MeWNvcmlzX1JlY29pbF8tXzA4X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDkuemlwcHlzaGFyZS5jb20vdi9wSWVETUxuei9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xYjZJcThIeGtjX3FaNi1aYmRwdnVLM3Y3RTJ6UE9lTE8vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE5NTA2NjYvbHljb3Jpc19yZWNvaWxfLV8wOF80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vN2kwOTZzZ2lvenQ1" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVl5Si9MeWNvcmlzX1JlY29pbF8tXzA4X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDkuemlwcHlzaGFyZS5jb20vdi9jdmNzYXk0MS9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xa0EyVU5IUTZydGlYWmpHazhfRUhqQ251Vng4V1E1TzIvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE5NTA2NjQvbHljb3Jpc19yZWNvaWxfLV8wOF8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28veTAyOTFnOTRwYm5q" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVl5SC9MeWNvcmlzX1JlY29pbF8tXzA4X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDkuemlwcHlzaGFyZS5jb20vdi9hTUhzSGJTYi9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xX0Zrd3dwejZ2Ym5iR0lId1FOeXFTRkhNMWJ4YWxtSVgvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE5NTA2NjEvbHljb3Jpc19yZWNvaWxfLV8wOF8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdjM1ZzRkZWh3NDdp" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVl5Ry9MeWNvcmlzX1JlY29pbF8tXzA4X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 07 — HunterSekai</h4>
<ul class="ini_ep4">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L1B6UkZEU1NIL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xbWdXT1NzUlU2UWI4dTBoNkpBRUE0ZC1NR3R5dXlQTTIvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE0NDU0NzYvbHljb3Jpc19yZWNvaWxfLV8wN18xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vaTJmc2NxZ2M5a2hx" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVh1TS9MeWNvcmlzX1JlY29pbF8tXzA3X1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L01zeGp0TmlOL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xb2FBWVd2VFprUXViREtxdnVmMXZNT0otcFBMWi1vWmgvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE0NDU0NzUvbHljb3Jpc19yZWNvaWxfLV8wN183MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcHZxdWt0Y2lmaTRp" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVh1TC9MeWNvcmlzX1JlY29pbF8tXzA3X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L3Q0T0diWTBkL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xc0xQMnF4WkdwU2J0b3hveEdlMnhuenpHUTZhNU55VlUvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE0NDU0NzMvbHljb3Jpc19yZWNvaWxfLV8wN180ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNDkzdnY4Y2UxczQ4" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVh1Sy9MeWNvcmlzX1JlY29pbF8tXzA3X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92LzJocVBzNzN2L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xcXk5a2NWc3pOZjdCbG91S3cyc01sSXVGTEpMSWIzT0Yvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE0NDU0NzIvbHljb3Jpc19yZWNvaWxfLV8wN18zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdnU4ZmNraXE5ajZ1" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVh1Si9MeWNvcmlzX1JlY29pbF8tXzA3X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c2MS56aXBweXNoYXJlLmNvbS92L2ZVMFR2YTluL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xTnZUNkozTTNjOVZBYWNxbmtFMlUxT0tzUjNRLXA1d1Yvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODE0NDU0NzEvbHljb3Jpc19yZWNvaWxfLV8wN18yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vd3BqcWtid20wYWRz" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVh1SS9MeWNvcmlzX1JlY29pbF8tXzA3X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 06 — HunterSekai</h4>
<ul class="ini_ep5">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyNy56aXBweXNoYXJlLmNvbS92L3Y3S3BIU3BvL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xSWxOa0dZajV1amxsSlBDV3BTNFdQejZfcU1CSTBxMmsvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA5ODQwNTEvbHljb3Jpc19yZWNvaWxfLV8wNl8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vaWk2MXg4NnF1bGJp" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVdMNC9LRC1TNC0xOC00ODBwLm1wNGh0dHBzOi8vZmFzdGRyaXZlLmlvLzVXTGQvTHljb3Jpc19SZWNvaWxfLV8wNl9bMTA4MHBdLm1rdg==" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c5My56aXBweXNoYXJlLmNvbS92L2tDYlR4WmM3L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xVVFfc3d1b0N0OHBJNXYtS0pKLW9rbDU3eVZQU25ETy0vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA5ODQwNTAvbHljb3Jpc19yZWNvaWxfLV8wNl83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28veGNieHo3bHI0czY5" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVdMOC9MeWNvcmlzX1JlY29pbF8tXzA2X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c5My56aXBweXNoYXJlLmNvbS92L1QwMWx0c2E3L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xa0g0WnNOS0FseEw4SUxjRkRqaGZtVUEyT1NaN2lpRU4vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA5ODQwNDgvbHljb3Jpc19yZWNvaWxfLV8wNl80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vZXI5ZGo2OG9uaGgz" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVdMNy9MeWNvcmlzX1JlY29pbF8tXzA2X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c5My56aXBweXNoYXJlLmNvbS92LzdOa3NKUTcxL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xQXBKVVN5eUZILVNGbW1MLXJTSmJiQ2hCZkM4YWxZODgvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA5ODQwNDcvbHljb3Jpc19yZWNvaWxfLV8wNl8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcHFwMnc3cW4xNGE2" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVdMNi9MeWNvcmlzX1JlY29pbF8tXzA2X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c5My56aXBweXNoYXJlLmNvbS92L25GY1MwMTBHL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xRUtmRXhiNTRuS2dPaXdLVHROQTRENU9aRWxENUJsTEsvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA5ODQwNDYvbHljb3Jpc19yZWNvaWxfLV8wNl8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vaTFiYnB5d3dweHd0" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVdMNS9MeWNvcmlzX1JlY29pbF8tXzA2X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 05 — HunterSekai</h4>
<ul class="ini_ep6">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDAuemlwcHlzaGFyZS5jb20vdi9jWktxQTkwUy9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xamNjRjRkTjJqMHFreHFXdHdkYWw3Yk1GZXhwU09qeEYvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA1MDQ0OTUvbHljb3Jpc19yZWNvaWxfLV8wNV8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vM2I4YTQxbHVqNGU5" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVc5RC9MeWNvcmlzX1JlY29pbF8tXzA1X1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDAuemlwcHlzaGFyZS5jb20vdi9QZUZyVHlUVi9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xSkxVclllZFZWbWdJR0dVdWtXNTV6THZ3eG1OV2M2RW4vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA1MDQ0OTQvbHljb3Jpc19yZWNvaWxfLV8wNV83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vbjJkOXluaDhqejYz" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVc5Qy9MeWNvcmlzX1JlY29pbF8tXzA1X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDAuemlwcHlzaGFyZS5jb20vdi9YZXgwY2pPVi9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xd1VhT2ZYblZSNTJRVUJCbERYSWxDeXpnLVRsTHlyaHQvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA1MDQ0OTIvbHljb3Jpc19yZWNvaWxfLV8wNV80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdHdsN2NwOWd5eTR0" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVc5Qi9MeWNvcmlzX1JlY29pbF8tXzA1X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDAuemlwcHlzaGFyZS5jb20vdi9xR25OMVZ4MC9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xLXlnczNjbHlyZ2NqRnZsVXR2NGY2ZWxEZlZSODlBZ20vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA1MDQ0ODcvbHljb3Jpc19yZWNvaWxfLV8wNV8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vdmNoazN1dnJhZnc5" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVc5QS9MeWNvcmlzX1JlY29pbF8tXzA1X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDAuemlwcHlzaGFyZS5jb20vdi82R0JyWGtIUy9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xeWhGSkZCejNvUEwwcWhla0cxeHd4WWtWeVNIR2NlQUovdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODA1MDQ0ODMvbHljb3Jpc19yZWNvaWxfLV8wNV8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcm4ycGR6NDR2YXhl" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVc5ei9MeWNvcmlzX1JlY29pbF8tXzA1X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 04 — HunterSekai</h4>
<ul class="ini_ep7">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1NC56aXBweXNoYXJlLmNvbS92L29ra0p4Z3M4L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xbHQyc0htcDZueVBvSDJ6VENSZGpudTk4STdvV2pqbDkvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODAwMzg3MzcvbHljb3Jpc19yZWNvaWxfLV8wNF8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNXJ3aGFjcXE5cXRl" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVY4Ri9MeWNvcmlzX1JlY29pbF8tXzA0X1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1NC56aXBweXNoYXJlLmNvbS92L3FqZ0VHSnkwL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xbV9QLVVUT3M4cWhyU2RiRXZVUlNaYWwwNDY5aS1wMlMvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODAwMzg3MzYvbHljb3Jpc19yZWNvaWxfLV8wNF83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNHd6cjc4czI0dGJr" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVY4RS9MeWNvcmlzX1JlY29pbF8tXzA0X1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1NC56aXBweXNoYXJlLmNvbS92L1lsdnhTcXdXL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xRUtzQUpKUzZEcEdSSFk5UDhqa1BrNDAtUVMydGlVdFIvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODAwMzg3MzQvbHljb3Jpc19yZWNvaWxfLV8wNF80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vZGhjbGhxdWxrY2po" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVY4RC9MeWNvcmlzX1JlY29pbF8tXzA0X1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1NC56aXBweXNoYXJlLmNvbS92L2ZtMDVBS0ZsL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xR3JBZ2I4WTBDeWdjLTAyVVlhSENxZzdNRFZDVGlLQXovdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODAwMzg3MzMvbHljb3Jpc19yZWNvaWxfLV8wNF8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28veXMyYnJzMzN6Y3M4" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVY4Qy9MeWNvcmlzX1JlY29pbF8tXzA0X1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c1NC56aXBweXNoYXJlLmNvbS92LzJodWVoNW1nL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xQVdXVEctd0UwVDRPMHBIa0N6UHJYY1N3Nkg0WFJHaTQvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvODAwMzg3MzIvbHljb3Jpc19yZWNvaWxfLV8wNF8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vMjQ0NTZycWQ2enA5" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVY4Qi9MeWNvcmlzX1JlY29pbF8tXzA0X1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 03 — HunterSekai</h4>
<ul class="ini_ep8">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDcuemlwcHlzaGFyZS5jb20vdi9HM3g5UU56cC9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xYWFaODJHR3B4MFJmVFVlazBRZFRIZm5hM0hTLU4ycm8vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzk1MzgyMDQvbHljb3Jpc19yZWNvaWxfLV8wM18xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vYWU5cndmMnA4aTV2" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVVwNi9MeWNvcmlzX1JlY29pbF8tXzAzX1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDcuemlwcHlzaGFyZS5jb20vdi9qWDhncTFaVS9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xaThLeGEzNnZKREdBNnFrc0dzOVpnbmpCWXp1dDRmdk8vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzk1MzgyMDIvbHljb3Jpc19yZWNvaWxfLV8wM183MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vY3I0eGxlZTU4ODhx" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVVwNS9MeWNvcmlzX1JlY29pbF8tXzAzX1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDcuemlwcHlzaGFyZS5jb20vdi9xNjBMWU5aUi9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xMWJJdV9mVU42U0ozRVFoaVN5UWpRMHRvX25HT1NXVmEvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzk1MzgyMDEvbHljb3Jpc19yZWNvaWxfLV8wM180ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNmVjOTAwYnYwZGsy" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVVwNC9MeWNvcmlzX1JlY29pbF8tXzAzX1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDcuemlwcHlzaGFyZS5jb20vdi84MTNnY0JKQS9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xUDAwbzRldFhRSEN0TURfYnFXMi1GbnlveXB5XzJjWjQvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzk1MzgxOTkvbHljb3Jpc19yZWNvaWxfLV8wM18zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vc2g4N3ZhMnJqZnV6" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVVwMy9MeWNvcmlzX1JlY29pbF8tXzAzX1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cxMDcuemlwcHlzaGFyZS5jb20vdi9aSktkcVlRYy9maWxlLmh0bWw=" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xVU5EMkEtRUNmaTB0ZmpOV0pTNFB0N21GcGVCaE0tdk0vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzk1MzgxOTUvbHljb3Jpc19yZWNvaWxfLV8wM18yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vOHVyczRsaXM4aXJp" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVVwMi9MeWNvcmlzX1JlY29pbF8tXzAzX1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 02 — HunterSekai</h4>
<ul class="ini_ep9">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyMC56aXBweXNoYXJlLmNvbS92L05rMzhVMGhDL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xSktkUTRhcFJqZmRrQ0ZBR3lYOW9DWFpvMVdJc19pVFYvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzkwMDY2MjEvbHljb3Jpc19yZWNvaWxfLV8wMl8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcDc5eDJiamNibzhq" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRKci9MeWNvcmlzX1JlY29pbF8tXzAyX1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyMC56aXBweXNoYXJlLmNvbS92L1BaUzlRZEp4L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xaDdGR0tRTXlIckFjX1FVZTZUTzFLWkhxSkJ0elQ5VUQvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzkwMDY2MTkvbHljb3Jpc19yZWNvaWxfLV8wMl83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcnV0dnhqdXZrYnpn" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRKcS9MeWNvcmlzX1JlY29pbF8tXzAyX1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyMC56aXBweXNoYXJlLmNvbS92L09ZODQ0UGtKL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xVUp2dFRQT0J5X3hBdHg5eDZ2ekNqT0dlalhyTEY5Y0wvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzkwMDY2MTgvbHljb3Jpc19yZWNvaWxfLV8wMl80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vZnlqczl3OWU2OTB2" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRKcC9MeWNvcmlzX1JlY29pbF8tXzAyX1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyMC56aXBweXNoYXJlLmNvbS92L3RQN3NVRHBaL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xWk91dFpJSGFUcGQzWnIzNTUwOUo1M084Y0ljTHhSV2Evdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzkwMDY2MTUvbHljb3Jpc19yZWNvaWxfLV8wMl8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vbWQ0aGc5OGJncnJv" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRKby9MeWNvcmlzX1JlY29pbF8tXzAyX1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3cyMC56aXBweXNoYXJlLmNvbS92Lzl2MmZqQ09qL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xV2hIbjlHQy1hVGgwejFWTGtDRC1QVHdLWk0zY2hDSVgvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive </a><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzkwMDY2MTMvbHljb3Jpc19yZWNvaWxfLV8wMl8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vb3YxM2IyMWUzcGM1" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRKbi9MeWNvcmlzX1JlY29pbF8tXzAyX1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<h4>Lycoris Recoil Episode 01 — HunterSekai</h4>
<ul class="ini_ep10">
<li><strong>1080P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c3NC56aXBweXNoYXJlLmNvbS92L1ZzMEJmSTdTL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xckhnb1lzdGJiTHF2UU5yaHVpeElMeTdqb3FNS19PWW4vdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzg0ODgwNjAvbHljb3Jpc19yZWNvaWxfLV8wMV8xMDgwcC1ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28veGxlZml5MjFwZXMy" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRkWi9MeWNvcmlzX1JlY29pbF8tXzAxX1sxMDgwcF0ubWt2" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>720P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c3NC56aXBweXNoYXJlLmNvbS92L2hIVEdueW9mL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xa3BEbDVROEMxZGpiNG5QTHBQQmNQRmlaRE04ZmtGWUUvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzg0ODgwNTUvbHljb3Jpc19yZWNvaWxfLV8wMV83MjBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vcnNsbDhkZzd1eTRl" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRkWC9MeWNvcmlzX1JlY29pbF8tXzAxX1s3MjBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>480P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c3NC56aXBweXNoYXJlLmNvbS92L0ZGRnNxRzM2L2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xUUp5Wm0tQWlrWUh3N0dpeUJlNHVvM3ZHZW5rdnpmV3ovdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzg0ODgwNTIvbHljb3Jpc19yZWNvaWxfLV8wMV80ODBwLW1rdg==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vMG1rdHZ3Zm16bjgx" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRkVy9MeWNvcmlzX1JlY29pbF8tXzAxX1s0ODBwXS5ta3Y=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>360P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c3NC56aXBweXNoYXJlLmNvbS92L0hkV2JjRWtlL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xUGhWbTJxaEgwNHhPOUhEUVZTbUNmNWRQQVFjRlFkbUovdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzg0ODgwNDUvbHljb3Jpc19yZWNvaWxfLV8wMV8zNjBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vNTVldmhsMWdzeHRo" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRkVi9MeWNvcmlzX1JlY29pbF8tXzAxX1szNjBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
<li><strong>240P </strong><a href="https://lia.flashtik.com/?r=aHR0cHM6Ly93d3c3NC56aXBweXNoYXJlLmNvbS92L3l0Qm1nTmdxL2ZpbGUuaHRtbA==" data-wpel-link="external" rel="external noopener noreferrer">Zippy</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xWWhxc3AyWFFzYnpYMnRINFFkQW5BZnloVnlFMzFjV3Uvdmlldz91c3A9c2hhcmluZw==" data-wpel-link="external" rel="external noopener noreferrer">GDrive</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNzg0ODgwNDIvbHljb3Jpc19yZWNvaWxfLV8wMV8yNDBwLW1wNA==" data-wpel-link="external" rel="external noopener noreferrer">Gsharer</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9oeGZpbGUuY28vb240czA2eGl2dGNr" data-wpel-link="external" rel="external noopener noreferrer">HxFile</a> <a href="https://lia.flashtik.com/?r=aHR0cHM6Ly9mYXN0ZHJpdmUuaW8vNVRkVS9MeWNvcmlzX1JlY29pbF8tXzAxX1syNDBwXS5tcDQ=" data-wpel-link="external" rel="external noopener noreferrer">FDrive</a></li>
</ul>
<div class="related-post grid">
<div class="post-list ">
<div class="item"> <a class="title post_title" href="https://drivenime.com/cinderella-girls-gekijou-climax-season-sub-indonesia-1/" data-wpel-link="internal"> Cinderella Girls Gekijou: Climax Season Subtitle Indonesia Batch </a>
<div class="thumb post_thumb"> <a href="https://drivenime.com/cinderella-girls-gekijou-climax-season-sub-indonesia-1/" data-wpel-link="internal"> <img width="300" height="169" src="{{ site.baseurl }}/assets/2022/09/Cinderella-Girls-Gekijou-Climax-Season-Subtitle-Indonesia-Batch-300x169.jpg" class="attachment-medium size-medium wp-post-image" alt="" loading="lazy" srcset="https://drivenime.com/wp-content/uploads/2019/07/Cinderella-Girls-Gekijou-Climax-Season-Subtitle-Indonesia-Batch-300x169.jpg 300w, https://drivenime.com/wp-content/uploads/2019/07/Cinderella-Girls-Gekijou-Climax-Season-Subtitle-Indonesia-Batch-768x432.jpg 768w, https://drivenime.com/wp-content/uploads/2019/07/Cinderella-Girls-Gekijou-Climax-Season-Subtitle-Indonesia-Batch.jpg 1024w, https://drivenime.com/wp-content/uploads/2019/07/Cinderella-Girls-Gekijou-Climax-Season-Subtitle-Indonesia-Batch-150x84.jpg 150w" sizes="(max-width: 300px) 100vw, 300px" /> </a> </div>
<p class="excerpt post_excerpt"> Sinopsis Season terakhir Dari Series Cinderella Girls Gekijou sebelumnya. Informasi Type: TV Episodes: 13 Status: Finished Airing Start: Apr 2, 2019 End: Jun 25, 2019 Season: Spring 2019 Studios: Gathering, Lesprit Producers: - Source: 4-koma manga Duration: 3 <a class="read-more" href="https://drivenime.com/cinderella-girls-gekijou-climax-season-sub-indonesia-1/" data-wpel-link="internal"> Read more</a> </p>
</p></div>
<div class="item"> <a class="title post_title" href="https://drivenime.com/tamako-love-story-subtitle-indonesia-2/" data-wpel-link="internal"> Tamako Love Story Subtitle Indonesia </a>
<div class="thumb post_thumb"> <a href="https://drivenime.com/tamako-love-story-subtitle-indonesia-2/" data-wpel-link="internal"> <img width="300" height="169" src="{{ site.baseurl }}/assets/2022/09/Tamako-Love-Story-Subtitle-Indonesia-300x169.jpg" class="attachment-medium size-medium wp-post-image" alt="Tamako Love Story Subtitle Indonesia" loading="lazy" srcset="https://drivenime.com/wp-content/uploads/2017/07/Tamako-Love-Story-Subtitle-Indonesia-300x169.jpg 300w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Love-Story-Subtitle-Indonesia-768x432.jpg 768w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Love-Story-Subtitle-Indonesia-1024x576.jpg 1024w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Love-Story-Subtitle-Indonesia-150x84.jpg 150w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Love-Story-Subtitle-Indonesia.jpg 1280w" sizes="(max-width: 300px) 100vw, 300px" /> </a> </div>
<p class="excerpt post_excerpt"> Sinopsis Dera-chan, burung ajaib yang dapat bicara. Sekarang sedang tinggal di sebuah pulau yang jauh. Bersama Choi dan pangerannya, mereka mencoba membuat mochi setelah belajar banyak saat di rumah Tamako. Sementara itu, kehidupan orang-orang di pusat perbelanjaan Usagi, <a class="read-more" href="https://drivenime.com/tamako-love-story-subtitle-indonesia-2/" data-wpel-link="internal"> Read more</a> </p>
</p></div>
<div class="item"> <a class="title post_title" href="https://drivenime.com/takunomi-subtitle-indonesia-batch-1/" data-wpel-link="internal"> Takunomi. Subtitle Indonesia Batch </a>
<div class="thumb post_thumb"> <a href="https://drivenime.com/takunomi-subtitle-indonesia-batch-1/" data-wpel-link="internal"> <img width="300" height="300" src="{{ site.baseurl }}/assets/2022/09/Takunomi.-Subtitle-Indonesia-Batch-300x300.jpg" class="attachment-medium size-medium wp-post-image" alt="Takunomi. Subtitle Indonesia Batch" loading="lazy" srcset="https://drivenime.com/wp-content/uploads/2018/04/Takunomi.-Subtitle-Indonesia-Batch-300x300.jpg 300w, https://drivenime.com/wp-content/uploads/2018/04/Takunomi.-Subtitle-Indonesia-Batch-150x150.jpg 150w, https://drivenime.com/wp-content/uploads/2018/04/Takunomi.-Subtitle-Indonesia-Batch-50x50.jpg 50w, https://drivenime.com/wp-content/uploads/2018/04/Takunomi.-Subtitle-Indonesia-Batch.jpg 512w" sizes="(max-width: 300px) 100vw, 300px" /> </a> </div>
<p class="excerpt post_excerpt"> Sinopsis Amatsuki Michiru gadis berusia 20 tahun pindah ke Tokyo untuk pekerjaan. Dia memutuskan untuk tinggal di Share House khusus wanita "Stella House Haruno". Dia tinggal bersama dengan gadis lain dengan kerjaan dan usia yang berbeda-beda. Semua terasa <a class="read-more" href="https://drivenime.com/takunomi-subtitle-indonesia-batch-1/" data-wpel-link="internal"> Read more</a> </p>
</p></div>
<div class="item"> <a class="title post_title" href="https://drivenime.com/tamako-market-bd-subtitle-indonesia-batch-2/" data-wpel-link="internal"> Tamako Market BD Subtitle Indonesia Batch </a>
<div class="thumb post_thumb"> <a href="https://drivenime.com/tamako-market-bd-subtitle-indonesia-batch-2/" data-wpel-link="internal"> <img width="300" height="207" src="{{ site.baseurl }}/assets/2022/09/Tamako-Market-BD-Subtitle-Indonesia-Batch-300x207.jpg" class="attachment-medium size-medium wp-post-image" alt="Tamako Market BD Subtitle Indonesia Batch" loading="lazy" srcset="https://drivenime.com/wp-content/uploads/2017/07/Tamako-Market-BD-Subtitle-Indonesia-Batch-300x207.jpg 300w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Market-BD-Subtitle-Indonesia-Batch-768x530.jpg 768w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Market-BD-Subtitle-Indonesia-Batch-1024x706.jpg 1024w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Market-BD-Subtitle-Indonesia-Batch-150x103.jpg 150w, https://drivenime.com/wp-content/uploads/2017/07/Tamako-Market-BD-Subtitle-Indonesia-Batch.jpg 1044w" sizes="(max-width: 300px) 100vw, 300px" /> </a> </div>
<p class="excerpt post_excerpt"> Sinopsis Staf dari anime K-ON kembali bereuni untuk memproduksi anime terbaru dari KyoAni yitu Tamako Market. Tamako anak pemilik toko mocchi wajar jika sebagian besar yang ada di pikiran cewek imut ini hanyalah mocchi. Tamako memiliki teman dekat <a class="read-more" href="https://drivenime.com/tamako-market-bd-subtitle-indonesia-batch-2/" data-wpel-link="internal"> Read more</a> </p>
</p></div>
</p></div>
<p> <script> </script><br />
<style> .related-post{} .related-post .post-list{ text-align:left; } .related-post .post-list .item{ margin:10px; padding:0px; } .related-post .headline{ font-size:18px !important; color:#999999 !important; } .related-post .post-list .item .post_title{ font-size:16px; color:#3f3f3f; margin:10px 0px; padding:0px; display: block; text-decoration: none; } .related-post .post-list .item .post_thumb{ max-height:220px; margin:10px 0px; padding:0px; display: block; } .related-post .post-list .item .post_excerpt{ font-size:13px; color:#3f3f3f; margin:10px 0px; padding:0px; display: block; text-decoration: none; } @media only screen and (min-width: 1024px ){ .related-post .post-list .item{ width: 45%; } } @media only screen and ( min-width: 768px ) and ( max-width: 1023px ) { .related-post .post-list .item{ width: 90%; } } @media only screen and ( min-width: 0px ) and ( max-width: 767px ){ .related-post .post-list .item{ width: 90%; } } </style>
</p></div>
<p>The post <a rel="nofollow" href="https://drivenime.com/download-anime-lycoris-recoil-sub-indonesia/" data-wpel-link="internal">Download Anime Lycoris Recoil Sub Indonesia</a> appeared first on <a rel="nofollow" href="https://drivenime.com" data-wpel-link="internal">Drivenime</a>.</p>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="divbtn"> <a href="https://handymansurrender.com/fihup8buzv?key=94550f7ce39444073321dde3b8782f97" class="btn"><i class="fa fa-download"></i> Direct Link</a> <br /><a href="https://drivenime.com/download-anime-lycoris-recoil-sub-indonesia/">Source</a> </div>
